import type { LessonDetail } from "@/lib/lessonContent";

export const supplementalLessonContent = {
  "math-foundations": {
    lead: "这一章从零解释后面反复出现的数学词。我们始终使用同一条‘看到红杯并生成三步动作’样本，先说明每个概念在解决什么问题，再写符号、代数字、运行脚本。你不需要预先学过概率论、强化学习或微分方程。",
    objectives: [
      "先用自然语言解释 probability、likelihood、NLL、KL、reward、return、value、advantage、gradient 和 ODE。",
      "把一条抓杯样本翻译成 x、A、B、K、H、dₐ，并能读出每个张量的 shape。",
      "从‘提高专家动作的概率’逐步推到 NLL、MSE 和交叉熵，说明成立条件。",
      "用一条三步轨迹算 return、value、advantage，再理解 policy gradient 与 PPO clipping。",
      "用匀速运动理解导数、速度场、Euler 积分，并区分本课程中的 diffusion 与 flow 练习。",
    ],
    timePlan: [
      { duration: "0:00–0:40", title: "先看一条完整样本", activity: "把图像、关节角、语言和未来动作写成带名字的表，不碰公式。", deliverable: "一张输入—输出表。" },
      { duration: "0:40–1:40", title: "概率、似然、NLL 与 MSE", activity: "从‘模型给专家动作多少分’开始，逐步解释负号、log 和高斯假设。", deliverable: "一个逐行数值例。" },
      { duration: "1:40–2:30", title: "潜变量与 KL", activity: "用两条不同抓取路径解释 z、posterior、prior 和 KL。", deliverable: "一维高斯 KL 手算。" },
      { duration: "2:30–3:50", title: "从 reward 到 PPO", activity: "先算三步 return 和 advantage，再解释策略概率为什么要乘 advantage。", deliverable: "一张三步轨迹表。" },
      { duration: "3:50–5:00", title: "从速度到 ODE", activity: "用 Euler 法走四步，再运行完整脚本并故意反转时间方向。", deliverable: "手算、PASS 输出和失败记录。" },
    ],
    theory: [
      "先看任务：机器人收到 4 帧 RGB、当前关节角和‘拿起红杯’，输出未来 3 步末端增量。把所有已知条件合称 x，把要预测的动作块称为 A。若每步动作是 [Δx,Δz]，单条样本的 A shape 就是 [H=3,dₐ=2]；一次训练放 8 条样本时，batch shape 是 [B=8,H=3,dₐ=2]。",
      "BC 的问题可以先用一句话描述：给定 x，模型应该给专家动作 A 较高的条件概率密度 pθ(A|x)。likelihood 是固定数据后，把同一个表达式看成参数 θ 的得分。训练通常最小化 −log pθ(A|x)，这就是 negative log-likelihood，简称 NLL。",
      "MSE 与 NLL 不是两个互不相关的公式。若先假设动作围绕模型均值服从固定方差高斯分布，展开高斯 NLL 后，与均值有关的部分正比于平方误差。固定方差时两者最优点相同，但数值不相等；方差可学习、动作多峰或各维单位差异很大时，简单 MSE 的假设就需要重新检查。",
      "CVAE 用潜变量 z 表示同一观测下可能出现的不同动作方式，例如从杯子左侧或右侧接近。训练时 encoder 看 x 和真实 A，形成 posterior qφ(z|x,A)；推理时真实未来动作不存在，只能使用 prior p(z|x)。KL 衡量这两个分布有多不一致，使训练时得到的 z 不至于和推理时可用的 z 完全脱节。",
      "RL 处理的是动作如何影响后续结果。reward 是某一步收到的反馈；return 是从当前时刻起的折扣 reward 总和；value 是采取动作前对未来 return 的平均预测；Q 是指定当前动作后的平均预测；advantage=Q−V，表示这个动作比当前策略的平均水平好多少。",
      "Policy gradient 的直觉是：采样动作的 advantage 为正，就提高它的概率；为负，就降低它的概率。PPO 再比较新旧策略给同一动作的概率比，限制一次更新不要走得太远。这个 clip 约束训练更新，不负责机器人动作限幅或碰撞安全。",
      "ODE 描述一个量如何随连续时间变化：dx/dt=v(x,t)。已知当前位置和速度后，Euler 法用 xₖ₊₁=xₖ+Δt·v(xₖ,tₖ) 走一小步。Flow matching 学的是这个速度场；本课程的 diffusion Toy 则使用有限个离散噪声步。两者的共同点是从简单噪声逐步得到动作，时间方向必须写清。",
    ],
    deepDive: [
      { title: "1. 先把一条 VLA 样本说清楚", paragraphs: ["输入 x 不是一个神秘向量。对抓杯任务，它可以包含 RGB 历史 I₁:₄、编码器读数 q 和语言指令 ℓ。输出 A 是未来动作块，例如 [[+1cm,0],[+1cm,−0.5cm],[0,−0.5cm]]。训练数据中的一行就是 (x,A)：前者是已知条件，后者是教师答案。", "K 表示历史帧数，H 表示动作步数，dₐ 表示每步动作维度，B 表示一次送进模型的样本数。B=8、H=3、dₐ=2 时，动作张量是 [8,3,2]，总共含 48 个数；它们不一定具有相同单位。"], takeaways: ["先写名字和单位，再写字母。", "K 是观测历史长度，H 是动作预测长度。"] },
      { title: "2. 公式中的竖线、下标和期望分别是什么", paragraphs: ["p(A|x) 读作‘在已知 x 的条件下，A 的概率分布或密度’。竖线不是除法。θ 是模型参数，下标 θ 表示这个分布由模型决定；t 通常是机器人时间，k 也可能表示数值积分或噪声步骤，必须看章节约定。", "E[·] 表示对许多可能样本取平均。Σ 是显式求和，mean reduction 是程序实际怎么除分母。公式只写 E、代码却在错误的轴上 mean，是常见且会改变训练权重的 bug。"], takeaways: ["先把公式逐字读成一句中文。", "时间下标与张量轴不能凭字母猜。"] },
      { title: "3. Probability、likelihood、log 与 NLL", paragraphs: ["模型看到 x 后，可能给三个离散动作的概率 [0.8,0.15,0.05]。若专家选择第一个动作，这条数据的 likelihood 是 0.8；选择第三个则是 0.05。训练想让实际出现的专家动作获得更高分。连续动作使用概率密度，密度值本身不必小于 1，但 NLL 的优化逻辑相同。", "多条独立样本的 likelihood 相乘容易得到极小数，log 会把乘法变成加法。训练器习惯做最小化，所以再加一个负号：−log(0.8)≈0.223，−log(0.05)≈2.996。模型越不相信真实答案，损失越大。"], takeaways: ["likelihood 是模型给已观察数据的分数。", "log 方便求和，负号把最大化变成最小化。"] },
      { title: "4. 从高斯 NLL 走到 MSE", paragraphs: ["取真实动作 a=1.0、模型均值 μ=0.6、固定 σ=0.5。平方误差是 (1.0−0.6)²=0.16；高斯 NLL 中与误差有关的项是 0.16/(2×0.5²)=0.32，再加归一化常数约 0.2258，得到 0.5458。MSE 与 NLL 数值不同，但固定 σ 时都通过让 μ 靠近 1.0 来下降。", "若 x 对应 −1 和 +1 两种同样合理的动作，单均值 MSE 可能预测 0。0 的误差平均最小，却可能不是可执行模式。这正是后面引入 CVAE、diffusion 或 flow 的原因。"], takeaways: ["MSE 等价关系来自固定高斯假设。", "平均误差小不保证动作落在有效模式上。"] },
      { title: "5. 潜变量 z 与 KL 到底在做什么", paragraphs: ["把 z 想成没有直接标注的‘动作方式’旋钮：z 的不同区域可表示从左侧或右侧接近杯子。训练 encoder 因为看到了真实动作 A，能判断这次演示更像哪一种方式；推理时没有 A，只能从 prior 取 z。", "KL 写成 DKL(q||p)，这里比较训练 posterior q 与推理 prior p。例子 q=N(0.5,0.8²)、p=N(0,1) 的 KL≈0.1681。KL≥0，但通常不对称，因此不是普通几何距离；它也不衡量动作重建是否准确，重建误差由另一项负责。"], takeaways: ["重建项管动作像不像，KL 管训练和推理的 z 是否接得上。", "posterior 训练可见，真实未来动作推理不可见。"] },
      { title: "6. Reward、return、V、Q 与 advantage", paragraphs: ["假设三步抓取只有最后成功时 reward=1，所以 rewards=[0,0,1]。取 γ=0.9，从后往前算：G₂=1，G₁=0+0.9×1=0.9，G₀=0+0.9×0.9=0.81。前两步即时 reward 为 0，但它们仍对最后成功有贡献。", "若 value 估计为 [0.6,0.8,0.9]，单轨迹 advantage estimate 是 [0.21,0.10,0.10]。正式定义仍是 Aπ=Qπ−Vπ；Ĝ−V̂ 只是用一条采样轨迹构造的估计。正值表示动作结果好于当前基线，不等于任务已经成功。"], takeaways: ["reward 看一步，return 看后续总和。", "advantage 比较指定动作与当前策略平均水平。"] },
      { title: "7. Policy gradient 与 PPO clipping", paragraphs: ["随机策略 πθ(a|s) 给动作分配概率。Policy gradient 的核心项可读成 ∇logπθ(a|s)×Â：Â 为正时提高该动作的 log probability，Â 为负时降低。它不是直接把 reward 对神经网络求导，而是利用采样动作的 log probability 建立梯度估计。", "若旧策略给动作概率 0.25，新策略给 0.30，则比率 ρ=1.2。ε=0.1 时把它限制到 1.1；对 Â=0.5，未截断项是 0.60，截断项是 0.55，PPO surrogate 取较小的 0.55。这个例子只解释正 advantage；负 advantage 必须重新比较两项。"], takeaways: ["advantage 决定概率调整方向。", "PPO clip 限制更新，不是机器人安全层。"] },
      { title: "8. 导数、梯度、ODE 与 Euler", paragraphs: ["一维导数表示函数随输入变化多快；多参数 loss 对每个参数的偏导组成 gradient。数值差分用 [L(θ+h)−L(θ−h)]/(2h) 近似梯度，可用来检查手推或代码中的解析梯度，但它不是训练大模型的算法。", "ODE dx/dt=v 表示当前位置的变化率由速度 v 决定。若 x₀=0、恒定 v=2、Δt=0.25，Euler 四步依次得到 0.5、1.0、1.5、2.0。把 Δt 错写为负数，就会走向 −2.0；这就是生成模型中时间方向错误为何不是小问题。"], takeaways: ["gradient 告诉参数往哪改。", "Euler 用局部速度近似一小段连续运动。"] },
      { title: "9. Diffusion 与 flow 在本课程里怎样连接", paragraphs: ["两者都学习从简单噪声生成动作分布，但训练目标与求解器不同。本课程的 diffusion Toy 在 50 个离散噪声步上预测加入的噪声，再逐步反向采样；flow Toy 学连续速度 vθ(x,t,c)，再用 ODE solver 积分。", "不要从这张入门图推出‘所有 diffusion 都只能离散采样’或‘flow 天然更安全’。现代生成模型还有 probability-flow ODE、不同参数化和多种 solver；真机质量还取决于条件输入、数据、action contract、延迟与控制层。"], takeaways: ["共同目标不代表公式可以混用。", "生成质量与机器人安全是两类问题。"] },
      { title: "10. 已确认的结论与课程边界", paragraphs: ["【已确认】固定方差高斯 NLL 与加权平方误差只差与均值无关的项；categorical NLL 对 one-hot 标签就是交叉熵；KL、return、advantage estimator、PPO ratio 和 Euler 例子都能由本章脚本复算。", "【合理推测】先统一 shape、unit 和符号能减少实现错误，但本站 Toy 没有统计证明它会提高真实机器人成功率。", "【个人观点】先理解最小可计算例子，再按需要补严格概率论，比一开始堆完整理论更适合这条工程课程。", "【暂无法验证】你的数据噪声、多峰程度、value 质量和最佳 loss 权重仍需用目标数据与 rollout 测量。"], takeaways: ["公式正确不等于建模假设适合数据。", "Toy 验证算术，不验证真实策略效果。"] },
    ],
    formula: { latex: String.raw`\begin{aligned}\text{BC: }&\mathcal L_{\mathrm{NLL}}=-\log p_\theta(\mathbf A\mid x)\\\text{CVAE: }&\mathcal L=\mathcal L_{\mathrm{recon}}+\beta D_{\mathrm{KL}}(q_\phi(z\mid x,\mathbf A)\|p(z\mid x))\\\text{RL: }&A^\pi(s,a)=Q^\pi(s,a)-V^\pi(s),\qquad \hat A_t=\hat G_t-\hat V(s_t)\\\text{Flow: }&\frac{d\mathbf A}{d\tau}=v_\theta(\mathbf A,\tau,x)\end{aligned}`, symbols: [
      { symbol: "x", meaning: "决策时已知的条件，例如图像历史、关节状态和语言。" }, { symbol: "A", meaning: "需要预测的 H×dₐ 动作块；不是输入条件。" }, { symbol: "θ/φ", meaning: "模型中通过训练调整的参数。" }, { symbol: "z", meaning: "用于表示不同动作方式的潜变量。" }, { symbol: "β", meaning: "重建与 prior 匹配的权重；β=1 才对应标准负 ELBO。" }, { symbol: "A^π", meaning: "指定动作相对策略平均水平的真实 advantage。" }, { symbol: "Âₜ", meaning: "用采样 return 和 value 估计得到的数值。" }, { symbol: "vθ", meaning: "flow 模型学习的连续时间速度场。" },
    ], note: "这四行是一张章节索引，不要求一次背下。先按深挖 1–9 的顺序理解，再回来指出每一行的输入、输出和用途。同一个字母 A 在文献中可能表示动作或 advantage；代码中应写 action_chunk 与 advantage，避免混淆。" },
    practice: { title: "从一条抓杯样本走完五段手算", summary: "先把概念翻译成中文和具体数字，再运行标准库脚本核对 NLL、KL、advantage、PPO clipping 与 Euler。", steps: ["写下 x={4帧RGB,关节角,‘拿起红杯’}，A 为 3×2 的未来末端增量，并标出 K=4、H=3、dₐ=2。", "用真实动作 1.0、均值 0.6、σ=0.5，手算平方误差 0.16 和高斯 NLL 0.5458。", "用 q=N(0.5,0.8²)、p=N(0,1) 手算 KL≈0.1681，并分别说明重建项与 KL 管什么。", "对 rewards=[0,0,1]、γ=0.9、V̂=[0.6,0.8,0.9]，从后往前算 Ĝ 与 Â。", "手算 0.30/0.25=1.2，经 ε=0.1 截到 1.1，正优势 0.5 的 clipped surrogate 为 0.55。", "手算 x₀=0、v=2、Δt=0.25 的四步 Euler，再运行 python public/labs/vla_math_foundations.py。", "只在临时副本中反转 Euler dt，确认 endpoint 走向错误方向；恢复后保留 PASS 输出。"], acceptance: ["不用术语也能解释 likelihood、KL、advantage 和 ODE 各在解决什么问题。", "所有手算与脚本一致。", "能说明 A^π=Q^π−V^π 与 Â=Ĝ−V̂ 的区别。", "能解释 PPO clip 约束训练更新，但不构成机器人安全约束。", "能从 action_chunk 的 shape 读出 batch、horizon 与动作维度。"], status: "已验证", code: "python public/labs/vla_math_foundations.py", expected: ["打印 NLL/MSE、KL、return/advantage estimates、PPO ratio=1.20→1.10、surrogate=0.55 与 Euler endpoint，最后 MATH CHECKS PASS。"], debugging: ["若概念说不清，先回到抓杯样本，不要继续背符号。", "数值不一致先检查 log 是自然对数以及 mean/sum reduction。", "advantage estimate 不一致先检查 γ 和从后往前递推的顺序。", "PPO 数值不一致先分清旧策略在分母、clip 区间以及 surrogate 的 min。"] },
    pitfalls: ["第一遍就背整张公式", "把概率、密度和 likelihood 混成同一个口号", "把 MSE 当成没有分布假设的真理", "混淆动作 A 与 advantage Aₜ", "忽略 batch/time/action reduction 和单位", "把训练时间与生成时间方向混用", "认为 PPO clip 等于机器人安全约束"],
    review: ["p(A|x) 中竖线怎样读？x 和 A 分别是什么？", "为什么训练使用 NLL，而不是直接最大化许多小概率的乘积？", "MSE 与高斯 NLL 在什么条件下有相同最优均值？", "CVAE 的 posterior 为什么训练可用、推理不可直接使用？", "reward、return、V、Q 与 advantage 分别回答什么问题？", "正 advantage 对动作概率意味着什么？", "PPO clip 与机器人动作 clip 有什么区别？", "Euler 更新式中的 Δt 符号为什么重要？"],
    completion: "能从一条抓杯样本解释九个核心概念，完成五段数值例，并在后续章节公式中标出每个张量的 shape、unit、已知条件和预测目标。",
    sources: [{ title: "Auto-Encoding Variational Bayes", url: "https://arxiv.org/abs/1312.6114", role: "ELBO 与重参数化" }, { title: "Deep Conditional Generative Models", url: "https://proceedings.neurips.cc/paper/2015/hash/8d55a249e6baa5c06772297520da2051-Abstract.html", role: "CVAE" }, { title: "Reinforcement Learning: An Introduction", url: "http://incompleteideas.net/book/the-book-2nd.html", role: "return、value、advantage 与 policy gradient" }, { title: "ACT", url: "https://arxiv.org/abs/2304.13705", role: "CVAE 动作块应用" }, { title: "Diffusion Policy", url: "https://diffusion-policy.cs.columbia.edu/", role: "动作 diffusion" }, { title: "Flow Matching", url: "https://arxiv.org/abs/2210.02747", role: "连续流目标" }, { title: "PPO", url: "https://arxiv.org/abs/1707.06347", role: "策略更新" }],
    visual: "math",
  },

  "act-cvae": {
    lead: "BC 每次只预测下一步时，策略容易频繁抖动，也很难表达一段连贯动作。ACT 改为一次预测未来动作块，并用潜变量表示同一观测下的不同动作方式。本章先用‘单步预测和三步预测有什么区别’解释问题，再进入 CVAE、mask 和 temporal ensemble。课程案例额外加入语言；原始 ACT 不接收语言。",
    objectives: ["在贯穿案例上画出 ACT 训练与推理的两条数据流。", "从条件似然逐步推出 ELBO，并手算 diagonal Gaussian KL。", "写出带 time/action mask 的 H×dₐ reconstruction loss。", "区分 chunk horizon、execution horizon 与 temporal ensemble。", "让 ACT 与后续 VLA 复用同一 action contract、评测器和安全层。"],
    timePlan: [
      { duration: "0:00–0:50", title: "拆训练/推理图", activity: "标出 style encoder 只在训练看到 action。", deliverable: "双色信息流图。" },
      { duration: "0:50–1:50", title: "手推 CVAE", activity: "手算重参数化与一维 KL。", deliverable: "ELBO 数值表。" },
      { duration: "1:50–2:40", title: "动作块与 mask", activity: "构造不足 H 的序列并检查 padding。", deliverable: "H×dₐ 张量图。" },
      { duration: "2:40–3:40", title: "Temporal ensemble", activity: "融合三个重叠预测并制造时间戳错位。", deliverable: "逐时刻融合表。" },
      { duration: "3:40–5:00", title: "迁移到统一接口", activity: "让 ACT 与 π₀.₅ 输出同一物理 action contract。", deliverable: "可交换的 PolicyResponse 示例。" },
    ],
    theory: [
      "先不谈网络结构。普通单步 BC 在时刻 t 输出 aₜ，下一时刻重新预测；ACT 在时刻 t 输出 Aₜ=[aₜ,aₜ₊₁,…,aₜ₊H₋₁]。动作块让模型学习短时间内的轨迹形状，也减少每一步都重新查询大模型的压力，但 H 步并不意味着必须全部开环执行。",
      "沿用全课程案例，一条训练样本包含最近 K=2 帧双相机图像、当前机器人状态 qₜ、语言指令 ℓ，以及未来动作块 Aₜ∈R^{16×7}。这是本站为统一 BC/VLA 接口定义的 language-conditioned ACT-style 变体；原始 ACT 使用图像与当前关节状态，不含语言输入，且其 chunk horizon、观测历史和动作维度应以原论文/固定代码配置为准。",
      "课程变体的训练目标不是单步 (oₜ,aₜ)，而是条件动作块分布 pθ(Aₜ|xₜ)。CVAE encoder 在训练时读取当前状态与真实动作块，产生 qφ(z|x,A)；decoder/Transformer 读取图像、状态、课程新增的语言条件与 z 预测整个动作块。潜变量 z 用来承载同一条件下无法由 x 唯一确定的动作风格或轨迹模式。",
      "推理时没有未来真实动作，因此训练期的 style encoder 被移除。ACT 论文的常用做法把 z 设为零；这意味着训练必须让 decoder 在该推理约定下可用。不能在部署时误把上一段预测当作 ground-truth action 喂入 encoder。",
      "动作块越过 episode 结尾时必须 padding，但 padding 不是专家的静止动作。time mask 应广播到 7 个动作维，再结合每维尺度或权重计算 reconstruction loss；归一化统计仍然只来自 BC 章冻结的 train split。",
      "Temporal ensemble 与 receding horizon 不同：前者把不同时刻预测、但指向同一执行时刻的动作做加权融合，减小预测跳变；后者决定每次只执行动作块前缀后再观测。二者都依赖绝对执行时刻或严格索引，延迟时不能只按数组位置拼接。",
      "ACT 适合作为窄策略基线：它和后续 VLA 接收相同 PolicyRequest、输出相同 H×7 物理合同，并经过相同 TTL、限幅和评测器。ACT 成功只给出‘这批数据和接口可以学出窄策略’的正证据；如果 VLA 失败，仍需继续区分模型、适配和训练配置。",
    ],
    deepDive: [
      { title: "1. ACT 的三个部件分别解决什么", paragraphs: ["Action chunking：一次预测 H 步，让模型学习一小段轨迹，而不是孤立动作。CVAE：用潜变量 z 表示同一观测下不同但合理的动作方式。Temporal ensemble：连续多次查询会对同一执行时刻给出多个预测，把时间对齐后的候选融合，减少动作跳变。", "三者不能互相替代。Chunk 解决输出时间范围，CVAE 解决条件动作分布，temporal ensemble 处理多次查询的重叠预测。部署时还需要 receding horizon、TTL、限幅和低层控制。"], takeaways: ["先按问题区分三个部件。", "ACT 仍只是策略，不是完整控制与安全系统。"] },
      { title: "2. 训练看得到、推理看不到的信息", paragraphs: ["训练：A_true→style encoder→(μ,logσ²)→z；image/q/z→decoder→Â。推理：没有 A_true，style encoder 被丢弃，z 按实现约定取零或先验样本。", "如果把训练路径原样复制到推理，会产生无法获得的未来信息；如果训练时不检查 z=0 路径，重建很好也可能部署失败。"], takeaways: ["未来动作只属于训练后验。", "推理 z 约定必须与 checkpoint 配套。"] },
      { title: "3. Chunk 与 temporal ensemble 的时间语义", paragraphs: ["t=10 的模型预测执行时刻 10…19；t=11 又预测 11…20。执行时刻 12 同时有来自 query 10 的第 2 项、query 11 的第 1 项、query 12 的第 0 项。temporal ensemble 对这些候选按预测年龄加权。", "若模型查询晚到 150ms，数组第 0 项可能已经属于过去；必须先按 observation_time 与 action_dt 对齐，再参与融合。"], takeaways: ["融合对象是同一物理执行时刻。", "先做时间对齐，再做权重。"] },
      { title: "4. 证据边界", paragraphs: ["【已确认】ACT 原论文使用 CVAE 动作块与 temporal ensembling，但没有语言输入；本站 K=2、H=16、dₐ=7 的 language-conditioned ACT-style 变体不是原论文复现。本站脚本只核对 KL、重参数化和融合算术。", "【合理推测】ACT-style baseline 与 VLA 共用接口有助于定位 adapter/执行器错误。", "【个人观点】在 π₀.₅ 前完整做一次窄动作块基线，比直接把 ACT 写成 baseline 名称更适合自学。", "【暂无法验证】你的双臂移动任务所需 H、KL 权重和 ensemble 衰减必须实测。"], takeaways: ["Toy 和课程变体都不是原始 ACT 复现。", "真实超参数不能从教程抄答案。"] },
    ],
    derivations: [
      {
        title: "从条件似然到 CVAE 的 ELBO",
        question: "真实动作模式 z 没有标签，为什么仍然可以训练 pθ(A|x,z)？",
        steps: [
          { label: "从真正想最大化的条件似然开始", latex: String.raw`\log p_\theta(\mathbf A\mid\mathbf x)=\log\int p_\theta(\mathbf A\mid\mathbf x,\mathbf z)\,p(\mathbf z)\,d\mathbf z`, explanation: "x 是图像、语言与本体状态，A 是 16×7 动作块。ACT 的实现采用标准正态先验 p(z)=N(0,I)；积分表示所有潜在动作风格都可能生成这段动作，但直接计算通常不可行。" },
          { label: "乘除同一个近似后验", latex: String.raw`\log p_\theta(\mathbf A\mid\mathbf x)=\log\mathbb E_{q_\phi(\mathbf z\mid\mathbf x,\mathbf A)}\!\left[\frac{p_\theta(\mathbf A\mid\mathbf x,\mathbf z)p(\mathbf z)}{q_\phi(\mathbf z\mid\mathbf x,\mathbf A)}\right]`, explanation: "训练时真实 A 已知，因此 encoder 可以构造 qφ(z|x,A)，把难算的积分改写成可采样的期望。这个后验只属于训练路径。" },
          { label: "用 Jensen 不等式得到可优化下界", latex: String.raw`\log p_\theta(\mathbf A\mid\mathbf x)\ge\mathbb E_q[\log p_\theta(\mathbf A\mid\mathbf x,\mathbf z)]-D_{\mathrm{KL}}\!\left(q_\phi(\mathbf z\mid\mathbf x,\mathbf A)\,\|\,p(\mathbf z)\right)`, explanation: "第一项要求 decoder 重建动作块，第二项要求训练后验不要远离推理时使用的标准正态先验。最小化负下界得到 reconstruction + KL。" },
          { label: "写成实现中的 β 加权损失", latex: String.raw`\mathcal L_{\mathrm{ACT}}=\mathcal L_{\mathrm{rec}}+\beta\,D_{\mathrm{KL}}(q_\phi\|p)`, explanation: "β=1 对应标准 ELBO；β≠1 是训练权衡，不能再把它无条件称为原始对数似然下界。β 太大可能忽略 z，太小会扩大训练后验与推理先验的差距。" },
        ],
        workedExample: {
          title: "手算二维 diagonal Gaussian KL",
          setup: "令 q=N(μ,diag(σ²))、p=N(0,I)，μ=(0.4,−0.2)，log σ²=(log 0.25,0)。",
          steps: ["使用 KL=½Σⱼ(μⱼ²+σⱼ²−logσⱼ²−1)。", "第 1 维贡献 ½(0.16+0.25−log0.25−1)≈0.3981。", "第 2 维贡献 ½(0.04+1−0−1)=0.0200。"],
          result: "KL≈0.4181，非负；μ=0、logσ²=0 时恰为 0。",
        },
        implementation: "encoder 输出 mu 与 logvar；采样写成 z=mu+exp(0.5*logvar)*eps。不要把 logvar 直接当 σ，也不要在推理时调用需要真实 A 的后验 encoder。",
      },
      {
        title: "带 padding mask 的动作块 L1 重建损失",
        question: "episode 只剩几步时，怎样保证补齐到 H=16 的数值不被模型当成专家动作？",
        steps: [
          { label: "先保留时间轴和动作轴", latex: String.raw`\mathbf A,\hat{\mathbf A}\in\mathbb R^{B\times H\times d_a},\qquad \mathbf m\in\{0,1\}^{B\times H}`, explanation: "在贯穿案例中 H=16、dₐ=7。mask 只描述某个未来时刻是否真实存在，再广播到动作维；不能把 112 个数展平后丢失时间语义。" },
          { label: "只在有效元素上聚合", latex: String.raw`\mathcal L_{\mathrm{rec}}^{\mathrm{valid}}=\frac{\sum_{b,h,j}m_{b,h}w_j\left|A_{b,h,j}-\hat A_{b,h,j}\right|}{\sum_{b,h,j}m_{b,h}w_j}`, explanation: "ACT 官方代码使用 masked L1；固定 revision 中是先把 padding 误差乘零，再对完整张量 mean。本课程把分母也限制到有效元素，作为跨可变长度 batch 保持 loss 尺度的工程建议，不冒充官方代码逐字复现。" },
          { label: "检查 padding invariance", latex: String.raw`\mathcal L_{\mathrm{rec}}(\mathbf A_{\mathrm{pad}}=0)=\mathcal L_{\mathrm{rec}}(\mathbf A_{\mathrm{pad}}=10^6)\quad\text{if }m_{\mathrm{pad}}=0`, explanation: "只改变无效 padding 数值时，masked loss 应完全不变。这是比肉眼检查 shape 更可靠的单元测试。" },
        ],
        workedExample: {
          title: "三步有效动作加一个错误 padding",
          setup: "取 dₐ=1、H=4，有效位置误差为 [0.1,−0.2,0]，最后一个 padding 误差故意设为 10，mask=[1,1,1,0]。",
          steps: ["有效绝对误差之和为 0.1+0.2+0=0.3。", "按有效元素归一化的 L1=0.3/3=0.1；官方代码风格的完整张量 mean 为 0.3/4=0.075。", "若忘记 mask，L1=(0.3+10)/4=2.575。"],
          result: "mask 决定 padding 是否贡献误差，reduction convention 决定不同有效长度样本的 loss 尺度；两者必须分别记录。",
        },
        implementation: "数据集同时返回 actions:[B,16,7] 与 action_valid:[B,16]；训练第一批次断言广播后的 mask shape，加入随机修改 padding 后 loss 不变的测试，并明确记录是 full-tensor mean 还是 valid-only mean。",
      },
      {
        title: "按物理执行时刻做 Temporal Ensemble",
        question: "为什么三个数组中的不同下标可能对应同一个应该执行的动作？",
        steps: [
          { label: "先把数组下标还原成执行时刻", latex: String.raw`\tau=t+h\Delta t_a,\qquad \hat{\mathbf a}_{t\rightarrow\tau}=\hat{\mathbf A}_{t}[h]`, explanation: "query t 的第 h 项属于物理时刻 τ，而不是永远从抵达客户端后的“现在”开始。晚到 chunk 必须先跳过属于过去的前缀。" },
          { label: "收集所有指向同一 τ 的候选", latex: String.raw`\mathcal C_\tau=\{\hat{\mathbf a}_{t\rightarrow\tau}\mid t\le\tau<t+H\Delta t_a\}`, explanation: "t=10、11、12 发出的三个 chunk，都可能包含执行时刻 12 的预测。融合发生在 Cτ 内，不能对同一数组的相邻元素做普通低通。" },
          { label: "先复现 ACT 官方代码的候选顺序", latex: String.raw`w_i^{\mathrm{official}}=e^{-ki},\qquad i=0\ \text{表示候选数组中最旧的 query}`, explanation: "ACT 官方仓库固定 revision 742c753 中，候选按 query_time 从旧到新排列，再对 arange(N) 做指数衰减，因此旧预测权重更高。权重含义依赖数组顺序，不能只抄 exp(−ki)。" },
          { label: "再把年龄衰减写成另一种显式变体", latex: String.raw`\bar{\mathbf a}_\tau^{\mathrm{age}}=\frac{\sum_t e^{-k(\tau-t)}\hat{\mathbf a}_{t\rightarrow\tau}}{\sum_t e^{-k(\tau-t)}}`, explanation: "本站 Toy 还计算“旧预测随年龄衰减”的对照变体。它不是官方代码同义改写；两者都必须声明候选顺序，并用固定输入输出测试锁定。" },
        ],
        workedExample: {
          title: "三个 query 对执行时刻 12 的预测",
          setup: "query 10、11、12 分别预测 0.20、0.26、0.35，取 k=1，年龄为 2、1、0。",
          steps: ["官方顺序权重为 1、e⁻¹、e⁻²，融合结果约 0.2282。", "年龄衰减变体权重为 e⁻²、e⁻¹、1，融合结果约 0.3145。", "两者候选完全相同，差异只来自明确声明的权重方向。"],
          result: "先复现固定 revision 的 0.2282，再把 0.3145 作为对照；若 query_time 错移一格，候选集合本身也会改变。",
        },
        implementation: "每个候选保留 observation_time、query_time、offset 与 execute_time。下一章的 action-chunking 会继续加入 TTL、异步队列和只执行前 E 步的规则。",
      },
    ],
    formula: { latex: String.raw`z=\mu_\phi+\sigma_\phi\odot\epsilon,\ \epsilon\sim\mathcal N(0,I),\qquad \bar a_\tau=\frac{\sum_i w_i\hat a_{i\rightarrow\tau}}{\sum_iw_i}`, symbols: [
      { symbol: "μ,σ", meaning: "训练期 style encoder 的后验参数。" }, { symbol: "ε", meaning: "重参数化噪声。" }, { symbol: "τ", meaning: "真实执行时刻。" }, { symbol: "âᵢ→τ", meaning: "候选数组第 i 项对执行时刻 τ 的预测。" }, { symbol: "wᵢ", meaning: "显式声明候选顺序后定义的融合权重；不同 convention 不可混写。" },
    ], note: "已核对 ACT 官方仓库 742c753：推理 z=0；reconstruction 使用 masked L1 后对完整张量 mean；temporal aggregation 对从旧到新排列的候选使用 exp(−k·arange)。本站另给 valid-only reduction 与年龄衰减作为显式工程对照，不能把二者写成官方原实现。" },
    practice: { title: "CVAE、mask 与重叠预测算术", summary: "运行脚本，先核对 KL 和两种明确命名的融合 convention，再改错时间索引。", steps: ["运行 python public/labs/act_cvae_mechanics.py。", "复算 KL。", "画出三条重叠 chunk，并分别核对 official-order 与 age-decay 输出。", "比较 valid-only/full-tensor L1 reduction。", "将 query_time 偏移一格并观察融合错误。"], acceptance: ["能解释训练/推理差异。", "两种融合值都与手算一致且不会混称官方实现。", "能说明 mask 与 reduction 是两个独立选择。", "能定位时间错位来源。"], status: "已验证", code: "python public/labs/act_cvae_mechanics.py", expected: ["输出 KL、三个同执行时刻候选、两套加权动作和两种 masked L1，最后 ACT MECHANICS PASS。"], debugging: ["KL 为负通常是公式符号错。", "融合候选数错先核对 query_time+offset。", "新旧权重方向相反时先核候选排列，不要先改指数符号。"] },
    pitfalls: ["推理时调用训练后验 encoder", "padding 动作参与 loss", "把 temporal ensemble 当简单平滑", "晚到 chunk 从索引 0 重放", "ACT/VLA 使用不同物理动作接口"],
    review: ["ACT 的 style encoder 为什么推理时不能使用？", "temporal ensemble 融合的是哪些动作？", "ACT 成功能证明什么、不能证明什么？"],
    completion: "独立画出训练/推理数据流，运行并改坏一次 temporal ensemble Toy，再用同一个 PolicyResponse schema 包装 ACT 与 VLA 输出。",
    sources: [{ title: "ACT paper", url: "https://arxiv.org/abs/2304.13705", role: "原论文" }, { title: "ACT official code · 742c753", url: "https://github.com/tonyzhaozh/act/tree/742c753c0d4a5d87076c8f69e5628c79a8cc5488", role: "固定实现参照" }, { title: "Auto-Encoding Variational Bayes", url: "https://arxiv.org/abs/1312.6114", role: "ELBO 与重参数化" }, { title: "Deep Conditional Generative Models", url: "https://proceedings.neurips.cc/paper/2015/hash/8d55a249e6baa5c06772297520da2051-Abstract.html", role: "CVAE" }],
    visual: "act",
  },

  "post-training": {
    lead: "模型完成第一次训练后，仍可能在偏离演示的状态失败。‘后训练’就是利用新增演示、人工纠错、失败结果或在线交互继续改进策略。它不是 RL 的同义词：很多机器人项目应先做 correction SFT 或 DAgger，只有奖励可靠且探索风险可控时才考虑 offline/online RL。",
    objectives: ["区分 pretraining、SFT、correction SFT、offline RL 与 online RL。", "用决策门判断何时不该上 RL。", "构造不污染测试集的失败—纠错—再训练闭环。", "手算 group-relative advantage 与 clip。", "设计 human takeover、reward 与 safety 三条独立通道。"],
    timePlan: [
      { duration: "0:00–1:00", title: "画后训练阶梯", activity: "按数据来源、是否在线、是否需要 reward 分类。", deliverable: "五层方法选择图。" },
      { duration: "1:00–2:00", title: "先修数据闭环", activity: "冻结 test，定义 intervention/recovery schema。", deliverable: "数据治理表。" },
      { duration: "2:00–3:15", title: "DAgger/HIL", activity: "设计接管与恢复采集，不把人工动作误记为策略动作。", deliverable: "一条完整 episode 日志。" },
      { duration: "3:15–4:30", title: "Reward model 与 offline RL", activity: "定义 outcome/progress/preference 信号及误判审计。", deliverable: "reward card。" },
      { duration: "4:30–5:45", title: "Group RL 手算", activity: "运行成功/失败 group rollout Toy，观察零方差组。", deliverable: "advantage 表。" },
      { duration: "5:45–7:00", title: "安全与回归", activity: "建立 canary、冻结回归集与 go/no-go。", deliverable: "后训练实验卡。" },
    ],
    theory: [
      "先按数据来源区分方法。SFT/BC 学‘专家在这个状态会做什么’；correction SFT 专门加入失败状态上的纠正动作；DAgger 让当前策略先访问自己的状态，再请专家给标签；offline RL 从固定日志中的 reward 学习；online RL 让策略继续与环境交互并收集新反馈。方法越往后，越依赖 reward、分布外估值和现场安全条件。",
      "继续 SFT 使用新的专家、纠错或恢复轨迹，优化目标仍是模仿。DAgger 类方法让当前策略访问自己的状态分布，再由专家标注/接管；它针对 covariate shift，但采集本身可能带风险。HIL 必须记录 policy_action、human_action、executed_action 和 takeover 原因，不能把三者混成一个 action。",
      "奖励可以是终局成功、阶段进度、偏好或人工评分。奖励模型不是事实传感器：遮挡、视觉捷径和 reset 泄漏都可能让 reward 高而任务失败。先用独立标注集报告 precision/recall、按场景分层，并保留人工审计。",
      "Offline RL 只用固定数据，避免在线探索，但会受分布外 action 估值误差影响；online RL 能收集当前策略反馈，却引入硬件磨损、危险探索和非平稳系统。真实机器人上通常应先缩短任务、限制动作、设置接管并从有非零成功率的 SFT policy 起步。",
      "π*0.6 官方报告描述了 offline RL 预训练、任务 SFT 与机器人经验后训练的三阶段，并使用 value/advantage 条件；这证明官方方法链存在，不等于 π0.6 已提供与 openpi π0.5 同等完整的公开权重、配置和部署代码。",
    ],
    deepDive: [
      { title: "1. 五种方法的最小区别", paragraphs: ["普通 SFT：收集更多专家成功演示并继续模仿。Correction SFT：专门记录策略失败状态以及专家如何救回来。DAgger/HIL：运行当前策略，专家在它真正访问的状态上标注或接管。Offline RL：不再采新交互，只用固定数据中的 reward/return 更新。Online RL：更新中的策略继续产生新数据。", "选择顺序不由方法新旧决定。若失败主要来自 frame、单位或时序 bug，五种方法都不该先上；若专家能稳定纠错但 reward 很难自动判断，correction SFT 往往比 RL 更直接。"], takeaways: ["先看数据怎样产生，再看算法名称。", "后训练不能修复未排除的执行协议错误。"] },
      { title: "2. 先问四个问题，再选算法", paragraphs: ["基础策略在冻结评测上是否有非零成功？若始终 0%，reward 只告诉失败，group-relative 更新常无方向；先补演示、缩短任务或课程化。", "失败可否由专家纠正？reward 是否可机器可靠判定？能否在仿真或安全沙箱探索？有没有严格冻结的回归集？四问决定优先 correction SFT、reward-weighted BC、offline RL 还是 online RL。"], takeaways: ["RL 不是修 pipeline bug 的工具。", "0% base policy 往往先补能力与数据。"] },
      { title: "3. 数据不能因为参与后训练就改写历史", paragraphs: ["episode 记录 original_policy_revision、observations、policy_action、executed_action、intervention、reward_source 和 termination。人工接管后的轨迹可以进入 correction train split，但原始冻结 test episode 和成功判据不能回流训练。", "每轮后训练都生成 dataset revision、checkpoint revision、reward model revision 与来源清单。否则提升可能只是测试泄漏或 evaluator 改动。"], takeaways: ["执行动作不一定等于策略动作。", "冻结测试集和 evaluator revision。"] },
      { title: "4. Group-relative 更新的可用边界", paragraphs: ["同一任务采样 K 个 rollout，得到 R₁:K，以组均值/标准差构造相对 advantage。它降低了对单独 value model 的依赖，但 K 个奖励都相同时分母需稳定化且学习信号接近零。", "对连续动作 VLA，还要定义可训练的 log-probability 或一致 surrogate；不同论文的实现不能仅凭都叫 GRPO 就互换。"], takeaways: ["组内多样性决定信号。", "连续生成头需单独推导训练比率。"] },
      { title: "5. 证据边界", paragraphs: ["【已确认】LeRobot 文档公开 DAgger/HG-DAgger/HIL-SERL 路线；TorchRL 教程演示 CPU 合成 VLA 的一次 GRPO 风格更新；π*0.6 官方报告三阶段训练。", "【合理推测】你的移动双臂应优先 correction SFT，再考虑 RL，因为全身探索代价更高。", "【个人观点】后训练应按风险从低到高逐级开门，而不是以论文新旧排序。", "【暂无法验证】你的 reward 可观测性、base policy 成功率与安全审批尚未知，因此不能预先指定 RL 算法或承诺提升。"], takeaways: ["方法选择依赖现场证据。", "官方结果不是本站复现。"] },
    ],
    formula: { latex: String.raw`\hat A_i=\frac{R_i-\bar R}{s_R+\epsilon},\qquad L(\theta)=-\mathbb E\left[\min(\rho_i\hat A_i,\operatorname{clip}(\rho_i,1-\varepsilon,1+\varepsilon)\hat A_i)\right]`, symbols: [
      { symbol: "Rᵢ", meaning: "同任务第 i 个 rollout 的回报。" }, { symbol: "Āᵢ", meaning: "组内标准化相对 advantage。" }, { symbol: "ρᵢ", meaning: "新旧策略对已采样动作的概率比。" }, { symbol: "ε", meaning: "数值稳定项；与 clip 宽度 ε 不应在代码中同名。" },
    ], note: "此式展示 group-relative + clipped update 的骨架，不声明可直接用于任意 flow/diffusion action head。实现必须核对论文的概率或 surrogate 定义。" },
    practice: { title: "后训练决策与 group rollout Toy", summary: "先用决策表拒绝不满足条件的 RL，再运行二元奖励 group Toy。", steps: ["写 base success、reward audit、safe rollout、frozen test 四项证据。", "运行 python public/labs/post_training_group_rl.py。", "把奖励全部改成 0，观察 advantage 消失。", "写出 correction SFT→可选 RL 的 go/no-go。"], acceptance: ["能解释为什么 0% 策略不应盲目上 group RL。", "测试集从未进入训练。", "reward 与 safety 独立。"], status: "已验证", code: "python public/labs/post_training_group_rl.py", expected: ["混合成功组产生正负 advantage；全失败组产生零信号；最后 POST-TRAINING TOY PASS。"], debugging: ["NaN 先检查 group std=0。", "离线提升而回归失败先查测试泄漏/evaluator revision。"] },
    pitfalls: ["把后训练等同于 RL", "基础策略 0% 仍只给稀疏终局奖励", "reward model 与 policy 看同一视觉捷径", "人工动作覆盖策略动作日志", "在线探索绕过独立安全层", "新数据污染冻结测试集"],
    review: ["什么时候 correction SFT 比 RL 更合理？", "为什么 reward model 不是安全系统？", "全失败 group 的更新信号怎样？"],
    completion: "提交一张方法决策表、一份版本化 intervention episode、一个 reward card 和一份通过冻结回归集的实验报告；没有现场数据时明确标为未验证。",
    sources: [{ title: "TorchRL VLA tutorial", url: "https://docs.pytorch.org/rl/main/tutorials/vla.html", role: "CPU 合成 BC/GRPO 教学" }, { title: "LeRobot HIL data collection", url: "https://huggingface.co/docs/lerobot/main/hil_data_collection", role: "DAgger/HG-DAgger" }, { title: "LeRobot HIL-SERL", url: "https://huggingface.co/docs/lerobot/main/hilserl", role: "真实机器人 RL 工作流" }, { title: "π*0.6 / RECAP", url: "https://www.pi.website/blog/pistar06", role: "官方三阶段报告" }, { title: "RIPT-VLA", url: "https://arxiv.org/abs/2505.17016", role: "VLA RL 研究" }],
    visual: "post-training",
  },

  "mobile-dual-arm-pi-deployment": {
    lead: "双臂、2-DOF 腰部、移动底盘和 Thor 共同构成一个异构全身系统。直接修改 openpi 示例动作向量的长度无法解决 frame、单位、mode、padding 和安全边界。下面 22 步给出最小工程主线；采集、训练和安全审批的实际耗时仍取决于现场条件。",
    objectives: [
      "在第 1 步识别 Thor 型号、内存、JetPack/L4T、CUDA/TensorRT、功耗模式与热状态。",
      "为双臂、夹爪、2-DOF 腰部和底盘建立命名、单位、frame、频率、mask 与限幅完整的 whole-body contract。",
      "实现 openpi 自定义 Inputs/Outputs/DataConfig、padding/slicing 与全新 norm stats。",
      "在 Thor 原生、TensorRT 和远端策略服务三条路径间用实测门禁选择，而不是凭峰值算力。",
      "按 shadow→空载→单子系统→组合→任务灰度顺序部署，并记录每次过滤、接管和停止。",
      "先用纠错 SFT/DAgger 闭环，再在有可靠 reward 与安全沙箱时评估 RL 后训练。",
    ],
    timePlan: [
      { duration: "阶段 A · 3–5h", title: "可行性与系统盘点（1–2）", activity: "冻结任务、π0.5/π0.6 公开性门禁和 Thor 软硬件清单。", deliverable: "feasibility.md + thor_inventory.txt。" },
      { duration: "阶段 B · 6–10h", title: "全身契约（3–7）", activity: "frame/time/state/action/rate/safety 逐项定稿。", deliverable: "whole_body_contract.yaml + TF 图。" },
      { duration: "阶段 C · 8–20h + 采集", title: "遥操与数据（8–11）", activity: "同步记录、episode split、回放和审计。", deliverable: "dataset revision + replay 报告。" },
      { duration: "阶段 D · 6–12h", title: "openpi/Thor 集成（12–15）", activity: "固定 revision、三路径 smoke、adapter、norm 与一批过拟合。", deliverable: "可重载 checkpoint + parity/perf 报告。" },
      { duration: "阶段 E · 5–10h + 训练", title: "训练与离线评估（16–18）", activity: "ACT 基线、π0.5 微调和固定协议消融。", deliverable: "对比实验卡。" },
      { duration: "阶段 F · 8–20h + 审批", title: "真机灰度与闭环（19–22）", activity: "服务时序、shadow、分级执行、纠错/后训练。", deliverable: "go/no-go 日志 + regression 报告。" },
    ],
    theory: [
      "先质疑一个常见前提：有 Thor 不等于 π₀.₅ 一定能在本机按目标频率运行。模型框架、ARM64 依赖、JetPack/CUDA 版本、相机预处理、内存峰值、功耗/散热和精度转换都会决定端到端延迟。峰值 TOPS 不能替代同一请求边界的 p50/p95/p99 和动作质量回归。",
      "截至 2026-08-09，openpi 主线公开列出的可下载/可微调路径是 π₀、π₀-FAST 与 π₀.₅，并提供 JAX 和部分 PyTorch 路径；本站未在官方主线确认与 π₀.₅ 同等完整的 π0.6 checkpoint/config/deploy 路线。因此工程主线固定为 π₀.₅，π0.6 只设开放性检查点：只有在你拥有合法权重、代码、输入输出定义和可复现实验后才能替换。",
      "openpi 的公开动作统计包含 Mobile ALOHA、dual UR5e、ARX mobile 等本体，并给出某些默认 16 维映射；但你的 2-DOF 腰部不是这些默认契约的一部分，底盘也未确认是差速、全向还是速度/位移接口。直接复用其切片或 norm stats 是未证实且高风险的。固定 revision 15a9616 中，π₀.₅ 默认走 q01/q99 quantile normalization；z-score 的 mean/std 是另一条显式分支。正确方法是建立物理 active dimensions，再 pad 到模型维度，按 checkpoint 的 normalization revision 做对应逆变换，输出时按 mask/slice 取回。统计只从兼容 train split 计算。",
      "全身策略存在不同时间尺度：机械臂/夹爪、腰部和底盘未必接受同类型命令或同频率。v1 更稳妥的工程路线是先做 mode-gated sequential control（移动、稳定、再操作），同时保留统一观测；只有在任务证明确实需要动态全身协同、数据覆盖充分且安全层支持时，再开放 base+waist+arms 同时动作。",
      "Thor 的正确位置可以有三种：A 原生运行 PyTorch/openpi；B 把已验证模型转换为 TensorRT；C Thor 负责传感、机器人客户端和安全，而策略在工作站/GPU 服务器。三条路径共用同一 PolicyRequest/Response 和 action contract，所以能用证据比较。TensorRT 只有在逐层/端到端数值 parity、动作分布与 rollout 回归都通过后才是优化，不是默认捷径。",
    ],
    deepDive: [
      { title: "1. 你现在已确认和仍缺的参数", paragraphs: ["【已确认】机器人是双臂、腰部 2 个自由度、移动底盘；你有 Thor 计算平台。", "【合理推测】Thor 指 NVIDIA Jetson AGX Thor，且计划用于机器人端推理；本章按此设计。", "【个人观点】π₀.₅ 应作为第一条可执行主线，π0.6 做可替换研究支线。", "【暂无法验证】Thor 是 T5000 128GB 还是 T4000 64GB、JetPack/L4T 版本、双臂各自 DOF、夹爪类型、底盘运动学、ROS/控制中间件、相机数量与接口、动作命令类型、供电/散热以及任务成功标准。22 步中的 Gate 会逐项补齐，缺失时不进入真实执行。"], takeaways: ["硬件名字不是部署配置。", "未知项必须变成可测字段。"] },
      { title: "2. Whole-body action contract 示例，不是你机器的最终答案", paragraphs: ["示例 active vector 可按命名切片组织：[left_arm, left_gripper, right_arm, right_gripper, waist_yaw, waist_pitch, base]。每个 slice 单独声明 command_type、joint_names、frame、units、dt、limits、normalizer 和 valid mask；不能只写 dₐ=17。", "若底盘是差速，base 常见命令是 [vₓ,ω_z]；若全向可能是 [vₓ,v_y,ω_z]。这两种不能靠 padding 互换。腰部可用关节位置增量或速度参考，但必须和执行器/低层控制接口一致。"], takeaways: ["按名字和物理语义切片。", "padding 解决形状，不解决本体语义。"] },
      { title: "3. Thor 三路径门禁", paragraphs: ["路径 A 先用官方兼容范围内的 PyTorch/openpi 运行 dummy 与固定观测；记录 load time、峰值内存、warm-up 后 p50/p95/p99、功耗和温度。路径 B 转 TensorRT 后对同一批固定输入比较 raw action chunk 最大/分位误差、finite、限幅前后与闭环回归；FP8/更低精度不能只看速度。路径 C 在工作站策略服务与 Thor 客户端之间测端到端 latency、抖动、断网、乱序与 TTL。", "选择规则不是‘最快者胜’，而是先过正确性、稳定性、动作质量和安全降级，再比较延迟/功耗。若 A 不兼容，先回 C；不要为追求板上推理同时修改模型、框架、精度和控制协议。"], takeaways: ["同一输入做三路径 A/B/C 对照。", "一次只改变一个部署变量。"] },
      { title: "4. 为什么先顺序模式，再全身协同", paragraphs: ["移动底盘改变相机视角和机械臂基座 frame，腰部又改变双臂工作空间；同时动作使数据覆盖和碰撞约束呈组合增长。第一版定义 mode∈{navigate,stabilize,manipulate,recover}，在 manipulate 时锁定底盘或严格限速，可显著降低调试维度。", "这不是永远禁止 whole-body policy。通过 sequential baseline 后，用明确任务比较 simultaneous 是否提升成功/时间，并检查 near-miss、抖动、定位漂移和动作延迟；只有收益超过风险才扩展。"], takeaways: ["先建立可比较 baseline。", "是否同时动作由任务证据决定。"] },
      { title: "5. 22 步不是 22 条命令", paragraphs: ["每一步都有输入、操作、产物、门禁和失败回退。步骤 1–7 在没有 GPU 训练前完成；8–11 确保数据真实可回放；12–18 才进入模型；19–22 才允许从 shadow 逐级接触硬件。", "30–60h 是已有机器人 SDK、相机/急停和基本遥操作的工程学习预算，不包含大规模采集、长训练、硬件维修、审批或算法不收敛。把它当普遍工期是不成立的。"], takeaways: ["按 Gate 完成，不按小时强行推进。", "墙钟时间与学习预算分开。"] },
    ],
    formula: { latex: String.raw`a_t^{\mathrm{phys}}=\operatorname{Safety}\!\left(\operatorname{Slice}_m\left(\operatorname{Norm}^{-1}_{r}(\hat a_t)\right),q_t,\mathcal W\right),\qquad R_{\mathrm{queue}}=\left\lceil\frac{L^{\mathrm{e2e}}_{p99}+M}{\Delta t_a}\right\rceil`, symbols: [
      { symbol: "âₜ", meaning: "模型 padded/normalized action。" }, { symbol: "Normᵣ⁻¹", meaning: "由 normalization revision r 指定的逆变换；π₀.₅ 固定配置默认用 q01/q99 quantile，显式 z-score 分支才用 mean/std。" }, { symbol: "Sliceₘ", meaning: "按 mode 与 valid mask 取出真实物理维。" }, { symbol: "Safety", meaning: "独立限速、工作空间、碰撞与状态机；不是神经网络层。" }, { symbol: "W", meaning: "机器人/环境约束集合。" }, { symbol: "Lᵉ²ᵉₚ₉₉", meaning: "从同一观测时间到动作可用的端到端 p99。" }, { symbol: "Rqueue", meaning: "动作队列建议预留步数。" },
    ], note: "反归一化必须跟随 checkpoint/config 的 normalization revision，不能默认写成 z-score。固定 openpi 15a9616 的 π₀.₅ 路径选择 q01/q99 quantile；同一实现也保留显式 z-score 分支。p99+margin 的队列公式是工程预算，不是安全证明；优先测同一请求边界的端到端分布。" },
    practice: { title: "22 步 Thor 全身部署主线", summary: "页面的跟做模式给出每一步的动作、产物、验收与回退；先在离线/shadow 完成，再由独立安全门禁批准真实执行。配套脚本只验证示例契约的 quantile round-trip、padding/mode mask 和两类无效物理动作拒绝。", steps: ["按 22 步完成 Gate A–F。"], acceptance: ["Thor 软硬件 revision、功耗模式、性能和热状态有可复现记录。", "whole-body contract 包含所有 slice 的 name/type/frame/unit/dt/limit/mask/norm revision。", "π₀.₅ adapter 通过 pad/slice/finite/round-trip 与一批过拟合。", "ACT 与 π₀.₅ 使用同一物理接口和评测协议。", "shadow、单子系统和组合灰度均有 go/no-go 日志。", "后训练数据不污染冻结测试集。"], status: "配方核验", code: "python public/labs/whole_body_action_contract.py", expected: ["脚本打印示例 active_dim=20、pad_dim=32、六个 slice、q01/q99 教学 normalization revision、round-trip 与 valid/mode mask。", "脚本捕获 non-finite 与 limit 两类故障并以 WHOLE-BODY CONTRACT PASS 结束；它不验证真实 robot I/O、真实 train-split stats、碰撞或安全。"], debugging: ["环境不兼容先退回远端策略服务，不同时改模型和控制协议。", "任何 frame/unit/mask 不确定都停止在 shadow。", "Thor 降频先查功耗模式、温度和电源，再讨论模型优化。"] },
    pitfalls: ["把 Thor 峰值算力当端到端频率", "直接照抄 Mobile ALOHA 的动作切片和 norm", "把差速和全向底盘都写成 base[2]", "腰部加入向量但不加入 frame/碰撞模型", "一开始同时移动底盘、腰部和双臂", "TensorRT/低精度无动作 parity 就上真机", "策略服务断开后重复旧 chunk", "π0.6 没有可复现公开链路却写成主线", "人类接管动作覆盖策略原始输出", "安全 filter 只在 VLA 路径而 ACT baseline 绕过"],
    review: ["为什么 Thor 不自动保证 π₀.₅ 实时？", "padding 与跨本体适配的区别是什么？", "什么时候选远端策略服务？", "为什么第一版建议 sequential mode？", "从哪一步开始可以让动作接触硬件？"],
    completion: "另一位工程师能从干净 Thor 环境复现固定输入 smoke、whole-body contract、策略服务和 shadow 日志；真实动作只在独立急停/限速/碰撞/接管门禁全部有证据时执行。",
    sources: [{ title: "openpi · main@15a9616", url: "https://github.com/Physical-Intelligence/openpi/tree/15a9616a00943ada6c20a0f158e3adb39df2ccac", role: "2026-08-08 固定实现" }, { title: "openpi normalization config · 15a9616", url: "https://github.com/Physical-Intelligence/openpi/blob/15a9616a00943ada6c20a0f158e3adb39df2ccac/src/openpi/training/config.py", role: "π₀.₅ 默认 quantile 分支" }, { title: "openpi normalization transforms · 15a9616", url: "https://github.com/Physical-Intelligence/openpi/blob/15a9616a00943ada6c20a0f158e3adb39df2ccac/src/openpi/transforms.py", role: "q01/q99 与 z-score 正逆变换" }, { title: "openpi normalization statistics", url: "https://github.com/Physical-Intelligence/openpi/blob/15a9616a00943ada6c20a0f158e3adb39df2ccac/docs/norm_stats.md", role: "固定 revision 本体动作定义" }, { title: "openpi ALOHA real example", url: "https://github.com/Physical-Intelligence/openpi/tree/15a9616a00943ada6c20a0f158e3adb39df2ccac/examples/aloha_real", role: "固定 revision server/client 参考" }, { title: "Jetson AGX Thor User Guide", url: "https://docs.nvidia.com/jetson/agx-thor-devkit/user-guide/latest/", role: "官方硬件/软件" }, { title: "Jetson Thor power and performance", url: "https://docs.nvidia.com/jetson/archives/r39.2/DeveloperGuide/SD/PlatformPowerAndPerformance/JetsonThor.html", role: "功耗与 tegrastats" }, { title: "π*0.6 / RECAP", url: "https://www.pi.website/blog/pistar06", role: "官方研究报告；非公开部署证明" }],
    visual: "whole-body",
  },
} satisfies Record<string, LessonDetail>;
