import type { LessonWalkthrough } from "@/lib/lessonWalkthroughTypes";

const commonMathTrouble = ["先核对 shape、单位、log 的底数和 mean/sum reduction。", "只改一个变量并保留修改前输出，不要同时改公式和测试数据。"];

export const supplementalWalkthroughs = {
  "math-foundations": {
    intro: "本章用同一组数值串起五类常用公式。先在纸上写 shape，再运行标准库脚本；每次等价都要写清适用前提。",
    beforeYouStart: ["准备纸笔或电子表格。", "确认 python --version 为 3.10+。", "不要先看脚本末尾断言。"],
    steps: [
      { title: "建立唯一符号表", goal: "避免同一个 A 同时代表 action chunk 和 advantage。", actions: ["写 x=(images,state,language)，action_chunk∈R[B,H,dₐ]。", "另写 reward、return、value、advantage，不复用变量名。", "为每项写 shape 和 unit。"], expected: ["你会得到至少 B、K、H、dₐ 四个轴。", "动作与 advantage 使用不同代码变量名。"], checkpoint: "任取后续一条公式都能标出每个符号的 shape。", troubleshooting: commonMathTrouble },
      { title: "手推高斯 NLL", goal: "看见 MSE 背后的分布和尺度假设。", actions: ["令 target=1.0、mean=0.6、σ=0.5。", "计算平方误差、除以 2σ²，再加 log 常数。", "保持 σ 固定，说明最小化 NLL 与平方误差为何同方向。"], expected: ["平方误差为 0.16。", "你能指出 σ 改变会改变维度权重。"], checkpoint: "能口述固定方差条件。", troubleshooting: commonMathTrouble },
      { title: "手算一维高斯 KL", goal: "为 ACT/CVAE 的 KL 项建立可核查数值。", actions: ["取 μ=0.5、σ=0.8、先验 N(0,1)。", "代入 0.5(μ²+σ²−1−logσ²)。", "检查结果非负。"], expected: ["KL 约为 0.1681。", "若 μ=0 且 σ=1，KL 为 0。"], checkpoint: "两个边界值都正确。", troubleshooting: commonMathTrouble },
      { title: "从后向前算 advantage estimator", goal: "区分即时 reward、真实 advantage 定义与单轨迹估计。", actions: ["先写正式定义 A^π(s,a)=Q^π(s,a)−V^π(s)。", "取 rewards=[0,0,1]、γ=0.9，从末尾递推 Monte Carlo return Ĝₜ=rₜ+γĜₜ₊₁。", "再取 value estimates=[0.6,0.8,0.9]，计算 Âₜ=Ĝₜ−V̂(sₜ)。"], expected: ["return estimates=[0.81,0.9,1.0]。", "advantage estimates=[0.21,0.1,0.1]。", "不会把一条轨迹的 Ĝ−V̂ 当成 A^π 的定义。"], checkpoint: "可以解释为什么第一步 reward=0 但 return>0，以及 Q−V 与 Ĝ−V̂ 的区别。", troubleshooting: commonMathTrouble },
      { title: "手算 PPO clipping", goal: "看懂概率比值何时被截断，以及截断保护的到底是什么。", actions: ["取旧策略概率 0.25、新策略概率 0.30，算 ρ=0.30/0.25=1.20。", "令 ε=0.10、Â=0.50，算 unclipped=ρÂ=0.60。", "把 ρ 截到 [0.90,1.10]，得到 clipped=1.10×0.50=0.55，再取两者较小值。"], expected: ["该样本的 clipped surrogate 为 0.55。", "PPO clipping 限制单次策略更新幅度，不是机器人动作限幅、碰撞检查或急停。"], checkpoint: "能解释正 advantage 时为什么取 0.55，而不是 0.60。", troubleshooting: ["先确认分母是旧策略概率。", "advantage 为负时，min 的结果需要重新逐项比较。", ...commonMathTrouble] },
      { title: "运行完整数值脚本", goal: "用独立断言检查前五步。", actions: ["从项目根目录运行命令。", "逐段对照纸面结果；脚本标签 advantages 指本例的 Â=Ĝ−V̂，不是真实 A^π 定义。"], code: "python public/labs/vla_math_foundations.py", expected: ["输出 NLL、KL、return/advantage estimates、PPO clipping 和 flow endpoint。", "末行 MATH CHECKS PASS。"], checkpoint: "每段输出都能解释。", troubleshooting: ["若找不到文件，确认当前目录含 package.json。", ...commonMathTrouble] },
      { title: "用数值差分查梯度", goal: "学会在复杂模型前检查局部解析梯度。", actions: ["找到脚本中的 quadratic loss。", "比较解析梯度与 ±h 中心差分。", "把 h 改成 1e-2、1e-4、1e-8 观察误差。"], expected: ["中等 h 时两者接近。", "过小 h 可能受浮点消减影响。"], checkpoint: "能解释数值差分不是训练算法。", troubleshooting: commonMathTrouble },
      { title: "故意反转 flow 时间", goal: "把符号错误变成可见失败。", actions: ["复制脚本到临时位置。", "仅把 Euler dt 的符号反转。", "运行并比较 endpoint。"], expected: ["endpoint 远离目标。", "其他 NLL/KL 检查仍通过。"], checkpoint: "失败只由一个变量引起并已记录。", troubleshooting: commonMathTrouble },
      { title: "迁移到一条真实 VLA batch", goal: "让符号表成为工程检查器。", actions: ["从现有数据 loader 打印 images/state/actions/mask shape。", "为 action 每个 slice 写 unit。", "列出 loss 在哪些轴做 mean/sum。"], expected: ["得到真实 batch 的带单位 shape 表。", "未知字段被明确标记，而非猜测。"], checkpoint: "另一人能按表读懂你的 loss。", troubleshooting: ["若 loader 尚未建立，先使用 data-and-adaptation 章 demo。", ...commonMathTrouble] },
    ],
    finalArtifact: ["一页不重名的 VLA 符号表。", "五段手算和脚本完整输出。", "一次错误时间方向的失败记录。", "真实 batch 的 shape/unit/reduction 表。"],
    verifiedBoundary: "脚本验证确定性算术与断言，不验证任何真实模型收敛、策略提升或安全性。",
    knowledgeCheck: [
      { question: "MSE 何时与高斯 NLL 等价？", answer: "当模型均值是待优化量、方差固定且忽略与均值无关的常数时；不同维方差还会引入权重。" },
      { question: "为什么 action_chunk 和 advantage 不应都叫 A？", answer: "论文可由上下文区分，代码中却容易广播或记录错对象；用 action_chunk 与 advantage 明确区分。" },
      { question: "全失败 group 的相对 advantage 怎样？", answer: "奖励方差为零，稳定化后优势接近零，通常没有方向性学习信号。" },
      { question: "PPO clipping 能代替动作限幅或碰撞检查吗？", answer: "不能。它约束训练时的新旧策略概率比，机器人安全仍由独立的动作合同、限幅、碰撞检查、TTL 和急停功能处理。" },
      { question: "Euler 的负号为什么危险？", answer: "它改变积分方向，可能把噪声推离数据或把动作逆向生成；必须与训练的时间约定一致。" },
    ],
  },

  "act-cvae": {
    intro: "这里实现的是 language-conditioned ACT-style 课程变体：复用 BC 章冻结的数据切分与 K=2、H=16、dₐ=7 动作合同，再把三段推导映射到 KL、masked chunk loss 和重叠动作融合。原始 ACT 不输入语言；本章的 K/H/7D 也不是原论文默认配置。",
    beforeYouStart: ["已完成数学地基与 Behavior Cloning，并保留 BC 的 dataset/checkpoint/rollout 产物。", "能读取 H×dₐ 张量；动作单位、frame、dt 和训练集统计沿用 BC 章，不在本章重新拟合。", "安装只需 Python 3.10+；action-chunking 的 TTL 与异步执行将在下一章继续完成。"],
    steps: [
      { title: "画训练信息流", goal: "标出未来动作只在训练期可见，并区分原始 ACT 与课程变体。", actions: ["画 image/q/language/action_chunk 四项；把 language 标为课程新增条件。", "action_chunk+q 进入 style encoder。", "采样 z 后 image/q/language/z 进入课程 decoder；另注原始 ACT 路径不含 language。"], expected: ["真实未来动作不直接进入 decoder 输出端。", "能指出 K=2、H=16、dₐ=7 与 language 都属于课程配置。"], checkpoint: "能指出 posterior 的条件，并说明哪条边不是原始 ACT。", troubleshooting: ["不要把未来 action 当普通传感器。", "不要用 ACT 名称掩盖课程新增的语言条件。"] },
      { title: "画推理信息流", goal: "消除训练期未来信息泄漏。", actions: ["删掉 action_chunk 和 style encoder。", "按 checkpoint 约定将 z=0 或从先验采样。", "课程变体保留 image/q/language→decoder；原始 ACT 只保留 image/q。"], expected: ["推理图没有 ground-truth future action。", "原始路径和课程 language-conditioned 路径没有混写。"], checkpoint: "训练与推理差异已用颜色标出。", troubleshooting: ["若实现推理仍调用 encoder，检查官方 checkpoint 代码路径。"] },
      { title: "手算重参数化与 KL", goal: "看懂 CVAE 的两项损失。", actions: ["用数学地基章 μ、σ 复算 KL。", "固定 ε=0.25 算 z=μ+σε。", "说明固定 ε 只用于可复现教学。"], expected: ["z 可被确定性复算。", "KL 非负。"], checkpoint: "可以解释为什么需要重参数化。", troubleshooting: commonMathTrouble },
      { title: "构造三个重叠 chunk", goal: "按真实执行时刻对齐，并把候选顺序与权重方向分开检查。", actions: ["写 query 0 预测时刻0,1,2。", "query 1 预测时刻1,2,3。", "query 2 预测时刻2,3,4。", "对执行时刻 2 按旧→新排列三个候选；分别计算官方代码的 exp(−k·index) 与年龄衰减 exp(−k·age)。"], expected: ["执行时刻 2 有三个候选。", "官方固定实现给旧候选更高权重；年龄衰减对照给新候选更高权重，两者结果不同。"], checkpoint: "每个候选能追溯 query_time 和 offset，并能说明权重到底作用于数组 index 还是物理 age。", troubleshooting: ["用 execute_time=query_time+offset，不要凭数组位置。", "只看到 exp(−ki) 不能判断偏好新旧，必须先写候选排列顺序。"] },
      { title: "运行 ACT 机制脚本", goal: "核对 KL 与融合算术。", actions: ["运行命令。", "将输出抄入你的重叠表。"], code: "python public/labs/act_cvae_mechanics.py", expected: ["打印 KL、候选和加权结果。", "末行 ACT MECHANICS PASS。"], checkpoint: "脚本与手算一致。", troubleshooting: commonMathTrouble },
      { title: "制造一格时间错位", goal: "看见 temporal ensemble 不是普通平滑。", actions: ["只把一个 query_time 加 1。", "重新列执行时刻 2 的候选。", "比较融合前后。"], expected: ["候选集合或权重变化。"], checkpoint: "能定位到时间戳而非模型权重。", troubleshooting: ["确保只改 query_time。"] },
      { title: "处理 padding 与 valid mask", goal: "把教材中的 masked reconstruction 变成可执行断言。", actions: ["先复算教材数值例：误差 [0.1,−0.2,0,10]、mask=[1,1,1,0]，valid-only L1 应为 0.1，完整张量 mean 应为 0.075。", "再构造剩余 2 步但 H=4 的样本，写 actions shape [4,dₐ] 和 mask=[1,1,0,0]。", "把 padding 从 0 改为 10^6，确认两种 masked reduction 都不受 padding 数值影响，同时记录二者尺度差异。"], expected: ["padding 值改变不会改变 masked loss。", "忘记 mask 时损失会被故意放大的 padding 主导。", "valid-only mean 与官方代码风格的 full-tensor mean 数值不同，但差异可由分母解释。"], checkpoint: "padding invariance 断言通过，并能说出当前训练代码采用哪一种 reduction。", troubleshooting: ["检查 mask 是否广播到 action 维。", "若两个 batch 的有效步数不同，检查 reduction 是否除以有效元素数还是固定 B×H×dₐ。"] },
      { title: "让 ACT 与 π₀.₅ 共用接口", goal: "用窄基线定位模型与系统问题。", actions: ["定义统一 PolicyRequest。", "把 ACT 输出反归一化为与 π₀.₅ 相同的物理 slice。", "让两者通过同一 TTL/限幅/日志。"], expected: ["评测器不需要知道后端是 ACT 还是 VLA。"], checkpoint: "同一固定输入可切换 policy revision。", troubleshooting: ["若结果尺度不同，先比 raw/norm/denorm 三层。"] },
    ],
    finalArtifact: ["训练/推理双色图。", "KL 与 z 手算。", "重叠 chunk/时间错位表。", "统一 PolicyRequest/Response。"],
    verifiedBoundary: "Toy 只验证 CVAE 与 temporal ensemble 的算术；没有训练视觉 Transformer，也没有复现 ACT 真实任务成功率。K=2、H=16、dₐ=7 和语言条件属于课程 ACT-style 变体，不能标成原始 ACT 配置。",
    knowledgeCheck: [
      { question: "训练期 style encoder 看什么？", answer: "当前关节/状态与真实未来动作块，用于近似后验 q(z|q,A)。" },
      { question: "推理为何不能继续用该 encoder？", answer: "未来真实动作不可用；推理必须按实现从先验/固定 z 生成。" },
      { question: "temporal ensemble 与 receding horizon 的区别？", answer: "前者融合多个 query 对同一执行时刻的预测，后者决定动作块只执行多少步后重规划。" },
      { question: "ACT 成功能证明 VLA 一定可学吗？", answer: "不能；它只为特定数据、配置和接口建立窄策略正证据。" },
      { question: "本章为什么不是原始 ACT 复现？", answer: "原始 ACT 不使用语言输入；本章为贯穿案例新增语言条件，并采用课程自己的 K=2、H=16、dₐ=7 数据合同。" },
    ],
  },

  "post-training": {
    intro: "先做方法选择和数据治理，再手算 RL 信号。没有非零基础能力、可靠 reward 或安全 rollout 条件时，本章的正确结果可能是‘暂不上 RL’。",
    beforeYouStart: ["冻结一份从未训练的 test revision。", "有基础策略的分层 rollout 结果。", "所有真实机器人试验有独立安全审批。"],
    steps: [
      { title: "冻结 base 与 evaluator", goal: "后续提升必须可归因。", actions: ["记录 checkpoint、dataset、success detector revision。", "冻结 seeds/tasks/scenes。", "保存 base 原始视频和日志。"], expected: ["得到不可覆盖的 baseline manifest。"], checkpoint: "重新运行能得到同格式报告。", troubleshooting: ["若 evaluator 仍在改，先不比较算法。"] },
      { title: "测基础策略是否有非零能力", goal: "判断稀疏奖励是否提供差异信号。", actions: ["按任务/场景分层运行。", "记录成功、失败、接管和超时。", "不只看总体平均。"], expected: ["知道哪些任务为 0%、低成功或稳定成功。"], checkpoint: "每层有 N 与不确定性。", troubleshooting: ["样本少就扩大 rollout，不下强结论。"] },
      { title: "先排 pipeline bug", goal: "不让 RL 学 frame、unit、时序错误。", actions: ["expert replay 检查执行器。", "一批过拟合检查训练链。", "固定观测核对 adapter 前后。"], expected: ["接口错误有独立 PASS。"], checkpoint: "已知 bug 清零后再收后训练数据。", troubleshooting: ["专家 replay 也失败就回数据/执行章节。"] },
      { title: "定义 intervention 日志", goal: "区分策略建议、人类修正和实际执行。", actions: ["记录 policy_action。", "记录 human_action/takeover_reason。", "记录 safety 后 executed_action。"], expected: ["三种 action 可逐时刻对齐。"], checkpoint: "任一接管可完整回放。", troubleshooting: ["旧数据缺字段就标 unknown，不猜。"] },
      { title: "先做 correction SFT", goal: "优先利用高质量纠错而非危险探索。", actions: ["从 base 失败状态采 recovery/correction。", "episode-level 加入 train，不改 test。", "小步 SFT 并跑完整回归。"], expected: ["得到 correction dataset/checkpoint revision。", "提升与退化都如实报告。"], checkpoint: "没有回归失败才进入下一 Gate。", troubleshooting: ["遗忘明显时混入原 SFT 数据或减小更新。"] },
      { title: "审计 reward", goal: "确认奖励测量任务而非视觉捷径。", actions: ["列 outcome/progress/preference 来源。", "独立标注集算 precision/recall。", "做遮挡、背景、reset 泄漏反例。"], expected: ["得到 reward card 与失败示例。"], checkpoint: "reward 误判率在风险许可内。", troubleshooting: ["reward 不可靠就停在 SFT/人工评估。"] },
      { title: "运行 group RL Toy", goal: "看见相对 advantage 的来源和消失。", actions: ["运行默认混合成功组。", "再运行/修改为全失败组。", "比较 advantage。"], code: "python public/labs/post_training_group_rl.py", expected: ["混合组有正负信号。", "全失败组为零信号。", "末行 POST-TRAINING TOY PASS。"], checkpoint: "能解释不是有 reward 就有梯度。", troubleshooting: commonMathTrouble },
      { title: "选择 offline 或 online", goal: "按证据而不是论文热度选择风险。", actions: ["若只有固定数据，列出 OOD action 风险。", "若在线，列探索范围、接管和磨损预算。", "优先在仿真/安全沙箱验证。"], expected: ["一张 go/no-go 决策表。"], checkpoint: "每个风险有 owner 和 stop rule。", troubleshooting: ["没有独立 safety owner 就不做真实在线 RL。"] },
      { title: "建立 canary 与冻结回归", goal: "防止新能力换来旧能力退化。", actions: ["选短、可重复 canary。", "同时运行旧任务 frozen regression。", "报告分层差值与区间。"], expected: ["新旧 checkpoint 同协议对比。"], checkpoint: "未通过任一关键回归即 no-go。", troubleshooting: ["不要只挑提升任务。"] },
      { title: "发布或回退", goal: "让后训练成为可逆工程流程。", actions: ["记录模型/数据/reward revision。", "保留 base 一键回退。", "发布后持续记录 drift/near-miss。"], expected: ["有明确 rollout percentage 和 rollback trigger。"], checkpoint: "值班人员能在无作者情况下回退。", troubleshooting: ["回退流程未演练就不扩大流量。"] },
    ],
    finalArtifact: ["基础能力分层报告。", "intervention episode schema。", "reward card。", "方法选择与 go/no-go 表。", "冻结回归和回退方案。"],
    verifiedBoundary: "本站只验证 group-relative toy 算术；真实后训练收益、安全和 reward 可信度必须由你的数据与审批验证。",
    knowledgeCheck: [
      { question: "基础策略 0% 时为什么先不盲目 group RL？", answer: "同组 rollout 可能全部失败，优势接近零；应先补演示、缩短任务或修 pipeline。" },
      { question: "executed_action 为什么不能覆盖 policy_action？", answer: "否则无法区分策略、人工和安全层的贡献，也不能正确做离线学习或事故复盘。" },
      { question: "reward model 为什么不是安全层？", answer: "它会误判、受分布漂移和捷径影响；安全约束需独立、可验证、及时执行。" },
      { question: "π*0.6 官方报告能证明什么？", answer: "能证明其报告的训练思路与结果；不能自动证明公开 openpi 已提供同等完整可部署实现。" },
    ],
  },

  "mobile-dual-arm-pi-deployment": {
    intro: "这 22 步从零动作的离线清单开始，以可回退的真机灰度结束。步骤号是依赖关系；任何 Gate 未通过都停在当前阶段，不以‘已经买了 Thor’或‘loss 降了’为放行理由。",
    beforeYouStart: [
      "本章把 Thor 暂按 NVIDIA Jetson AGX Thor；第 1 步必须用实机输出确认 T5000/T4000、内存和 JetPack/L4T。",
      "准备机器人厂商控制 API、关节/夹爪/底盘接口文档、急停与碰撞保护说明。",
      "真实动作前必须有独立急停、限速/限位、碰撞/工作空间保护、deadman 或人工接管，以及现场风险负责人。",
      "先创建实验目录保存文本/JSON/YAML/日志；不要把密钥和机器人内网地址提交到公开仓库。",
    ],
    steps: [
      {
        title: "盘点 Thor，而不是只写‘有一块 Thor’",
        goal: "确认实际 SoM、内存、系统、CUDA/TensorRT、功耗模式、磁盘和热状态；这些决定可复现环境与推理路径。",
        actions: ["在 Thor 本机执行只读命令并保存为 thor_inventory.txt。", "额外记录电源、载板、NVMe、散热方式与是否 headless。", "空闲运行 2 分钟 tegrastats，记录温度、内存和功耗；用 Ctrl+C 结束。"],
        code: "uname -a\ncat /etc/nv_tegra_release\ncat /proc/device-tree/model\nfree -h\ndf -h /\ndpkg-query -W 'nvidia-jetpack' 'nvidia-cuda*' 'tensorrt*' 2>/dev/null\nsudo nvpmodel -q\nsudo tegrastats",
        expected: ["能明确写出 T5000 128GB 或 T4000 64GB，而不是泛称 Thor。", "得到 L4T/JetPack、aarch64、CUDA/TensorRT 包、功耗模式和空闲温度。", "某些包未安装可以为空；这不是自动失败，而是环境事实。"],
        checkpoint: "thor_inventory.txt 中没有‘大概’；所有可读参数来自命令或实物标签。",
        troubleshooting: ["若 /etc/nv_tegra_release 不存在，确认是否运行在 Thor 的 Jetson Linux，而非容器/其他主机。", "若 nvpmodel/tegrastats 不存在，先核对 BSP/JetPack，不要安装 Ubuntu 仓库的 nvidia-cuda-toolkit。", "若你实际不是 Jetson AGX Thor，停止使用本章的 Thor 特定命令并重新定义平台。"],
      },
      {
        title: "冻结第一个任务与模型开放性 Gate",
        goal: "避免同时解决开放世界、导航和双臂协同；确认模型路线确实可获得、可运行、许可可用。",
        actions: ["写 task_spec：起始状态、语言指令、成功/失败、超时、允许接触、速度和人员隔离。", "第一任务优先选择短、可 reset、底盘停稳后的双臂或单臂操作。", "将模型列为 π0.5 executable baseline；π0.6 只有在权重、代码、输入输出、许可证和固定 revision 五项齐全时才切换。"],
        expected: ["得到一页 task_spec 和 model_gate 表。", "π0.6 不会因名字更新就自动成为部署主线。"],
        checkpoint: "陌生工程师能用 task_spec 独立判断 success/failure。",
        troubleshooting: ["任务包含过多自由度时先拆 navigate→stabilize→manipulate。", "若 π0.6 只有报告/视频，保持‘暂无法验证’。"],
      },
      {
        title: "清点全部执行器与控制接口",
        goal: "将‘双臂+腰+底盘’变成命名、方向、单位和控制类型明确的设备表。",
        actions: ["逐项记录左右臂 DOF、joint names/order/limits、夹爪命令与反馈。", "记录腰部两个关节的物理轴、零位、limit、是否自锁。", "记录底盘是差速/全向/其他，接收 velocity 还是 pose/trajectory。", "为每个接口记录标称/实测 command rate 与 timeout 行为。"],
        expected: ["robot_io.csv 每个自由度一行。", "左右、正方向、弧度/米、position/velocity 等无歧义。"],
        checkpoint: "任一向量元素都能反查物理执行器。",
        troubleshooting: ["厂商字段不清就做低速单轴 jog 并由两人确认；未确认前不接模型。", "不要从数组长度猜底盘运动学。"],
      },
      {
        title: "建立 TF/frame 树与标定清单",
        goal: "底盘和腰部运动会改变双臂基座与相机几何，frame 错误会系统性生成反向动作。",
        actions: ["画 map/odom/base_link/waist/left_arm_base/right_arm_base/tool/camera frames。", "标出静态外参和随关节变化的变换。", "为头部/外部/腕部相机记录内参、外参、分辨率、曝光和时间戳来源。", "用已知点或 AprilTag/标定板检查至少三个姿态。"],
        expected: ["一张 TF 图和 calibration revision。", "腰部动作后，arm base 到 camera 的变换会正确更新。"],
        checkpoint: "可视化中轴向、左右手和重投影与实体一致。",
        troubleshooting: ["静止重投影好、腰动后坏，优先检查动态 TF 和时间同步。", "不要把 base_frame delta 当 tool_frame delta。"],
      },
      {
        title: "定义带时间的 whole-body state",
        goal: "让模型知道机器人当时是什么状态，并能审计多源观测是否同一时刻。",
        actions: ["定义 state slices：两臂 q/dq、夹爪、腰 q/dq、底盘 twist/pose、可选力/触觉。", "每个 source 保存 measurement_time，不只保存 batch_time。", "定义 stale threshold、缺失传感器 valid mask 与历史窗口。", "打印一帧 named state，不只打印数组。"],
        expected: ["state_contract.yaml 含 name/slice/unit/frame/rate/time source。", "一帧日志可显示各源时间差。"],
        checkpoint: "相机/状态最大 skew 小于你在 task_spec 中定义的门限。",
        troubleshooting: ["skew 大时先做硬件/软件同步或按时间插值；不要靠加历史掩盖。", "未知速度不要用 0 冒充，使用 mask。"],
      },
      {
        title: "定义 whole-body action、mode 与 padding",
        goal: "把物理动作语义与模型固定维度解耦，加入腰部而不破坏其他本体。",
        actions: ["按 left_arm/left_gripper/right_arm/right_gripper/waist/base 命名 slice。", "为每个 slice 写 command_type、frame、unit、dt、limits、normalizer 和 valid mask。", "先定义 mode-gated 动作：navigate/stabilize/manipulate/recover；无效 slice 必须 mask。", "运行契约脚本，修改示例 DOF 以匹配 robot_io.csv。"],
        code: "python public/labs/whole_body_action_contract.py",
        expected: ["脚本打印 active_dim=20、pad_dim=32、六个 slice、q01/q99 教学 norm revision、round-trip error 与 valid/mode mask。", "non-finite 与 limit 两类故障被捕获；脚本没有单独注入 mask corruption。", "默认统计来自示例 limits，不是真实 train split，必须替换为目标机器定义。"],
        checkpoint: "physical→quantile normalize→pad→quantile denormalize→mode slice 的有效维误差通过断言，base 在 manipulate mode 被 mask，padding 不进入反归一化或执行。",
        troubleshooting: ["active_dim>32 时不能只截断；修改模型/adapter 设计并重新评估。", "差速底盘通常 [vₓ,ωz]，全向可能 [vₓ,vᵧ,ωz]；必须按实机确认。", "常量维 norm 除零时用 fixed/mask 处理。"],
      },
      {
        title: "确定多频率控制与独立安全边界",
        goal: "策略查询、动作采样和各子系统伺服不能混成一个 Hz。",
        actions: ["实测 arms/waist/base 的 command consumption 与 watchdog。", "选 policy query、action_dt、H 和 execution E；先做 sequential mode。", "在模型外实现 joint/base limits、workspace、self/environment collision、acceleration/jerk、TTL 和 controlled stop。", "逐个故障注入 stale/NaN/乱序/断网。"],
        expected: ["frequency_budget.md 区分 f_policy/f_action/f_servo。", "所有拒绝都有确定 fallback 和日志。"],
        checkpoint: "模型进程被杀时机器人进入经厂商/风险分析确认的状态。",
        troubleshooting: ["hold 对移动底盘和重力臂未必安全，按子系统定义 stop。", "先测端到端 p99，不把组件 p99 相加当统计定理。"],
      },
      {
        title: "建立全身遥操作与 deadman",
        goal: "模型上线前先有能稳定完成任务、能随时停的专家接口。",
        actions: ["为 base/waist/arms 设计显式 mode 切换或双人协作。", "deadman 松开立即进入定义的 stop。", "UI 同时显示 active mode、控制对象、限幅与相机。", "先无负载、低速完成 task_spec。"],
        expected: ["专家能重复完成短任务。", "每次 mode 切换与 deadman 事件被记录。"],
        checkpoint: "人工演示本身没有不可控跳变。",
        troubleshooting: ["遥操作做不好时不要先采大量数据；修 UI、映射和延迟。", "左右臂镜像错误先做单轴核对。"],
      },
      {
        title: "采集成功、失败、恢复与语言变体",
        goal: "让数据覆盖策略会遇到的关键状态，而不是只录完美视频。",
        actions: ["按 episode 保存 instruction、task/config revision、所有原始观测与时间。", "分别标 success/failure/intervention/recovery/near-miss。", "记录不同物体位置、光照、相机轻扰动和同义指令；一次只改变可追踪因素。", "禁止先用 test 场景反复调参。"],
        expected: ["每条 episode 有完整来源和终止原因。", "数据分布表按 task/scene/language/mode 分层。"],
        checkpoint: "随机抽 10 条可播放且 action 与画面时间一致。",
        troubleshooting: ["图像与动作错位就暂停采集，先修时间协议。", "接管后 executed_action 必须与 policy_action 分开。"],
      },
      {
        title: "转换数据并做 episode-level split",
        goal: "将自定义记录变成可训练且不泄漏的数据 revision。",
        actions: ["映射到 LeRobotDataset 或固定自定义 schema。", "按 episode/task/object/environment 分 train/val/test，不按帧随机切。", "从 train-only 计算 state/action stats。", "保存 contract/calibration/dataset revision。"],
        expected: ["split 没有 episode 重叠。", "test 不参与 norm 和 reward model 训练。"],
        checkpoint: "数据审计脚本 PASS 且映射表人工复核。",
        troubleshooting: ["自定义 manifest 不是 LeRobot 原生字段，文档中明确映射。", "常量/稀疏 slice 单独处理。"],
      },
      {
        title: "专家动作 replay 与零模型 dry-run",
        goal: "在训练前证明数据→adapter→执行器链路的物理语义正确。",
        actions: ["离线重放并画每个 slice。", "在仿真或架空/disabled actuator 模式喂专家动作。", "检查 base/waist/arms 的顺序、符号、单位和 dt。", "用 zero/hold policy 走同一接口。"],
        expected: ["专家轨迹在可控环境中按预期复现。", "zero/hold 不产生未命名动作。"],
        checkpoint: "任何一个 slice 都没有反向、错位或越界。",
        troubleshooting: ["专家 replay 失败是 pipeline 错，不是模型问题。", "先逐子系统，再组合。"],
      },
      {
        title: "固定 openpi 与部署环境 revision",
        goal: "把动态主线变成可复现依赖，并先证明 checkpoint 可加载。",
        actions: ["记录 openpi commit、checkpoint URI/hash、framework、Python/transformers/JAX/PyTorch 版本。", "在官方支持环境先跑固定 observation smoke。", "Thor 原生失败时保存完整错误并启用路径 C：工作站 server + Thor client。", "不要同时改 transformers patch、精度和 action adapter。"],
        expected: ["得到 environment lock 和 fixed-input raw action。", "原生或远端至少一条 smoke 路径可复现。"],
        checkpoint: "同一固定输入重复推理 finite、shape 一致且 revision 可追溯。",
        troubleshooting: ["ARM64/JetPack 依赖冲突先容器化或远端服务，不盲目降级多个包。", "openpi README 会变，必须用 commit 而非 main 描述结果。"],
      },
      {
        title: "实现自定义 Inputs/Outputs 与 DataConfig",
        goal: "把你的相机、state、语言和 action contract 接入 π₀.₅，而不是改机器人去假装 ALOHA。",
        actions: ["Inputs：按 checkpoint 要求 resize/crop/normalize images，按名字拼 state，传 prompt。", "Outputs：调用 normalization_revision 对应的 Norm⁻¹，再按 mode/mask slice、转换 frame/unit，最后交 safety；不要把 z-score 写死为通用反归一化。", "DataConfig：字段映射、delta timestamps、action horizon 和 transforms 全部版本化。", "用一条样本逐层保存 raw→model→physical 中间值。"],
        expected: ["adapter_trace.json 可看到每层 shape/range/revision。", "模型 padded 维不直接流入执行器。"],
        checkpoint: "手工样本 round-trip 与 whole_body_action_contract.py 一致。",
        troubleshooting: ["先比较一条样本，不在训练 loss 中猜 adapter 错误。", "crop 改变相机几何时记录配置。"],
      },
      {
        title: "计算兼容的 norm stats",
        goal: "避免把其他本体统计套到新增腰部和未知底盘上。",
        actions: ["逐 slice 检查物理定义是否与公开 stats 完全一致。", "固定 openpi 15a9616 的 π₀.₅ 默认使用 q01/q99 quantile；从本机 train split 计算匹配统计，并记录 Norm/Norm⁻¹。", "只有显式选择 z-score 分支时才改用 mean/std；不要混用两套正逆变换。", "保留 clip count、常量维、NaN/Inf 和单位检查；stats 与 dataset/action contract revision 绑定。"],
        expected: ["每个 active dimension 有来源。", "腰部/底盘不会借用不相容本体统计。"],
        checkpoint: "同一 normalization revision 的 Norm/Norm⁻¹ 有效维 round-trip 通过，π₀.₅ 默认报告 q01/q99，val/test 不参与统计。",
        troubleshooting: ["统计极端先查单位与 outlier，不直接扩大范围。", "公开 Mobile ALOHA stats 只有契约完全相同才可尝试。"],
      },
      {
        title: "做一批过拟合、保存与重载",
        goal: "在昂贵训练前验证数据、mask、loss、adapter 和 checkpoint 链。",
        actions: ["选 1 batch/少量 episode，固定 seed。", "训练到明显拟合并保存。", "重载后对同一输入比较 raw/norm/physical action。", "打乱语言、遮挡一相机、mask 某 action group 做单变量检查。"],
        expected: ["小样本 loss 显著下降；具体阈值由训练配置记录。", "重载输出在允许数值误差内一致。", "条件消融是否变差如实报告，不预设结论。"],
        checkpoint: "无法过拟合就不进入长训练。",
        troubleshooting: ["查时间对齐、mask、scale、冻结参数和 optimizer。", "loss 降而物理动作错，查 inverse transform。"],
      },
      {
        title: "训练同接口 ACT baseline",
        goal: "建立较窄、可审计的动作块基线，定位 VLA 特有问题。",
        actions: ["ACT 使用同一 images/state/action physical contract 和 split。", "记录 H、temporal ensemble、CVAE/KL 与参数量。", "通过同一 safety/executor 做离线和后续 rollout。", "不因为模型小就给它不同限速。"],
        expected: ["得到可重载 ACT checkpoint 和同格式报告。"],
        checkpoint: "ACT/π₀.₅ 可由同一客户端配置切换。",
        troubleshooting: ["两者都失败优先查共同数据/执行层。", "ACT 成功只提供窄策略正证据。"],
      },
      {
        title: "微调 π₀.₅ 并做 Thor 三路径性能门禁",
        goal: "分开验证模型学习、部署正确性和平台性能。",
        actions: ["固定训练配置微调 π₀.₅；保存完整 revision。", "路径 A：Thor 原生；B：TensorRT/低精度；C：远端 server，对同一固定输入运行。", "记录 warm-up、峰值内存、p50/p95/p99、功耗/温度和 throttling。", "比较 raw action 分位误差、finite、clip count 与固定回归。"],
        expected: ["一张 A/B/C 正确性与性能表。", "最快但 parity/稳定性失败的路径被淘汰。"],
        checkpoint: "至少一条路径通过正确性、稳定性和延迟预算。",
        troubleshooting: ["Thor 频率下降先查 nvpmodel、温度、电源和内存压力。", "TensorRT 偏差大时回 FP16/原生，不让真机替你做数值测试。", "社区报告只作线索，不当你的性能事实。"],
      },
      {
        title: "做离线回放、固定仿真/台架评测与消融",
        goal: "在动作接触硬件前找到条件失效与协议错误。",
        actions: ["同 seed 比 zero/hold、ACT、π₀.₅。", "按 language/camera/action group/mode 做一次一变量消融。", "报告 task/object/environment/mode 分层和 N/区间。", "保存 raw policy action 与 safety 后 action。"],
        expected: ["得到失败树，不只有 success rate。", "能区分 perception、policy、adapter、latency、safety 和 evaluator。"],
        checkpoint: "关键回归无未解释退化；否则不进 shadow。",
        troubleshooting: ["离线好、仿真坏时查 covariate shift 与闭环。", "ACT/π₀.₅ 都反向时查共同 frame/norm。"],
      },
      {
        title: "实现带时间戳的 Thor policy client/server",
        goal: "真实网络和推理延迟下拒绝旧动作并保留可回放日志。",
        actions: ["request 含 request_id、observation_time、camera times、state/action contract revision。", "response 含 action_dt、chunk、created_time、model/norm revision。", "客户端按当前时间跳过过期前缀，拒绝乱序/TTL/NaN。", "注入断网、server kill、重复包和延迟尖峰。"],
        expected: ["每种故障进入确定的 controlled stop。", "端到端 p99 从 observation_time 到 action available 实测。"],
        checkpoint: "服务重启不会执行旧队列。",
        troubleshooting: ["时钟不同步先用同机 monotonic 或同步方案并记录。", "不要把平均延迟当队列余量。"],
      },
      {
        title: "Shadow mode：模型只建议，不执行",
        goal: "用真实传感和时序检查动作质量，同时保持执行器隔离。",
        actions: ["机器人由专家或保持安全状态运行，模型输出只记录。", "实时显示每个 slice、mode、limit/碰撞过滤和 stale skip。", "比较 expert/executed 与 policy suggestion。", "收集至少覆盖 task_spec 主要状态的 shadow 日志。"],
        expected: ["发现的 frame/norm/mode 错误不会接触硬件。", "near-limit、clip、stale 和 disagreement 有统计。"],
        checkpoint: "连续 shadow 无未解释越界/NaN/过期动作后才申请动作灰度。",
        troubleshooting: ["shadow 中 base/waist 持续非零先查 mode/mask。", "不要用 safety clip 掩盖系统性尺度错误。"],
      },
      {
        title: "分级低速灰度、冻结评测与故障回归",
        goal: "一次只增加一种物理耦合，并用一致协议判断是否能从试验转为受控使用。",
        actions: ["先空载/架空或安全场地逐个测试 arms、waist、base；具体顺序由风险分析决定。", "再测试 base 停稳+waist/arms，最后才评估 simultaneous whole-body；每级有速度、空间、人员和次数门禁。", "按预注册 seeds/tasks/scenes 比 ACT/π₀.₅ 和旧稳定版本，不删除失败 rollout。", "注入相机掉线、网络尖峰、stale state、mode mismatch；报告成功、超时、接管、near-miss、p99、clip 与能耗/热。", "任何 near-miss/接管/异常立即 stop、冻结日志、复盘。"],
        expected: ["每级都有 go/no-go 记录。", "sequential baseline 可重复完成后才讨论 simultaneous。", "结果带 N、分层和不确定性，故障回归进入预期降级。"],
        checkpoint: "达到 task_spec 与安全门槛并由独立安全负责人批准下一等级；否则 no-go 也是合格结论。",
        troubleshooting: ["不要让模型置信度覆盖 safety no-go；组合失败退回上一级做最小复现。", "样本少就增加 N，不用最佳视频替代统计。", "热降频导致延迟漂移时纳入持续负载测试。"],
      },
      {
        title: "建立失败驱动纠错与可选后训练闭环",
        goal: "先用最可控的数据修复，再决定是否需要 RL。",
        actions: ["从失败树选一个高频可纠正 leaf，采 human correction/recovery。", "保留 policy_action/human_action/executed_action，新增 train revision，不动 frozen test。", "先做 correction SFT/DAgger 并跑全回归。", "只有基础策略有非零能力、reward 经审计、仿真/安全 rollout 与回退均通过时，才评估 offline/online RL；π0.6 仍需通过第 2 步开放性 Gate。"],
        expected: ["每轮只针对明确失败模式。", "提升与遗忘都能追溯 dataset/checkpoint/reward revision。", "不满足 RL 条件时输出‘暂不上 RL’，不是强行完成。"],
        checkpoint: "新版本通过 frozen regression、Thor 性能与安全故障回归后才灰度替换。",
        troubleshooting: ["纠错后旧任务退化，混入原 SFT 数据/减小更新并重跑。", "reward 与真实成功不一致就停止 RL。", "π0.6 公开链路变化时重新锁 commit 和完整 smoke，不沿用 π0.5 结论。"],
      },
    ],
    finalArtifact: [
      "thor_inventory.txt：SoM/内存/JetPack/L4T/CUDA/TensorRT/功耗/温度。",
      "task_spec、model_gate、robot_io.csv、TF/calibration revision。",
      "whole_body state/action contract、mode/mask、norm stats 和本地故障注入输出。",
      "数据审计、expert replay、openpi adapter trace 与一批过拟合报告。",
      "ACT/π₀.₅ 同协议比较和 Thor A/B/C parity/performance 报告。",
      "policy service 故障日志、shadow 报告、分级真机 go/no-go 与回退方案。",
      "correction/后训练实验卡和未污染的冻结回归结果。",
    ],
    verifiedBoundary: "已确认的是公开 openpi/Thor 文档和本站契约 Toy；你的实际机器人 DOF、底盘运动学、Thor SKU/系统、延迟、模型效果和真机安全均未在本站验证，必须由 22 步的现场证据填充。",
    knowledgeCheck: [
      { question: "有 Thor 为什么仍不能直接承诺 π₀.₅ 实时？", answer: "端到端性能还取决于 SKU/内存、JetPack/CUDA、ARM64 框架兼容、模型精度、预处理、功耗/散热和通信；必须实测同一请求边界 p99。" },
      { question: "openpi 默认移动本体统计为什么不能直接套你的机器人？", answer: "你的腰部和底盘语义未必匹配公开 action slices；padding 只对齐形状，不对齐 DOF、frame、unit、command type 或统计分布。" },
      { question: "Thor 原生不通时正确回退是什么？", answer: "保持 action contract 不变，先用工作站策略服务+Thor 客户端路径 C；一次只处理环境兼容，不同时改模型、精度和控制接口。" },
      { question: "何时可以让模型动作接触硬件？", answer: "完成数据/replay/adapter/一批过拟合/离线评测/服务故障注入和 shadow，且独立急停、限速、碰撞、接管与现场审批全部通过后，才进入低速单子系统灰度。" },
      { question: "π0.6 为什么只作为检查点？", answer: "截至教程审校日，官方研究报告存在，但本站未在 openpi 主线确认与 π₀.₅ 同等完整的公开 checkpoint/config/deploy 路线；只有实际拥有并固定全链路后才可替换。" },
      { question: "后训练第一选择一定是 RL 吗？", answer: "不是。对全身机器人通常先修 pipeline、采 correction/recovery 并 SFT/DAgger；只有非零基础能力、可靠 reward、安全 rollout 与回退齐备才考虑 RL。" },
    ],
  },
} satisfies Record<string, LessonWalkthrough>;
