import type { OpenCourse } from "@/lib/openCourseTypes";

const course = "https://cs336.stanford.edu/";
const lectures = "https://github.com/stanford-cs336/lectures";
const playlist = "https://www.youtube.com/playlist?list=PLoROMvodv4rMqXOcazWaTUHhq-yembLCV";

const video = (id: string, title: string) => ({
  title: `CS336 2026 视频：${title}`,
  url: `https://www.youtube.com/watch?v=${id}&list=PLoROMvodv4rMqXOcazWaTUHhq-yembLCV`,
  kind: "video" as const,
  note: "Stanford Online 官方录像；本章将课堂中的动机、口头例子和工程判断融入讲解。",
});

const script = (index: string, title: string) => ({
  title: `Lecture ${Number(index)} 可执行课件：${title}`,
  url: `${lectures}/blob/main/lecture_${index}.py`,
  kind: "code" as const,
  note: "Spring 2026 官方 executable lecture；链接到原始代码，不在本站复制。",
});

const slides = (index: string, title: string) => ({
  title: `Lecture ${Number(index)} Slides：${title}`,
  url: `${lectures}/blob/main/lecture_${index}.pdf`,
  kind: "slides" as const,
  note: "Spring 2026 官方 PDF；本站按其论证顺序讲解，不逐页翻译。",
});

const assignment = (index: number, title: string, file: string) => ({
  title: `Assignment ${index}：${title}`,
  url: `https://github.com/stanford-cs336/assignment${index}-${file}`,
  kind: "assignment" as const,
  note: index < 5
    ? "官方 handout、starter code 与 tests，仓库标注 MIT License；请遵守课程 Honor Code，独立完成 TODO。"
    : "官方 handout、starter code 与 tests；仓库未发现许可证文件，只链接参考，勿复制或发布作业答案。",
});

export const cs336Course = {
  slug: "cs336",
  title: "Stanford CS336：从零构建语言模型",
  shortTitle: "CS336",
  provider: "Stanford University · Spring 2026",
  sourceUrl: course,
  description:
    "沿着 CS336 Spring 2026 的原始课序，从字节、BPE 和 Transformer 一直走到 GPU 内核、并行训练、扩展律、数据治理与推理强化。中文讲解用于串起官方 slides、可执行讲义、YouTube 课堂说明和 assignments；重要例子与代码边界均回链原材料。",
  provenance:
    "章节依照官方 Spring 2026 schedule 整理。公式、符号和案例尽量沿用课程；中文正文为重新组织的讲解，并明确链接到每讲视频、slides/lecture code 与作业。独立实验只复现教学机制，不实现官方作业 TODO，也不提供 solution。",
  licenseNote:
    "课程网页、lecture 仓库与视频未见统一开放内容许可证，Assignment 5 仓库也未发现 LICENSE，因此只做必要引用、中文转述和远程来源链接；官方图不重新上传，官方 lecture code 不复制。Assignment 1–4 仓库的 LICENSE 标注 MIT，但 Stanford Honor Code 与课程 AI policy 仍适用于正在修读课程的学生。",
  prerequisites: [
    "熟练使用 Python；官方提醒本课代码量显著高于一般 AI 课程",
    "会用 PyTorch，并理解反向传播、矩阵乘法和基本训练循环",
    "线性代数、微积分、概率统计与机器学习基础",
    "了解缓存、显存与并行等系统概念；GPU 不是本站缩小实验的必需条件",
  ],
  outcomes: [
    "从原始文本训练 tokenizer，并把 token 序列接到自回归 Transformer",
    "用 FLOPs、字节数、算术强度与 MFU 分析训练和推理瓶颈",
    "解释现代 Transformer、注意力替代、MoE、并行与推理系统的核心取舍",
    "拟合并审查 scaling law，构造可复现的 evaluation 与 data pipeline",
    "区分 SFT、偏好优化、RLHF、RLVR，并理解多模态输入如何进入语言模型",
  ],
  coverage: [
    { source: "Lecture 1 · Overview, Tokenization", mappedTo: "第 1 章", note: "official executable lecture + video + A1" },
    { source: "Lecture 2 · PyTorch, einops, resource accounting", mappedTo: "第 2 章", note: "official executable lecture + video + A1" },
    { source: "Lecture 3 · Architectures, hyperparameters", mappedTo: "第 3 章", note: "official slides + video + A1" },
    { source: "Lecture 4 · Attention alternatives and MoE", mappedTo: "第 4 章", note: "official slides + video" },
    { source: "Lecture 5 · GPUs, TPUs", mappedTo: "第 5 章", note: "official slides + video + A2" },
    { source: "Lecture 6 · Kernels, Triton, XLA", mappedTo: "第 6 章", note: "official executable lecture + video + A2" },
    { source: "Lecture 7 · Parallelism", mappedTo: "第 7 章", note: "official executable lecture + video + A2" },
    { source: "Lecture 8 · Parallelism", mappedTo: "第 7 章", note: "official slides + video + A2" },
    { source: "Lecture 9 · Scaling laws", mappedTo: "第 8 章", note: "official slides + video + A3" },
    { source: "Lecture 10 · Inference", mappedTo: "第 9 章", note: "official executable lecture + video + A2" },
    { source: "Lecture 11 · Scaling laws", mappedTo: "第 8 章", note: "official slides + video + A3" },
    { source: "Lecture 12 · Evaluation", mappedTo: "第 10 章", note: "official executable lecture + video + A3/A4 handoff" },
    { source: "Lecture 13 · Data: sources, datasets", mappedTo: "第 11 章", note: "official executable lecture + video + A4" },
    { source: "Lecture 14 · Data pipeline", mappedTo: "第 12 章", note: "official executable lecture + video + A4" },
    { source: "Lecture 15 · Mid/post-training", mappedTo: "第 13 章", note: "official slides + video + A5" },
    { source: "Lecture 16 · RLVR", mappedTo: "第 14 章", note: "official slides + video + A5" },
    { source: "Lecture 17 · Multimodality", mappedTo: "第 15 章", note: "official executable lecture + video" },
    { source: "Lecture 18 · Guest lecture: Daniel Selsam", mappedTo: "第 15 章", note: "官方 schedule 有列项，但截至核对时未提供公开 slides/录像；本站不虚构内容" },
    { source: "Lecture 19 · Guest lecture: Dan Fu", mappedTo: "第 9 章", note: "官方 playlist 录像作为推理系统延伸：continuous batching、KV cache、megakernel 与循环架构" },
    { source: "Assignment 1 · Basics", mappedTo: "第 1–3 章", note: "tokenizer、model、optimizer、training" },
    { source: "Assignment 2 · Systems", mappedTo: "第 2、5–7 章", note: "mixed precision、profiling、FlashAttention2、distributed training" },
    { source: "Assignment 3 · Scaling", mappedTo: "第 3、8 章", note: "Transformer component review、training API、scaling law 与预测" },
    { source: "Assignment 4 · Data", mappedTo: "第 10–12 章", note: "Common Crawl、filter、dedup 与 evaluation" },
    { source: "Assignment 5 · Alignment and Reasoning RL", mappedTo: "第 13–14 章", note: "SFT、GRPO/RLVR；optional safety/DPO" },
  ],
  chapters: [
    {
      slug: "overview-tokenization",
      index: 1,
      title: "总览与 Tokenization",
      subtitle: "Lecture 1：先把字符串变成模型能计算、又能无损还原的整数序列",
      duration: "3–4 小时",
      summary:
        "课程从 tokenizer 开始并不是因为它最简单，而是因为它同时决定序列长度、词表矩阵大小、跨语言公平性和训练吞吐。先建立 UTF-8 字节视角，再手算一次 BPE 合并。",
      objectives: [
        "区分 Unicode code point、UTF-8 byte 与 token id",
        "解释 byte-level BPE 的训练和编码为什么是两个阶段",
        "验证 round trip，并分析词表大小与序列长度的折中",
      ],
      prerequisites: ["Python 字符串与 bytes", "频数统计"],
      concepts: [
        {
          name: "可逆 tokenizer",
          explanation: "tokenizer 是 encode: string → ids 与 decode: ids → string 的一对变换。最基本的不变量是 decode(encode(x)) = x；模型是否理解文本是后话。",
          why: "语言模型只接收整数索引。若预处理不能还原原文，训练目标就悄悄换成了另一个数据分布。",
          example: "“你好”有两个 Unicode 字符，但 UTF-8 编码占 6 个字节；byte tokenizer 会先得到 6 个基本符号。",
          boundary: "可逆不等于高效。纯字节方案永不 OOV，却会把常见词切得很长。",
        },
        {
          name: "UTF-8 字节词表",
          explanation: "以 0–255 的字节作为保底词表，任何合法 UTF-8 文本都能表示；BPE 只在这些基本符号之上添加合并 token。",
          why: "若直接以 Unicode 字符建词表，字符空间很大且训练语料仍可能遗漏字符。",
          example: "英文 a 是单字节 0x61；中文“你”对应三个字节 E4 BD A0，但常见组合可被 BPE 合成一个较长 token。",
          boundary: "切分发生在字节层时，中间 token 不一定能单独解码成人类可读字符。",
        },
        {
          name: "BPE 合并",
          explanation: "反复统计相邻 token 对，选择最高频的一对，把它登记为新 token，再更新语料表示，直到达到目标词表大小。",
          why: "它用数据驱动方式给常见片段短编码，同时让罕见字符串退回字节。",
          example: "语料 aaabdaaabac 中若 (a,a) 最常见，先合成 aa；下一轮频数必须基于更新后的序列重算。",
          boundary: "训练得到的是有顺序的 merge rules。编码新文本时不能只看最终词表随意做最长匹配。",
        },
        {
          name: "压缩率与公平性",
          explanation: "同一句语义被切成多少 token，决定模型看到的有效上下文和需要支付的计算量。不同语言的 token/字符比可能不同。",
          why: "上下文窗口按 token 计费；切分更碎的语言在相同窗口内能放入的信息更少。",
          example: "若英文句子是 8 token、等义中文句子是 14 token，那么固定 4096-token 窗口对二者覆盖的段落长度不同。",
          boundary: "平均压缩率不能单独代表 tokenizer 质量；还要检查代码、数字、特殊 token 和训练域外文本。",
        },
      ],
      sections: [
        {
          title: "1. 从原始文本到下一个 token 目标",
          intuition: "模型无法直接对字符串做矩阵乘法；tokenizer 是数据和网络之间的接口契约。",
          paragraphs: [
            "给定文本 x，tokenizer 产生整数序列 t₁,…,tₙ。训练样本随后平移一位：输入是 t₁,…,tₙ₋₁，标签是 t₂,…,tₙ。Lecture 1 的课程地图正是 tokenizer → architecture → training，而不是把 tokenizer 当作无关紧要的工具。",
            "课堂口头讲解把这门课与只调用 API 的路线区分开：接口会变化，但从数据表示、资源计数到训练失败的判断可以迁移。对 tokenizer 而言，第一项可迁移能力就是写断言检查 round trip、特殊 token 冲突和边界输入。",
          ],
          formula: {
            latex: "t_{1:n}=\\operatorname{encode}(x),\\qquad x=\\operatorname{decode}(t_{1:n})",
            explanation: "第二个等式是应被测试的不变量，不是语言模型的学习目标。",
            symbols: [
              { symbol: "x", meaning: "原始字符串" },
              { symbol: "t_i", meaning: "第 i 个 token id" },
              { symbol: "n", meaning: "编码后的序列长度" },
            ],
          },
          checks: ["空串能否往返？", "包含 emoji、换行和无效边界时是否有明确行为？"],
        },
        {
          title: "2. 手算 BPE：训练规则，不是背词表",
          intuition: "每一次 merge 都是在当前语料表示上重新定义一个常见块。",
          paragraphs: [
            "把预分词后的词按 UTF-8 bytes 展开，并统计每个相邻对的频数。选中频数最高的一对 (u,v)，分配新 id w，按从左到右、不重叠的方式把 u,v 替换为 w。随后重新统计；旧频数已经失效。",
            "实际实现的困难不在三行伪代码，而在规模：不能每轮扫描全部语料；并列频数要有确定规则；特殊 token 应在普通分词之前被识别；并行预分词不能把一个文档边界误连到另一个文档。官方 A1 用 tests 把这些工程不变量暴露出来。",
          ],
          example: {
            title: "两轮合并",
            steps: [
              "初始序列 [a,a,a,b,a,a,a,b]；(a,a) 出现 4 次，但不重叠替换后得到 [aa,a,b,aa,a,b]。",
              "重新计数，(aa,a) 和 (a,b) 都出现 2 次；按约定的 tie-break 选择一个。",
              "若选择 (aa,a)→aaa，则新序列为 [aaa,b,aaa,b]；编码新文本必须按 merge rank 重放规则。",
            ],
            result: "BPE 的输出不仅是 token→bytes 的词表，还包括有先后顺序的 merges。",
          },
          checks: ["重叠 pair 如何替换？", "频数相同时结果是否可复现？"],
        },
        {
          title: "3. 评估 tokenizer，不只看词表大小",
          intuition: "词表变大缩短序列，却同时增大 embedding 和输出 softmax。",
          paragraphs: [
            "设隐藏维度 d、词表 V。若输入输出权重共享，token embedding 约有 Vd 个参数；不共享时通常接近 2Vd。词表变大还会增加输出 logits 的计算，而序列变短会降低注意力和逐 token 的计算，因此不存在脱离数据与模型的最佳 V。",
            "至少报告 bytes/token 或 characters/token 的分布，而非一个总平均数；分别检查主要语言、代码、数字和域外语料。还要固定 normalization 与 pre-tokenization，否则两次实验比较的并非同一个算法。",
          ],
          formula: {
            latex: "r_{byte}=\\frac{\\text{UTF-8 bytes}}{\\text{tokens}},\\qquad P_{embed}=Vd",
            explanation: "较大的 r_byte 表示每个 token 平均承载更多字节，但不能说明语义质量。",
            symbols: [
              { symbol: "V", meaning: "词表大小" },
              { symbol: "d", meaning: "模型隐藏维度" },
              { symbol: "P_embed", meaning: "共享 embedding 的参数量" },
            ],
          },
          checks: ["跨语言压缩率是否分别报告？", "特殊 token 是否可能出现在普通文本中？"],
        },
      ],
      lab: {
        title: "实验：在小语料上训练并验证 byte-level BPE",
        goal: "亲手看到 pair 频数、merge 顺序、压缩率和 round trip 之间的关系。",
        file: "/labs/cs336/toy_bpe.py",
        steps: ["运行脚本观察每轮 merge", "修改中英混合语料", "增加词表预算并比较 bytes/token"],
        expected: ["所有样本 decode(encode(x)) == x", "合并次数增加时训练语料 token 数不增加", "终端输出 PASS"],
        sourceNote: "对应 Lecture 1 和 Assignment 1 的 tokenizer 单元；本站代码是独立小例，不实现作业接口。",
      },
      recordings: [{ title: "Lecture 1 · Overview, Tokenization", youtubeId: "JuoVZkPBiKk", note: "课堂先给完整训练栈和五项作业地图，再从 Unicode、UTF-8 走到 BPE。" }],
      pitfalls: [
        "把 Unicode 字符数当成 UTF-8 字节数",
        "训练时合并最频繁 pair，编码时却改用无 rank 的贪心最长匹配",
        "只在英文新闻上测压缩率便宣称 tokenizer 普适",
      ],
      exercises: [
        { question: "为什么 byte tokenizer 没有未知词？", answer: "任意 UTF-8 字符串最终都是 0–255 的字节序列，因此基本词表总能表示；这不保证序列短。" },
        { question: "词表扩大一倍，训练一定更快吗？", answer: "不一定。序列可能缩短，但 embedding/输出矩阵变大；效果取决于数据切分、隐藏维度与硬件瓶颈。" },
      ],
      sources: [
        { title: "CS336 Spring 2026 官方课程与 schedule", url: course, kind: "course" },
        script("01", "Overview, tokenization"),
        video("JuoVZkPBiKk", "Lecture 1 · Overview, Tokenization"),
        assignment(1, "Basics", "basics"),
      ],
    },
    {
      slug: "tensors-resource-accounting",
      index: 2,
      title: "PyTorch、张量与资源账本",
      subtitle: "Lecture 2：用 shape、dtype、FLOPs 和 bytes 解释一次训练到底花在哪里",
      duration: "4 小时",
      summary: "先把张量变换写成可核对的轴，再分别计算计算量与内存流量。课程反复强调：FLOPs 不是运行时间；roofline 判断的是瓶颈属于算力还是带宽。",
      objectives: ["用 shape 推导 einops 变换", "计算参数、激活和优化器状态内存", "用算术强度和 MFU 解释性能"],
      prerequisites: ["矩阵乘法", "浮点数与字节"],
      concepts: [
        { name: "Shape 契约", explanation: "每个轴都有语义，例如 batch、sequence、head、head dimension；重排前后元素总数必须守恒。", why: "许多注意力 bug 不报错，只是把两个同尺寸轴弄反。", example: "[B,S,H,D] 转为 [B,H,S,D] 只换轴，不改变 BSHD 个元素。", boundary: "shape 正确仍可能语义错误；必须给轴命名或用小值追踪。" },
        { name: "dtype 与数值范围", explanation: "fp32、fp16、bf16 在存储、有效位和指数范围上不同；混合精度把不同计算分配给适合的格式。", why: "低精度减少内存和提高 tensor core 吞吐，但小梯度可能下溢。", example: "同一亿个元素，fp32 约 400 MB，bf16 约 200 MB。", boundary: "把权重存成 bf16 不代表累加、master weight 和 optimizer state 都是 bf16。" },
        { name: "算术强度", explanation: "arithmetic intensity 是执行的 FLOPs 除以从慢层级搬运的 bytes。", why: "它把算法放到 roofline 上，判断优化应减少搬运还是增加计算利用率。", example: "逐元素激活每个元素做少量运算却至少读写一次，常是 memory-bound。", boundary: "必须说明 bytes 是相对 HBM、缓存还是网络；不同边界会得到不同强度。" },
        { name: "MFU", explanation: "Model FLOPs Utilization 用模型理论 FLOPs/秒除以设备峰值 FLOPs/秒。", why: "它把训练吞吐换算成跨 batch、模型和机器更可比较的利用率。", example: "每步 2e14 FLOPs、0.2 s/步，设备峰值 2e15 FLOP/s，则 MFU=50%。", boundary: "MFU 依赖 FLOPs 口径和峰值精度规格；高 MFU 不自动代表端到端成本最低。" },
      ],
      sections: [
        { title: "1. 先写轴，再写算子", intuition: "张量代码的可读性来自轴的语义，而不是短。", paragraphs: ["Lecture 2 用 B、S、H、D 明确 batch、序列、头数和头维。把 hidden 拆成 heads×head_dim 时，先验证 d_model=H·D，再 reshape 和 transpose；不要依赖记忆猜 permute 顺序。", "einsum/einops 的价值是把变换意图写进表达式。调试时用 arange 构造每个位置都不同的张量，比随机数更容易发现轴交换。"], example: { title: "注意力投影的 shape", steps: ["输入 x:[B,S,d] 与 Wq:[d,H·D] 相乘得到 [B,S,H·D]。", "重排为 q:[B,H,S,D]，同样得到 k、v。", "q @ kᵀ 在最后两轴相乘，score:[B,H,S,S]。"], result: "每一步都能从轴名检查，不需要盲猜广播。" }, checks: ["元素总数是否守恒？", "softmax 是沿 key 轴而不是 query 轴吗？"] },
        { title: "2. 内存账本必须区分四类对象", intuition: "参数只是显存的一部分；一句 M_act∝BSLd 只够描述残差流，不能代表完整 Transformer。", paragraphs: ["训练显存至少包括参数、梯度、优化器状态和为反向传播保留的激活。Adam 常为每个参数维护一阶矩和二阶矩；若还有 fp32 master weights，不能只用参数量×2 bytes 估算。", "残差流一类激活约随 BSLd 增长，MLP 中间量约为 BSLd_ff；朴素 attention 若保存每层每头的 score/probability，还会出现 BHLS² 项。FlashAttention 或重算能避免保存完整 S² 中间量，但这属于实现选择，不能从总账中静默删掉。gradient checkpointing 用重算换保存空间，不会减少数学上所需的反向传播。"], formula: { latex: "M_{static}=P(b_w+b_g+b_m+b_v),\\quad M_{res}\\sim BSLd,\\quad M_{mlp}\\sim BSLd_{ff},\\quad M_{attn}\\sim BHLS^2", explanation: "后三项分别给出残差类、MLP 中间量和朴素 attention score 的元素数量级；实际峰值取决于保存策略、dtype 与 fusion。", symbols: [{ symbol: "P", meaning: "参数个数" }, { symbol: "b_w,b_g,b_m,b_v", meaning: "权重、梯度和 Adam 两个状态的每参数字节" }, { symbol: "B,S,L,d,H", meaning: "batch、序列、层数、隐藏维与头数" }, { symbol: "d_ff", meaning: "MLP 中间维度" }] }, checks: ["是否计入 optimizer state？", "是否把朴素 attention 的 S² 中间量误算成线性？", "峰值是否包含暂存张量？"] },
        { title: "3. Roofline：FLOPs 不是秒", intuition: "设备只有在算子提供足够多可复用计算时才能吃满算力。", paragraphs: ["设峰值计算 C_peak、内存带宽 BW、算术强度 I。可达性能上界是 min(C_peak, BW·I)。若 BW·I 更小，继续减少 FLOPs 可能毫无作用，减少 HBM 往返、融合算子或增大复用更有效。", "视频课堂从逐元素 GELU、向量点积到矩阵乘法逐步比较 bytes 与 FLOPs，目的不是记一个常数，而是建立先计数再优化的习惯。测量还要 warm-up、同步异步设备并报告方差。"], formula: { latex: "C_{attainable}\\leq\\min(C_{peak}, BW\\cdot I),\\qquad I=FLOPs/bytes", explanation: "I 小时受带宽限制，I 足够大后转为 compute-bound。", symbols: [{ symbol: "BW", meaning: "所选内存层级的带宽" }, { symbol: "I", meaning: "算术强度" }, { symbol: "C_peak", meaning: "相应精度下峰值计算率" }] }, checks: ["计数边界是 HBM 还是 cache？", "计时前是否同步设备？"] },
      ],
      lab: { title: "实验：Transformer 资源账本", goal: "对一个小模型计算参数、训练静态内存、激活量、FLOPs 与 roofline 上界。", file: "/labs/cs336/resource_accounting.py", steps: ["运行默认配置", "把序列长度加倍", "比较逐元素算子与矩阵乘法的强度"], expected: ["shape 断言通过", "序列加倍时 attention score 元素约变 4 倍", "输出 PASS"], sourceNote: "对应 Lecture 2 的 executable lecture；使用纯算术独立实现。" },
      recordings: [{ title: "Lecture 2 · PyTorch (einops)", youtubeId: "kuYAsz7zspQ", note: "课堂用具体张量和硬件数字区分 shape、memory accounting、FLOPs、arithmetic intensity 与 MFU。" }],
      pitfalls: ["把硬件宣传页的稀疏峰值用于稠密训练", "只计算参数显存", "用 CPU 墙钟时间测异步 GPU kernel"],
      exercises: [
        { question: "为什么算子 FLOPs 更少却可能更慢？", answer: "它可能需要更多内存往返或启动开销，处在 bandwidth-bound 区域；FLOPs 不是完整成本模型。" },
        { question: "bf16 相比 fp16 的主要数值差异是什么？", answer: "bf16 保留接近 fp32 的指数范围但尾数更短，较不易因范围不足而上下溢；精度仍需管理。" },
      ],
      sources: [script("02", "PyTorch, einops, resource accounting"), video("kuYAsz7zspQ", "Lecture 2 · PyTorch (einops)"), assignment(1, "Basics", "basics")],
    },
    {
      slug: "transformer-architecture",
      index: 3,
      title: "现代 Transformer 架构与训练目标",
      subtitle: "Lecture 3：从 original Transformer 走到 pre-norm、RMSNorm、RoPE 与 SwiGLU",
      duration: "4–5 小时",
      summary: "这讲的核心不是收集架构名词，而是辨认稳定的骨架、可替换的部件和证据强弱。最终把 token embedding、causal attention、MLP、残差和 next-token NLL 串成一个可训练模型。",
      objectives: ["逐层追踪 decoder-only Transformer", "推导 causal NLL", "解释 pre-norm、RMSNorm、RoPE、SwiGLU 的作用与边界"],
      prerequisites: ["第 1–2 章", "softmax 与交叉熵"],
      concepts: [
        { name: "Decoder-only 自回归", explanation: "模型在位置 t 只用 t 之前的 token，输出下一个 token 的条件分布。整段训练可并行，生成仍逐 token。", why: "它把文本联合概率分解成一串可监督的分类问题。", example: "输入“北京 是”，当前位置的标签是“中”；mask 禁止读取标签右侧。", boundary: "causal mask 防未来泄漏，但 padding mask、文档边界和 loss mask 仍需单独处理。" },
        { name: "Pre-norm 残差块", explanation: "先对输入归一化再进入 attention/MLP，子层输出加回主残差流。", why: "主残差路径保持直接的恒等通路，深网络优化通常更稳定。", example: "h'=h+Attn(RMSNorm(h)); h''=h'+MLP(RMSNorm(h'))。", boundary: "pre-norm 是常见稳健默认，不代表所有深度和初始化下都最优。" },
        { name: "RoPE", explanation: "按位置旋转 query/key 的二维通道，使点积携带相对位置信息。", why: "attention 本身对 token 排列没有位置感，RoPE 将相对位移编码进 q·k。", example: "同一向量在位置 m、n 旋转不同角度，内积依赖角度差 m−n。", boundary: "RoPE 外推到远超训练长度时并非自动可靠，常需频率缩放或再训练。" },
        { name: "SwiGLU", explanation: "两路线性投影中一路过 SiLU 门控，再与另一路逐元素相乘并投回隐藏维。", why: "门控让 FFN 可选择性传递特征，现代 LLM 中常比 ReLU FFN 表现好。", example: "FFN(x)=W₂[SiLU(W_gx)⊙(W_ux)]。", boundary: "比较参数量时要调整中间维度；不能用同一个 d_ff 直接声称公平。" },
        { name: "AdamW 与学习率计划", explanation: "Adam 用梯度一、二阶滑动矩给每个参数自适应步长；AdamW 将 weight decay 与梯度更新解耦。", why: "大模型梯度尺度跨参数不同，warmup、峰值学习率、decay 和 clipping 共同决定训练是否稳定。", example: "训练初期从接近 0 的学习率线性 warmup，随后 cosine 或 WSD 衰减；global grad norm 超阈值时统一缩放。", boundary: "优化器超参数会随参数化、batch 和 scale 改变；从小模型复制并非无条件安全。" },
      ],
      sections: [
        { title: "1. 一条 token 如何穿过网络", intuition: "Transformer 不是 attention 的同义词，而是 embedding、两类残差子层和输出头的组合。", paragraphs: ["token ids 先查表得到 [B,S,d]。每层先做 causal self-attention，让位置在过去上下文间读写；再做逐位置 MLP，扩展并压回通道。残差连接保留旧表示，norm 控制尺度。最后把每个位置投到 V 维 logits。", "Lecture 3 先对比 2017 原版与 A1 要实现的简单现代变体：post-norm→pre-norm、sinusoidal position→RoPE、ReLU→SwiGLU、LayerNorm→RMSNorm，并去掉多数 bias。课堂强调这些选择很大程度来自跨模型经验，不应包装成唯一理论结论。"], checks: ["每层输入输出是否都是 [B,S,d]？", "attention 与 MLP 都有各自残差吗？"] },
        { title: "2. Causal attention 与尺度", intuition: "每个 query 在许可的 key 中做一次内容寻址。", paragraphs: ["把 x 投影成 Q、K、V，score=QKᵀ/√d_h。除以 √d_h 是为了避免独立分量累加后方差随维度变大，使 softmax 过早饱和。因果位置 j>i 的 score 设为 −∞，softmax 后权重为 0。", "多头不是把同一个注意力复制 H 次，而是让不同投影子空间分别读信息，再拼接并投影。实现时 mask 必须在 softmax 前施加，且需处理全 mask 行避免 NaN。"], formula: { latex: "\\operatorname{Attn}(Q,K,V)=\\operatorname{softmax}(QK^\\top/\\sqrt{d_h}+M)V", explanation: "M_{ij}=−∞ 表示 query i 不允许访问 key j。", symbols: [{ symbol: "d_h", meaning: "单头维度" }, { symbol: "M", meaning: "因果/有效位掩码" }, { symbol: "Q,K,V", meaning: "查询、键和值" }] }, checks: ["softmax 沿最后的 key 维吗？", "训练标签是否平移一位？"] },
        { title: "3. NLL 把所有位置连成训练信号", intuition: "teacher forcing 让一段长度 S 的文本同时提供 S−1 个监督位置。", paragraphs: ["给定前缀 t_<i，模型产生 logits z_i，softmax 得到 pθ(t_i|t_<i)。最小化正确 token 的负对数概率，等价于最小化经验数据分布与模型分布的交叉熵。padding、文档拼接边界或 prompt token 是否计入 loss，必须由明确 mask 决定。", "perplexity=exp(平均 NLL) 可解释为模型平均有效分支数，但只可在相同 tokenizer、相同数据预处理和相同 token 口径下比较。不同 tokenizer 的 token-level perplexity 不能直接排榜。"], formula: { latex: "\\mathcal L(\\theta)=-\\frac{1}{N}\\sum_{i=1}^{N}\\log p_\\theta(t_i\\mid t_{<i}),\\qquad PPL=e^{\\mathcal L}", explanation: "N 是实际参与 loss 的 token 数，不应把被 mask 的 padding 算入分母。", symbols: [{ symbol: "p_θ", meaning: "模型条件分布" }, { symbol: "t_<i", meaning: "位置 i 前的可见前缀" }, { symbol: "PPL", meaning: "perplexity" }] }, checks: ["loss 分母是否只计有效标签？", "比较 PPL 时 tokenizer 是否相同？"] },
        { title: "4. 从梯度到 AdamW 更新", intuition: "loss 定义学什么，optimizer 和 schedule 决定能否稳定学到。", paragraphs: ["反向传播得到 g_t。Adam 对一阶矩 m_t 和二阶矩 v_t 做指数滑动平均并做 bias correction，再按 m̂/(√v̂+ε) 更新；AdamW 另做与梯度解耦的参数衰减。通常不对 norm/bias 参数施加 weight decay，具体分组要写进配置。", "学习率 warmup 避免早期未校准矩估计和激活尺度造成大更新，随后 decay 帮助收敛。gradient clipping 以 global norm 统一缩放，不应逐元素随意截断。A1 要求亲手实现 optimizer 和 training loop，本站只给公式与检查点。"], formula: { latex: "m_t=\\beta_1m_{t-1}+(1-\\beta_1)g_t,\\quad v_t=\\beta_2v_{t-1}+(1-\\beta_2)g_t^2,\\quad \\theta_{t+1}=(1-\\eta_t\\lambda)\\theta_t-\\eta_t\\frac{\\hat m_t}{\\sqrt{\\hat v_t}+\\epsilon}", explanation: "第一项是 decoupled weight decay，第二项是 bias-corrected Adam 更新。", symbols: [{ symbol: "g_t", meaning: "当前梯度" }, { symbol: "β₁,β₂", meaning: "矩估计衰减系数" }, { symbol: "η_t", meaning: "当前学习率" }, { symbol: "λ", meaning: "weight decay 系数" }] }, checks: ["step 从 0/1 开始是否影响 bias correction？", "clip 发生在 optimizer update 之前吗？"] },
      ],
      lab: { title: "实验：手算 causal attention 与 NLL", goal: "用极小矩阵验证 mask、softmax、残差 shape 和 shifted labels。", file: "/labs/cs336/causal_lm_math.py", steps: ["运行 3-token 注意力", "观察未来 token 权重为 0", "核对均匀 logits 的 NLL=log V"], expected: ["每行有效权重和为 1", "未来位置权重为 0", "输出 PASS"], sourceNote: "对应 Lecture 3 与 Assignment 1 的模型单元；本站实验只做数值机制。" },
      recordings: [{ title: "Lecture 3 · Architectures", youtubeId: "lVynu4bo1rY", note: "课堂把架构选择当成需要实验和公开配方佐证的工程判断，而非单一理论定理。" }],
      pitfalls: ["将 residual stream 的维度与 head dimension 混为一谈", "先 softmax 再清零未来权重", "跨 tokenizer 直接比较 perplexity"],
      exercises: [
        { question: "为什么训练能并行而生成通常不能？", answer: "训练已知整段真实前缀，可一次计算所有位置；生成的下一个输入依赖刚采样出的 token。" },
        { question: "RMSNorm 与 LayerNorm 的直接区别？", answer: "RMSNorm 按均方根缩放，不减去均值；常见实现也没有 bias。" },
      ],
      sources: [slides("03", "Architectures, hyperparameters"), video("lVynu4bo1rY", "Lecture 3 · Architectures"), assignment(1, "Basics", "basics")],
    },
    {
      slug: "attention-alternatives-moe",
      index: 4,
      title: "Attention 替代与 Mixture of Experts",
      subtitle: "Lecture 4：长上下文成本、线性/混合注意力与稀疏激活参数",
      duration: "4 小时",
      summary: "标准 attention 的序列二次成本推动了局部、线性、状态空间和稀疏注意力；MoE 则在近似固定 token FLOPs 下增加总参数。两类方法都把算法优势转化成了新的系统复杂度。",
      objectives: ["推导 Q(KᵀV) 的线性序列成本", "解释 recurrent state 与并行训练的 duality", "手算 top-k MoE routing 与 capacity"],
      prerequisites: ["标准 attention", "矩阵结合律"],
      concepts: [
        { name: "二次 attention", explanation: "长度 n 的 QKᵀ 形成 n×n 分数矩阵，计算与中间存储随 n² 增长。", why: "长上下文时它可能成为训练成本与显存核心。", example: "序列从 4k 加倍到 8k，score 元素数约变为 4 倍。", boundary: "FlashAttention 可减少 HBM I/O 和显存，但不会把数学 FLOPs 从 n² 变线性。" },
        { name: "线性 attention duality", explanation: "在合适核/无 softmax 简化下，用结合律把 (QKᵀ)V 改成 Q(KᵀV)，并能写成递归状态更新。", why: "训练可批量并行，逐 token 推理可维护固定大小状态。", example: "S_t=S_{t−1}+k_tv_tᵀ，y_t=q_tᵀS_t。", boundary: "标准 softmax attention 不能直接无损交换括号；线性化改变了函数族。" },
        { name: "混合注意力", explanation: "在多层中组合线性/局部层与少量完整 attention 层。", why: "线性层负责低成本长程状态，完整层补足精确 token-token 检索。", example: "每 8 层安排 1 层 full attention，其余使用线性更新。", boundary: "层比例是经验超参数；长上下文吞吐提升不保证所有检索任务等价。" },
        { name: "Top-k MoE", explanation: "router 为每个 token 选择少数专家 MLP，仅计算被选中的专家。", why: "总参数容量可随专家数增长，而每 token 激活参数由 k 控制。", example: "8 个专家、top-2 时，一个 token 只经过两个专家，再按 router 权重合并。", boundary: "总参数、激活参数、通信量是三个不同指标；负载不均会丢 token 或拖慢所有设备。" },
      ],
      sections: [
        { title: "1. 从矩阵结合律到 recurrent state", intuition: "避免显式 n×n 矩阵的代价，是改变归一化或 attention 形式。", paragraphs: ["若 ρ 是恒等映射，QKᵀV 可按 Q(KᵀV) 计算。前者主要随 n²d 增长，后者先汇总 d_k×d_v 状态，主要随 nd_kd_v 增长。自回归时只需把 k_tv_tᵀ 加进状态。", "Lecture 4 继续加入遗忘门 γ_t、输入门 β_t 与定向擦除，从线性 attention 过渡到 Mamba-2、gated delta net 等思路。重要的是看见机制：固定状态换来线性推理，但状态压缩可能遗失精细历史。"], formula: { latex: "S_t=\\gamma_tS_{t-1}+k_tv_t^\\top,\\qquad y_t=q_t^\\top S_t", explanation: "γ_t 控制旧状态保留，外积写入当前 key-value 关联。", symbols: [{ symbol: "S_t", meaning: "截至 t 的压缩状态" }, { symbol: "γ_t", meaning: "遗忘/衰减门" }, { symbol: "q_t,k_t,v_t", meaning: "当前位置的 query、key、value" }] }, checks: ["是否保留 softmax？若没有，函数已改变。", "状态维度是否独立于序列长度？"] },
        { title: "2. Sparse 与 hybrid 是不同的折中", intuition: "可以少看 token，也可以把历史压进状态；两者信息丢失方式不同。", paragraphs: ["local/sliding-window attention 只连最近 w 个位置，成本 O(nw)；稀疏索引器挑选少量远程 token；hybrid 模型间隔插入 full attention。它们都需要为检索能力、吞吐和实现成熟度分别测量。", "课件用 2026 年出现的混合架构说明趋势，但模型发布日期和榜单会快速变化；本站保留机制层结论，不把某个模型的短期领先当定律。"], example: { title: "长文中的远程定义", steps: ["局部窗口只保留最近 512 token，开头定义可能离开窗口。", "稀疏索引器若命中定义，可直接读取；若漏检就无法恢复。", "每隔若干层的 full attention 能传播信息，但仍需实测有效上下文。"], result: "复杂度下降并不等于任务无损，评估集必须包含长程依赖。" }, checks: ["评估是否真的需要远程精确复制？", "报告的是 theoretical 还是 measured speedup？"] },
        { title: "3. MoE 的容量、路由和通信", intuition: "MoE 省的是每 token 计算，不是让所有参数免费。", paragraphs: ["router 输出专家分数并选 top-k。训练还需 capacity factor 限制每个专家接收 token 数，以及 load-balancing loss 避免所有 token 挤向同一专家。在 expert parallel 中，token 通常通过 all-to-all 发送到专家所在设备。", "因此 MoE 的胜负依赖批量、网络拓扑、kernel 与负载。单机小 batch 可能根本吃不到理论收益。解释模型规模时应同时给 total params、active params/token 与实际 FLOPs。"], formula: { latex: "y=\\sum_{e\\in TopK(g(x))}\\alpha_e(x)E_e(x)", explanation: "只计算被选专家 E_e，再按归一化路由权重 α_e 合并。", symbols: [{ symbol: "g(x)", meaning: "router logits" }, { symbol: "E_e", meaning: "第 e 个专家 MLP" }, { symbol: "K", meaning: "每 token 激活的专家数" }] }, checks: ["最忙专家的 token 数是多少？", "all-to-all 时间是否计入吞吐？"] },
      ],
      pitfalls: ["把 FlashAttention 说成线性 attention", "把总参数量当作每 token 计算量", "忽略 router imbalance 与跨机 all-to-all"],
      recordings: [{ title: "Lecture 4 · Attention Alternatives", youtubeId: "cKSwj_qZ8Jg", note: "课堂覆盖线性/循环 duality、hybrid attention、sparse attention 与 MoE 的路由和系统成本。" }],
      exercises: [
        { question: "Q(KᵀV) 为什么不等价于标准 softmax attention？", answer: "softmax ρ 作用在 QKᵀ 上，通常不能穿过矩阵乘法或用结合律重排。" },
        { question: "MoE 增加专家数为什么仍会增加成本？", answer: "存储、参数同步/加载、路由与通信都增长；只有每 token 的专家计算近似由 top-k 固定。" },
      ],
      sources: [slides("04", "Attention alternatives and mixtures of experts"), video("cKSwj_qZ8Jg", "Lecture 4 · Attention Alternatives")],
    },
    {
      slug: "accelerator-roofline",
      index: 5,
      title: "GPU、TPU 与 Roofline",
      subtitle: "Lecture 5：让加速器不再是黑箱",
      duration: "4 小时",
      summary: "GPU 用大量线程追求吞吐，内存层级却限制数据供给。课程沿着 SIMT、warp、shared memory、tensor core 到 FlashAttention，解释为什么低精度、fusion、tiling 和重算有效。",
      objectives: ["解释 GPU 执行与内存层级", "判断 memory-bound/compute-bound", "从 I/O 角度解释 fusion 与 tiling"],
      prerequisites: ["第 2 章资源账本", "基本并行程序概念"],
      concepts: [
        { name: "SIMT 与 warp", explanation: "GPU 让一组线程执行同一指令处理不同数据；NVIDIA warp 通常以 32 线程为调度组。", why: "大量规则并行工作可提供高吞吐。", example: "同一 warp 的线程走不同 if 分支时，分支往往串行执行并屏蔽不活跃线程。", boundary: "SIMT 不是所有 GPU/TPU 的统一细节；具体 warp、block 限制需看硬件。" },
        { name: "GPU 与 TPU", explanation: "二者都把大部分芯片预算用于并行矩阵乘、片上存储和高带宽数据通路，而不是复杂的单线程控制。GPU 以大量 SM、warp/SIMT 提供较通用的编程面；TPU 更偏大块矩阵单元与显式编译调度，没有完全对应 CUDA warp 的抽象。", why: "同一个 matmul 在两类设备上都可能很快，但非规则控制流、网络拓扑和编译栈的代价不同。", example: "分支很多的小 kernel 在 GPU 上会遇到 warp divergence；大而规则的矩阵乘更接近两类设备的优势区。", boundary: "GPU/TPU 是产品族而非固定规格。SM 数、矩阵单元、互联和内存数字必须注明具体代际。" },
        { name: "内存层级", explanation: "register、shared memory/L1 靠近计算单元、容量小；L2 服务更多执行单元；HBM 容量大，却是片外往返。越靠近算力，通常容量越小、复用要求越高。", why: "很多 ML 算子不是算不动，而是反复把中间量搬进搬出 HBM。", example: "把 softmax 一行留在片上完成，可避免 max、exp、sum、normalize 各自把整行写回 HBM。", boundary: "片上容量有限；tile 太大会增加 register/shared-memory 压力，降低 occupancy，甚至无法启动。" },
        { name: "Tensor Core", explanation: "专门执行小块矩阵乘加的硬件，低精度 matmul 峰值远高于一般标量运算。", why: "Transformer 的主要 FLOPs 是矩阵乘法，shape 对齐和 dtype 会直接影响利用率。", example: "不规则小矩阵即使 FLOPs 少，也可能无法填满 tensor cores。", boundary: "宣传峰值不包括数据搬运、通信与非 matmul 算子。" },
        { name: "Coalescing、tiling 与 fusion", explanation: "coalescing 让同一 warp 的线程访问相邻地址；tiling 把会复用的数据块留在片上；fusion 则让多个逐元素阶段共享一次读写。三者分别修复访问形状、复用距离和中间量落盘。", why: "它们减少相对 HBM 的搬运量，而不是把所有优化笼统归为‘少算 FLOPs’。", example: "课堂里的 sin²x+cos²x 若拆成多个逐元素 kernel，会多次读写中间量；融合后可一次读入、一次写出。", boundary: "fusion 可能增加寄存器压力；coalesced 也不等于命中 cache；tile 尺寸仍要服从硬件容量与对齐。" },
        { name: "Online softmax", explanation: "分块扫过一行 logits 时，维护目前最大值 m、指数和 l，以及按同一尺度累计的加权值 o。新块提高最大值后，旧的 l 和 o 都必须乘 exp(m_old−m_new) 重标度。", why: "这样不保存完整 score 行，仍能得到与稳定 softmax 相同的输出。", example: "先处理 [1000,999]，再处理 [1002]；第二块到来后，第一块累计量统一乘 exp(1000−1002)，不会溢出也不会丢失旧贡献。", boundary: "它节省的是中间量与 HBM I/O；允许的 q-k 对仍全部计算，attention FLOPs 仍是二次。" },
      ],
      sections: [
        { title: "1. 先看执行机器：CPU、GPU 与 TPU", intuition: "加速器不是更快的 CPU；它用规则并行和显式复用换吞吐。", paragraphs: ["CPU 为少数复杂线程配置分支预测、大缓存和乱序执行；GPU 把更多面积交给 SM 内的并行执行单元。线程组成 block，block 被调度到一个 SM 并共享片上存储；NVIDIA 设备再以 32-thread warp 锁步发射。若一个 warp 的线程走不同分支，两条路径往往要分时执行。", "TPU 与 GPU 的共同点是轻控制、大矩阵单元和快片上存储；区别在编程模型与互联。课程把 TPU 作为旁线，是为了提醒：warp、bank 等术语不是所有加速器的普遍定律，但‘让矩阵足够大、让数据复用、让通信匹配拓扑’可以迁移。性能问题通常来自 block 太少、寄存器压力、分支发散、bank conflict 或不连续访存。"], figures: [{ title: "CPU 与 GPU 的资源取舍", src: "https://raw.githubusercontent.com/stanford-cs336/lectures/main/images/cpu-gpu.png", href: "https://github.com/stanford-cs336/lectures/blob/main/images/cpu-gpu.png", caption: "原课用这张图对比 CPU 的低延迟控制与 GPU 的吞吐式并行。阅读时关注资源分配，不要把示意图当具体芯片规格。", credit: "Stanford CS336 Lecture 5，远程引用，未在本站复制", kind: "image" }], checks: ["并行 block 是否足以覆盖所有 SM？", "结论依赖 CUDA warp，还是可迁移到其他加速器？"] },
        { title: "2. Roofline：先判断算得慢还是搬得慢", intuition: "同样一万亿次运算，复用同一批数据和每次都从 HBM 取数，是两种 workload。", paragraphs: ["算术强度 I=F/M，分子是 FLOPs，分母是相对某一慢层级搬运的 bytes。设备峰值计算率 C_peak 与带宽 BW 给出两个上限：计算至少花 F/C_peak，搬运至少花 M/BW；roofline 用两者较大值做理想化下界。若 BW·I 小于 C_peak，算子在该口径下 memory-bound。", "低精度会同时减少每元素 bytes，并在支持的矩阵单元上提高峰值 FLOPs；但 fp8/fp4 常伴随 block scale、转置格式和高精度累加。课堂展示 MXFP8/MXFP4 是为了看清工程代价，不是说把 dtype 改小就自动保持训练质量。算术强度也必须注明相对 HBM、L2 还是网络，否则同一算子会得到不同答案。"], formula: { latex: "I=\\frac{F}{M},\\qquad t\\gtrsim\\max\\left(\\frac{F}{C_{peak}},\\frac{M}{BW}\\right),\\qquad C_{attainable}\\le\\min(C_{peak},BW I)", explanation: "这是忽略调度、启动与重叠细节的上界模型，用于确定优化方向而非预测精确毫秒数。", symbols: [{ symbol: "F", meaning: "工作负载 FLOPs" }, { symbol: "M", meaning: "相对所选慢层级搬运的字节" }, { symbol: "BW", meaning: "该层级带宽" }, { symbol: "C_peak", meaning: "相应 dtype 下峰值算力" }] }, figures: [{ title: "计算增长快于内存供给", src: "https://raw.githubusercontent.com/stanford-cs336/lectures/main/images/compute-memory.png", href: "https://github.com/stanford-cs336/lectures/blob/main/images/compute-memory.png", caption: "原课用历史趋势说明 memory wall。它支持‘先算 bytes’的动机，不提供某一设备的永久常数。", credit: "Stanford CS336 Lecture 5，远程引用，未在本站复制", kind: "image" }], checks: ["bytes 相对哪个内存层级？", "使用的是对应 dtype 的稠密峰值吗？"] },
        { title: "3. Fusion、重算与 coalescing 分别修什么", intuition: "少写一次中间量、重算一个便宜函数、让相邻线程读相邻地址，是三种不同手术。", paragraphs: ["逐元素表达式若拆成多个 kernel，每一步都可能把中间量写回 HBM。课堂以 sin²x+cos²x 为例：朴素 eager 执行会产生多次 launch 和读写；编译器或手写 fused kernel 可把它变成一次读、一次写。重算则更进一步：若某个中间量生成很便宜，反向时重新计算可能比保存并读取它更快。", "DRAM 以 burst 传输连续区域。让同一 warp 的线程访问相邻地址，才能把一次 transaction 的字节都用上；按错误轴遍历 row-major 矩阵，即使每个线程只读一个数，也会浪费 transaction。coalescing 解决访问排列，fusion 解决阶段边界，recomputation 解决保存选择，三者不能互相替代。"], example: { title: "为什么 FLOPs 增加反而可能变快", steps: ["方案 A 保存一个昂贵到 HBM 的逐元素中间量，反向时再读。", "方案 B 丢弃它，反向时用寄存器中的输入重算。", "若重算耗时小于一次写加一次读，方案 B 虽多做 FLOPs，墙钟时间反而更短。"], result: "优化目标是端到端时间和内存，不是单独最小化 FLOPs。" }, checks: ["中间量跨 kernel 落到哪里？", "线程地址在一个 warp 内是否连续？"] },
        { title: "4. Tiling：用片上复用偿还矩阵乘的数据成本", intuition: "矩阵乘快，不是因为每个乘加便宜，而是同一元素能在 tile 内被反复使用。", paragraphs: ["朴素 n×n matmul 若每次乘加都从全局内存取两个输入，输入读取量数量级为 2n³ 个元素。以 T×T tile 为单位装入 shared memory 后，同一元素可服务 T 次乘加，理想化全局读取降到约 2n³/T。真实 kernel 还要处理边界 mask、对齐、double buffering、寄存器 tile 和 tensor-core shape。", "tile 不是越大越好。它占用更多 shared memory 与寄存器，可能减少每个 SM 同时驻留的 block；矩阵维度与 tile 不整除时还出现浪费。课程用 A100 上 block 数与 SM 数的例子说明，局部最省流量的 tile 不一定带来最高设备利用率。"], formula: { latex: "R_{naive}\\approx2n^3,\\qquad R_{tiled}\\approx\\frac{2n^3}{T}", explanation: "R 只统计一个理想化方阵 matmul 的输入元素全局读取次数；输出写入、cache 命中和边界未计。", symbols: [{ symbol: "n", meaning: "方阵边长" }, { symbol: "T", meaning: "tile 边长/复用因子" }, { symbol: "R", meaning: "全局内存输入元素读取次数" }] }, checks: ["tile 是否放得进片上存储？", "减少 traffic 后是否因 occupancy 下降抵消收益？"] },
        { title: "5. 从 online softmax 到 FlashAttention", intuition: "FlashAttention 的关键不是少看 token，而是不把完整 score 矩阵写进 HBM。", paragraphs: ["朴素 attention 先物化 S=QKᵀ，再执行稳定 softmax，最后乘 V。分块算法对每个 query tile 逐块读 K/V。设旧累计为最大值 m、指数和 l、未归一化加权输出 o；新 score 块到来时先求 m_new，再按 exp(m_old−m_new) 重标度旧 l 和 o，最后加入新块。全部块结束后输出 o/l。", "这个递推与一次性稳定 softmax 等价，也让 Q/K/V tile 和累计量留在片上。它避免 score 矩阵的 HBM 写回和读回，但所有允许的 q-k 点积仍存在，所以 FLOP complexity 仍为 O(n²)。训练反向还会按 tile 重算部分量；不能只从 forward 峰值推断总成本。"], formula: { latex: "m'=\\max(m,\\max s),\\quad l'=e^{m-m'}l+\\sum_j e^{s_j-m'},\\quad o'=e^{m-m'}o+\\sum_j e^{s_j-m'}v_j,\\quad y=o'/l'", explanation: "m、l、o 必须使用同一新尺度更新；漏掉 o 的重标度会得到数值稳定但错误的输出。", symbols: [{ symbol: "s_j", meaning: "当前 score tile 中的 logit" }, { symbol: "v_j", meaning: "对应 value" }, { symbol: "m,l,o", meaning: "旧块累计最大值、指数和与加权值" }] }, figures: [{ title: "分块矩阵乘的数据复用", src: "https://raw.githubusercontent.com/stanford-cs336/lectures/main/images/gemm_tiled.png", href: "https://github.com/stanford-cs336/lectures/blob/main/images/gemm_tiled.png", caption: "原课先用 tiled GEMM 建立片上复用，再把同一思想用于 QKᵀ、online softmax 与分块输出累计。", credit: "Stanford CS336 Lectures 5–6，远程引用，未在本站复制", kind: "image" }], checks: ["online 更新是否同时重标度 l 与 o？", "是否把 I/O complexity 与 FLOP complexity 混淆？"] },
      ],
      lab: { title: "实验：Roofline、HBM traffic 与 online softmax", goal: "用 CPU 数值实验分别验证 roofline 判别、score 物化流量和 online-softmax 等价性，不伪装成 GPU benchmark。", file: "/labs/cs336/roofline_attention.py", steps: ["计算 memory/compute-bound 两种算子", "比较朴素 score 的 HBM 写读与分块片上暂存", "用极端 logits 验证分块递推"], expected: ["online 与一次性稳定 softmax 输出一致", "分块方案不把 S² score 写入 HBM", "序列加倍时朴素 score traffic 约变 4 倍", "输出 PASS"], sourceNote: "对应 Lecture 5 的 roofline 与 FlashAttention 推导；这里只核对数学与 I/O 账本，不报告 GPU 加速比。" },
      recordings: [{ title: "Lecture 5 · GPUs, TPUs", youtubeId: "izZba4UA7iY", note: "课堂从 GPU/CPU 差异、内存层级和 roofline 解释 FlashAttention，而不是只展示速度结果。" }],
      pitfalls: ["用 CPU 实验声称 GPU 加速比", "混淆 cache/shared memory/HBM 的带宽口径", "认为 kernel fusion 总能减少 FLOPs"],
      exercises: [
        { question: "为什么重算可能更快？", answer: "若函数便宜而保存/读取中间结果的 HBM 成本高，重算增加少量 FLOPs却减少更多慢速搬运。" },
        { question: "FlashAttention 与 sparse attention 的本质区别？", answer: "前者通常精确计算所有允许配对但优化 I/O；后者跳过一部分配对并改变连接模式。" },
      ],
      sources: [slides("05", "GPUs, TPUs"), video("izZba4UA7iY", "Lecture 5 · GPUs, TPUs"), assignment(2, "Systems", "systems")],
    },
    {
      slug: "kernels-triton",
      index: 6,
      title: "Benchmark、Kernel 与 Triton",
      subtitle: "Lecture 6：先剖析，再把 GELU、softmax 和 matmul 分块写进 kernel",
      duration: "5 小时",
      summary: "官方 executable lecture 从可信计时出发，对比 naive、builtin、compiled 与 Triton，再逐步引入 block、mask、reduction 和 tiling。本章保持这个顺序，但 CPU 实验只验证基准方法。",
      objectives: ["写出可信 benchmark protocol", "解释 program id、block 与 mask", "区分正确性、稳定性和性能测试"],
      prerequisites: ["第 5 章", "Python profiling"],
      concepts: [
        { name: "Warm-up 与同步", explanation: "首次运行可能含编译/缓存成本，GPU 调用又是异步；稳态计时前需 warm-up，边界处同步。", why: "否则测到的是启动或 CPU enqueue 时间。", example: "记录 CUDA event 后必须等 end event 完成，普通 perf_counter 包围异步 launch 会低估。", boundary: "冷启动延迟对在线服务也可能重要，应另立指标而不是丢弃。" },
        { name: "Profiler", explanation: "profiler 记录时间落在哪些算子、kernel 与内存事件。", why: "总耗时只能说明慢，不能告诉你该优化哪一层。", example: "若 layernorm 占比小，花数天写自定义 kernel 对端到端收益有限。", boundary: "profiling 本身有开销；采样应代表真实 shape 和稳态负载。" },
        { name: "Occupancy 与资源约束", explanation: "一个 block 使用的 registers、shared memory 与 warps 会限制同一 SM 能同时驻留多少 block。occupancy 描述可驻留 warps 相对硬件上限的比例。", why: "驻留 warp 可在另一个 warp 等待内存时隐藏延迟，但单线程使用更多寄存器也可能减少搬运，因此 occupancy 不是越高越好。", example: "128 threads/block、160 registers/thread 时，一个 block 需 20,480 registers；若 SM 只有 65,536 registers，寄存器会把并发 block 限在 3 个。", boundary: "还要同时检查 shared memory、最大 threads/blocks 与编译器实际寄存器分配；只算一个约束是上界。" },
        { name: "Bank conflict", explanation: "shared memory 被划分为多个 bank；同一 warp 若同时访问同一 bank 的不同地址，访问可能串行化。", why: "数据已经进了片上存储，错误布局仍会让带宽打折。", example: "二维 tile 增加一列 padding，常可打散转置访问时的同-bank 冲突。", boundary: "bank 数和宽度依硬件而变；广播同一地址与访问不同地址的行为也不同。" },
        { name: "Triton program", explanation: "一个 program instance 处理一个 block，通过 program_id 找到数据区间，mask 防越界。", why: "它以块级抽象表达 GPU 并行，便于控制加载、计算和存储。", example: "长度 1000、BLOCK_SIZE 1024 时，最后 24 个 lane 必须 mask。", boundary: "通过单元测试不代表占用率、访存合并或寄存器压力理想。" },
        { name: "编译层级", explanation: "PyTorch eager 提交现成算子；torch.compile 尝试捕获图并融合；Triton 让作者显式写 block 级算法；Triton 最终还会生成 PTX/机器码。", why: "profile 中看到一个 kernel 还是五个 kernel，往往由编译边界而非公式本身决定。", example: "naive GeLU 的乘、加、tanh 可能形成多个 kernel，compiled/builtin 版本可融合成一次 HBM 读写。", boundary: "同样的 Python 代码会因版本、shape 和动态控制流得到不同编译结果，必须查看实际 graph/kernel。" },
      ],
      sections: [
        { title: "1. Benchmark 回答多久，profiler 回答时间花在哪里", intuition: "一次 time() 既看不到异步执行，也分不开编译、launch 与稳态计算。", paragraphs: ["先固定输入 shape、dtype、layout、设备、正确性容差和 workload。冷启动要单独测，因为它包含 import、JIT/graph compile 和 cache 建立；稳态 benchmark 则 warm-up 后重复多次，报告 median 与尾分位。CUDA 调用默认异步，使用 CPU 时钟前后必须 synchronize，或使用正确放置并等待完成的 CUDA events。", "profiler 展开调用栈和实际 kernel。Lecture 6 比较不同矩阵尺寸时，PyTorch 可能选择不同 CUDA kernel；总耗时曲线告诉你何时变慢，profiler 才显示是 launch、memcpy 还是某个 matmul。profile 自己会增加开销，所以用代表性短窗口，不把 profile 时间当正式 benchmark。"], formula: { latex: "t_{cold}=t_{compile}+t_{launch}+t_{execute},\\qquad \\tilde t_{steady}=\\operatorname{median}(t_1,\\ldots,t_n)", explanation: "冷启动与稳态回答不同问题；分位数比单次或只报均值更能暴露抖动。", symbols: [{ symbol: "t_cold", meaning: "首次调用端到端时间" }, { symbol: "t_execute", meaning: "设备实际执行时间" }, { symbol: "t̃_steady", meaning: "warm-up 后稳态中位数" }] }, checks: ["计时边界是否同步设备？", "冷启动是否被混进候选实现的一边？", "shape sweep 是否覆盖真实负载？"] },
        { title: "2. 用 GeLU 看 eager、builtin 与 compiled 的差别", intuition: "数学表达式相同，不代表执行图相同。", paragraphs: ["Lecture 6 先把 GeLU 写成若干基础张量操作，再与 PyTorch builtin、torch.compile 版本比较。naive eager 可能逐项启动乘、加、tanh 等 kernel，每个阶段都让中间量往返 HBM；builtin 或 compiled 版本可把表达式融合成一个 kernel。此时加速主要来自 launch 和 traffic，而不是减少 GeLU 的数学步骤。", "比较之前先用 fp32 reference 测随机输入、零附近和大幅值输入，再为 bf16/fp16 设置与量化误差相称的 atol/rtol。若为了让候选通过而放宽阈值，必须同步报告最大误差与失败 shape。编译器是否真的融合，要由 graph/profiler/PTX 证据确认，不能凭用了 torch.compile 就断言。"], example: { title: "一个伪造的 2× 加速", steps: ["naive 版本第一次运行，时间包含编译和 allocator 初始化。", "compiled 版本先跑过多次，缓存已经热。", "两者只比较一个 16,384 元素的整齐 shape，也没核对极端输入。"], result: "纠正 warm-up、shape 与正确性协议后，原数字作废；新结果才可解释。" }, figures: [{ title: "Lecture 6 的硬件/编程账本", src: "https://raw.githubusercontent.com/stanford-cs336/lectures/main/images/gpu-hardware.png", href: "https://github.com/stanford-cs336/lectures/blob/main/images/gpu-hardware.png", caption: "原课列出多代 GPU 的 SM、片上存储和 HBM，用于说明 kernel 选择必须绑定设备。具体数值会过时，本站只保留读表方法。", credit: "Stanford CS336 Lecture 6，远程引用，未在本站复制", kind: "image" }], checks: ["三种实现的输出是否先对齐？", "profiler 是否真的显示 kernel 数减少？"] },
        { title: "3. Triton 的基本单位是 program/block", intuition: "先决定一块数据怎样在片上完成，再决定开多少块。", paragraphs: ["对于长度 N 的逐元素 GeLU，选择 BLOCK_SIZE 后，grid 大小是 ceil(N/BLOCK_SIZE)。program_id 给出当前块号，offset=pid·BLOCK_SIZE+arange；最后一块通常越界，所以 load/store 都要带 offset<N 的 mask。长度 1000、block 1024 时，24 个 lane 不应访问真实内存。", "program 正确之后再谈性能。一个 block 使用的 registers 和 shared memory 会限制驻留数；连续 lane 的地址关系决定 coalescing；shared tile 的索引决定 bank conflict。Triton 编译成 PTX，查看生成代码能发现意外的类型转换、冗余 load 或寄存器溢出，但 PTX 是诊断证据，不是要求学习者手写汇编。"], formula: { latex: "N_{programs}=\\left\\lceil\\frac{N}{B}\\right\\rceil,\\qquad i=pid\\cdot B+[0,\\ldots,B-1],\\qquad mask=(i<N)", explanation: "向上取整保证覆盖全部元素，mask 负责最后一个不完整 block。", symbols: [{ symbol: "B", meaning: "BLOCK_SIZE" }, { symbol: "pid", meaning: "program id" }, { symbol: "i", meaning: "当前 program 负责的全局索引" }] }, checks: ["N=0、N=1、N=B±1 时 grid/mask 是否正确？", "load 和 store 是否使用一致边界？"] },
        { title: "4. Reduction：一行放得下与放不下是两种算法", intuition: "elementwise 没有跨 lane 依赖，softmax 和 row sum 必须汇总。", paragraphs: ["若 softmax 的一整行能放入一个 block，program 可一次读取该行，先归约 max，再归约 exp sum，最后写出概率。BLOCK_SIZE 常取不小于列数的 2 的幂，空余 lane 用 −∞ mask；这样便于归约，却可能浪费 lane。全 mask 行没有有限最大值，必须由上层语义明确处理。", "当行宽超过单 block 可承载范围，不能简单扩大 block。Lecture 6 先用 row sum 拆解：每个 program 计算一段 partial sum，随后第二阶段归约这些 partials。跨 block 同步需要额外 kernel、原子操作或重新布局。softmax 的多阶段版本还要同时传播 max 与按新尺度修正的 sum。"], formula: { latex: "p_i=\\frac{e^{x_i-m}}{\\sum_j e^{x_j-m}},\\qquad m=\\max_jx_j", explanation: "减最大值保持概率不变并避免指数溢出；mask lane 应贡献 −∞ 而不是 0。", symbols: [{ symbol: "x_i", meaning: "有效 logit" }, { symbol: "m", meaning: "有效位置最大值" }, { symbol: "p_i", meaning: "输出概率" }] }, figures: [{ title: "Triton 单行 softmax 数据流", src: "https://raw.githubusercontent.com/stanford-cs336/lectures/main/images/triton-softmax.png", href: "https://github.com/stanford-cs336/lectures/blob/main/images/triton-softmax.png", caption: "一个 program 负责一行时，max、sum 与 normalize 都留在同一 block；行太宽后必须换成分层归约。", credit: "Stanford CS336 Lecture 6，远程引用，未在本站复制", kind: "image" }], checks: ["mask lane 的归约单位元正确吗？", "行宽超过单 block 时是否仍假装一次完成？"] },
        { title: "5. 从 row sum 走到 tiled matmul+ReLU", intuition: "matmul kernel 的核心是把 A/B tile 复用多次，并在结果写回前融合便宜后处理。", paragraphs: ["给输出 tile C[m:m+BM,n:n+BN]，program 沿 K 维循环：分别加载 A 的 BM×BK 与 B 的 BK×BN tile，在寄存器累加 BM×BN 结果。边界 tile 用 mask；低精度输入常用更高精度累加。grid 的二维映射还应让相邻 programs 复用 cache，而不是只做字面 row-major 排列。", "ReLU 若在 matmul 后另开 kernel，会重新读写完整 C。把 max(C,0) 放在 store 前就能融合；代价是 kernel 更复杂、寄存器生命周期可能变长。最终闭环是 reference→correctness→profile→提出 traffic/occupancy 假设→跨 shape benchmark，而不是先写自定义 kernel。A2 的 FlashAttention2 与分布式 TODO 仍由学习者独立完成。"], example: { title: "Tiled matmul 的核对顺序", steps: ["先用 3×5 乘 5×7 的非整除 shape 对齐 reference。", "再测大而整齐和窄矩阵，观察 tile 选择是否改变。", "最后用 profiler/PTX 核对 fusion、load 与寄存器，而不是只看一个最快数字。"], result: "正确性覆盖边界，性能覆盖工作负载，二者都通过后才可接受 kernel。" }, checks: ["累加 dtype 是什么？", "非整除 M/N/K 是否都 mask？", "融合后端到端收益是否可见？"] },
      ],
      lab: { title: "实验：可信 benchmark 与 kernel 资源账本", goal: "在无需 GPU 的环境中验证 warm-up/分位数协议、mask、occupancy、fusion traffic 和 tiled-matmul 读取量；若本机有 PyTorch/Triton，只报告可用性，不伪造性能。", file: "/labs/cs336/kernel_benchmark_protocol.py", steps: ["运行固定 CPU workload 的冷/热计时协议", "检查 N=B±1 的 block/mask", "改变 registers/thread 与 tile size", "查看可选 GPU 栈探测结果"], expected: ["稳态统计包含 median/p90 而非单次值", "最后一块越界 lane 数正确", "fusion traffic 少于多阶段 eager 账本", "输出 PASS"], sourceNote: "对应 Lecture 6 的 benchmark/profile 与 Triton 资源分析；不包含官方 A2 kernel 或 adapter 实现。" },
      pitfalls: ["忘记异步同步", "只测 2 的幂 shape", "为了跑分放宽误差却不说明"],
      recordings: [{ title: "Lecture 6 · Kernels, Triton, XLA", youtubeId: "xnDHaNUvHBg", note: "课堂顺序是 benchmark/profile，再写 GELU、softmax、reduction 与 tiled matmul。" }],
      exercises: [
        { question: "为什么最后一个 block 需要 mask？", answer: "grid 常向上取整；最后 block 的部分 lane 会落在数组之外，必须禁止非法 load/store。" },
        { question: "profiler 与 benchmark 各回答什么？", answer: "profiler 定位时间和资源分布；benchmark 在受控条件下量化某实现的延迟/吞吐。" },
      ],
      sources: [script("06", "Kernels, Triton, XLA"), video("xnDHaNUvHBg", "Lecture 6 · Kernels, Triton, XLA"), assignment(2, "Systems", "systems")],
    },
    {
      slug: "parallel-training",
      index: 7,
      title: "Collectives 与多维并行训练",
      subtitle: "Lectures 7–8：从 all-reduce 原语到 DP、FSDP、TP、PP 与 expert parallel",
      duration: "6 小时",
      summary: "两次 parallelism 课被保留为一条连续主线：先理解通信原语和网络，再把模型的 batch、宽度、深度和专家维切到设备 mesh 上。",
      objectives: ["手算 collective 输入输出与通信量", "区分 replicated、sharded 与 partitioned 状态", "为给定模型和拓扑选择混合并行"],
      prerequisites: ["第 2、5–6 章", "基本进程/设备概念"],
      concepts: [
        { name: "Collective", explanation: "all-reduce、reduce-scatter、all-gather、all-to-all 是一组 rank 共同参与的通信操作，各自有严格输入输出契约。", why: "分布式训练的梯度同步、参数分片和专家路由最终落在这些原语上。", example: "四个 rank 各有一个向量，all-reduce sum 后每个 rank 都得到四向量之和。", boundary: "collective 的数学结果相同，不代表 ring、tree 等实现延迟和带宽相同。" },
        { name: "Data Parallel", explanation: "每个 rank 保留完整模型，处理不同 batch shard，再汇总梯度。", why: "实现简单且计算能随 batch 扩展。", example: "global batch 128、4 rank 时每 rank 处理 32 个样本，反向后 all-reduce 梯度。", boundary: "模型、梯度和 optimizer state 仍需在单设备放下；FSDP/ZeRO 才进一步分片。" },
        { name: "Tensor Parallel", explanation: "把单层矩阵沿输入或输出通道切到多设备，层内需 all-reduce/all-gather。", why: "单层权重无法放进一张卡时，按宽度分摊存储和 matmul。", example: "W 的列分到两卡，各算一半输出通道，再按下一层布局决定是否聚合。", boundary: "TP 通信发生频繁，通常应放在高速节点内互联。" },
        { name: "Pipeline Parallel", explanation: "把连续层分成 stages，不同 microbatch 像流水线一样穿过。", why: "按深度分摊参数，跨 stage 只传激活/梯度。", example: "4 stages、8 microbatches 能重叠部分前后向，但开始和结束有 bubble。", boundary: "microbatch 太少 bubble 大；太多则调度和小矩阵效率变差。" },
      ],
      sections: [
        { title: "1. 先画 rank 上的值，再背 collective 名字", intuition: "collective 的名字容易混，输入输出表不会混。", paragraphs: ["reduce-scatter 把跨 rank 归约后的结果切片留在不同 rank；all-gather 把各 rank 切片拼回完整张量。两者组合可实现 all-reduce，并在带宽受限时避免单点瓶颈。all-to-all 则把每个 rank 给每个目标的分片重新分发，是 expert parallel 的关键。", "Lecture 7 的 executable lecture 用 rank0…rank3 的具体小张量展示输出，再进入 torch.distributed 和 NCCL benchmark。本站 CPU 实验同样先验证数学结果，不冒充真实网络性能。"], example: { title: "四 rank reduce-scatter", steps: ["rank r 持有长度 4 向量 [r,r+1,r+2,r+3]。", "逐位置求和得 [6,10,14,18]。", "scatter 后 rank0 得 6，rank1 得 10，rank2 得 14，rank3 得 18。"], result: "再 all-gather，所有 rank 都恢复 [6,10,14,18]，等价于 all-reduce 结果。" }, checks: ["归约发生在哪个维？", "每个 rank 最终拥有完整还是分片结果？"] },
        { title: "2. 三种切分对应三种通信位置", intuition: "并行不是多开进程，而是选择哪个张量轴在哪里切。", paragraphs: ["DP 切 batch，通信主要在梯度；TP 切 layer width，几乎每层通信；PP 切 layer depth，stage 之间传激活。FSDP/ZeRO 则在 DP 组内分片参数、梯度和 optimizer state，并在需要计算时 gather。", "Lecture 8 将这些选择放回 GPU/TPU 网络：高频 TP 应利用节点内高带宽，跨节点更适合较粗粒度 DP/PP。所谓 3D parallelism 是在设备 mesh 的独立轴上组合 DP×TP×PP。MoE 的 EP 若另占一个独立 mesh 轴才可继续相乘；很多实现让 EP 与数据并行子组重叠，此时不能机械地再乘一次。"], formula: { latex: "N_{devices}=N_{DP}N_{TP}N_{PP}\\quad(\\text{independent mesh axes})", explanation: "只有互不重叠的逻辑轴才能相乘；EP 是否是额外因子必须由 process-group/mesh 定义确认。", symbols: [{ symbol: "DP", meaning: "数据并行度" }, { symbol: "TP", meaning: "张量并行度" }, { symbol: "PP", meaning: "流水线并行度" }, { symbol: "EP", meaning: "专家并行度，可能与其他组重叠" }] }, checks: ["每个 mesh 轴是否真的独立？", "EP 与 DP/EDP 的 process group 如何重叠？", "通信是否匹配物理互联？"] },
        { title: "3. 可扩展性由最慢路径决定", intuition: "增加 GPU 同时增加计算供给和通信/调度成本。", paragraphs: ["strong scaling 固定总问题规模增加设备，单设备工作越来越少，通信占比上升；weak scaling 让问题规模随设备增长，关注每设备吞吐是否维持。step time 受最慢 rank、pipeline bubble 和 straggler 影响。", "真实训练还要 checkpoint、容错、确定性与 restart。A2 的目标不只是启动多进程，而是 memory-efficient distributed 版本，并通过官方 tests 证明分片 optimizer、DDP、FSDP 语义正确。"], formula: { latex: "\\eta_{strong}=T_1/(N T_N)", explanation: "理想 strong-scaling efficiency 为 1；N 卡时间 T_N 若没有接近 T_1/N，差额来自通信、空闲和开销。", symbols: [{ symbol: "T_1", meaning: "单设备时间" }, { symbol: "T_N", meaning: "N 设备时间" }, { symbol: "η_strong", meaning: "强扩展效率" }] }, checks: ["报告 global 还是 per-device batch？", "是否包含 checkpoint 和数据等待？"] },
      ],
      lab: { title: "实验：在单进程模拟 collectives 与分片状态", goal: "用列表模拟 all-reduce、reduce-scatter、all-gather，并验证组合不变量。", file: "/labs/cs336/collectives_sim.py", steps: ["运行四 rank 例子", "更改 world size", "观察通信结果和分片大小"], expected: ["reduce-scatter+all-gather 等于 all-reduce", "每 rank shard 大小一致", "输出 PASS"], sourceNote: "对应 Lectures 7–8 与 A2；不测网络带宽，不实现官方 distributed TODO。" },
      recordings: [
        { title: "Lecture 7 · Parallelism", youtubeId: "SzpOcwdIL0Y", note: "课堂从 collectives、NCCL 和 benchmark 进入 DP/TP/PP。" },
        { title: "Lecture 8 · Parallelism", youtubeId: "6-cXp-aOmdg", note: "课堂从网络拓扑和大模型内存限制继续讨论混合并行与大规模训练。" },
      ],
      pitfalls: ["把 global batch 和 local batch 混用", "只看带宽不看 latency 与消息大小", "在慢跨节点链路上放高频 TP"],
      exercises: [
        { question: "为什么 reduce-scatter + all-gather 可组成 all-reduce？", answer: "前者完成全局归约并把结果切片，后者把归约后的所有切片重新收集到每个 rank。" },
        { question: "FSDP 与普通 DP 的核心内存差别？", answer: "普通 DP 每卡复制完整训练状态；FSDP 在数据并行组中分片一部分或全部参数、梯度和 optimizer state。" },
      ],
      sources: [script("07", "Parallelism"), slides("08", "Parallelism basics"), video("SzpOcwdIL0Y", "Lecture 7 · Parallelism"), video("6-cXp-aOmdg", "Lecture 8 · Parallelism"), assignment(2, "Systems", "systems")],
    },
    {
      slug: "scaling-laws",
      index: 8,
      title: "Scaling Laws：拟合、预算与训练配方",
      subtitle: "Lectures 9 & 11：从幂律与 IsoFLOP 曲线走到 WSD、μP 和公开配方",
      duration: "6 小时",
      summary: "扩展律是有限实验区间内的经验模型，不是自然定律。先分清参数 N、token D、compute C 和 loss L，再用留出点检验外推；第二次课把这些工具放进 MiniCPM、DeepSeek 等公开训练配方。",
      objectives: ["拟合并诊断 power law", "在 compute constraint 下找 N/D 折中", "解释 WSD 和 μP 为何帮助低成本 scale-up"],
      prerequisites: ["对数与线性回归", "训练 loss"],
      concepts: [
        { name: "经验幂律", explanation: "在特定范围内，loss 的可约部分常近似随参数、数据或计算量按幂下降。", why: "小实验可以用来预测较大训练并分配预算。", example: "L(C)=L∞+aC^{-α}；取对数后若 L∞ 已知，成为直线拟合。", boundary: "数据分布、架构、优化器或区间改变会破坏外推；它不是无限尺度定律。" },
        { name: "IsoFLOP", explanation: "在近似相同训练 compute 下改变模型大小 N 与 token 数 D，比较最终 loss。", why: "同一预算下模型过大数据不足、或模型过小数据过多，都可能次优。", example: "固定 C≈6ND，N 加倍就需把 D 约减半。", boundary: "常数 6 是 dense Transformer 训练的工程近似，MoE、序列结构和实现会改变口径。" },
        { name: "Compute-optimal", explanation: "对每个 compute budget 找最低 loss 的 N*(C)、D*(C)，再拟合其随 C 的变化。", why: "它把“更大模型还是更多 token”变成可测问题。", example: "在每条 IsoFLOP 曲线上用平滑曲线求最小点，而不是只取噪声最小观测。", boundary: "最小 pretraining loss 不一定是下游、推理成本或生命周期总成本最优。" },
        { name: "WSD 与 μP", explanation: "WSD 把学习率分为 warmup、stable、decay；μP 设计参数化使某些超参数更能跨宽度迁移。", why: "可从 stable checkpoint 分叉多个 decay，减少 scaling sweep 重训成本；稳定超参数能降低试验维度。", example: "共享前 90% stable run，再从多个 token budget 分别进入 decay。", boundary: "迁移有假设和实现约束，不能把小模型最佳 LR 无条件复制到任意架构。" },
      ],
      sections: [
        { title: "1. 先定义要预测的量", intuition: "没有固定数据、tokenizer、loss 口径和训练配方，就没有一条可解释的曲线。", paragraphs: ["记录每次运行的 non-embedding parameter N、训练 token D、估计 compute C、训练/验证 loss、学习率计划和数据混合。若只收集成功 run 会有选择偏差；NaN 和欠训练点同样告诉你配方边界。", "Lecture 9 区分随 N、D、C 的一维 fits 与 Chinchilla 式 joint fit。A3 让学生通过训练 API 在有限预算下选择实验，再对隐藏规模提交预测；核心技能是 experimental design，不是套 scipy 一行函数。"], formula: { latex: "C\\approx6ND,\\qquad L(N,D)=E+A N^{-\\alpha}+B D^{-\\beta}", explanation: "E 是不可约/数据熵项，另两项描述有限模型与有限数据造成的损失。", symbols: [{ symbol: "N", meaning: "non-embedding 参数量" }, { symbol: "D", meaning: "训练 token 数" }, { symbol: "E", meaning: "渐近 loss" }, { symbol: "α,β", meaning: "经验缩放指数" }] }, checks: ["N 是否包含 embedding？", "C 是估计 FLOPs 还是实测设备时？"] },
        { title: "2. 拟合要留出外推测试", intuition: "训练点拟合得漂亮，不代表能预测更大规模。", paragraphs: ["对数空间最小二乘会改变误差权重；直接拟合 L 又可能让大 loss 点主导。应报告目标函数、置信区间和残差图。随机切分不足以测 scale extrapolation，最好按 compute 留出最大的若干点。", "若 L∞ 未知，log(L−L∞) 对 L∞ 很敏感；联合非线性拟合可能出现多组参数同样解释训练区间。先用合成数据检查 fitter 能否回收已知指数，再碰昂贵训练数据。"], example: { title: "错误的随机验证", steps: ["在 1M–1B FLOP 对数均匀采点。", "随机留出会让训练集仍包含 1B 附近点，验证只是插值。", "改为留出最大 20% compute，才测试向更大预算外推。"], result: "Scaling law 的验证划分必须匹配最终用途。" }, checks: ["残差随 scale 是否有系统趋势？", "最大目标点是否真正未参与拟合？"] },
        { title: "3. 从曲线到训练配方", intuition: "扩展律只有进入决策闭环才有用。", paragraphs: ["Lecture 11 对照 MiniCPM、DeepSeek 等公开配方：估计最佳 batch/LR，使用 WSD 获取多个有效终点，再做 IsoFLOP 或 joint fit；某些配方用 μP 让学习率与宽度更稳定。课堂也指出部分公开曲线数据稀疏、拟合未必令人信服。", "最终选择还要加入内存上限、并行效率、数据库存、推理成本与下游评价。把 loss 预测的小数点后三位当作确定事实，是对经验模型的滥用。"], checks: ["预测区间离最大实验点有多远？", "决策是否包含 inference cost？"] },
      ],
      lab: { title: "实验：拟合幂律并故意做一次失败外推", goal: "用标准库对合成 loss 拟合 log-linear 模型，比较插值与外推误差。", file: "/labs/cs336/scaling_fit.py", steps: ["运行已知指数的合成数据", "加入高尺度 regime change", "比较随机留出和最大尺度留出"], expected: ["正常区间能近似回收指数", "regime change 后外推误差明显上升", "输出 PASS"], sourceNote: "对应 Lectures 9/11 和 A3；不连接官方训练 API，不泄露 assignment solution。" },
      recordings: [
        { title: "Lecture 9 · Scaling Laws", youtubeId: "Q15rhEWZPQ4", note: "课堂建立基本 fits、IsoFLOP 与 compute-optimal 视角。" },
        { title: "Lecture 11 · Scaling Laws", youtubeId: "vTfEyOyzV9E", note: "课堂审查 μP、WSD 和多个公开模型的实际 scaling recipe。" },
      ],
      pitfalls: ["用随机切分冒充外推验证", "忽略 asymptote 却直接在 log-loss 上拟合", "把预训练 loss 最优等同于产品总成本最优"],
      exercises: [
        { question: "固定 C≈6ND，N 增大时 D 怎么变？", answer: "在该近似下 D≈C/(6N)，N 加倍则 D 约减半；实际还受效率和架构影响。" },
        { question: "为什么 WSD 有利于 scaling sweep？", answer: "多个预算可共享 warmup/stable 主干，再从不同 checkpoint 进入 decay，减少从头重复训练。" },
      ],
      sources: [slides("09", "Scaling laws — basics"), slides("11", "Scaling laws — recipes"), video("Q15rhEWZPQ4", "Lecture 9 · Scaling Laws"), video("vTfEyOyzV9E", "Lecture 11 · Scaling Laws"), assignment(3, "Scaling", "scaling")],
    },
    {
      slug: "inference",
      index: 9,
      title: "语言模型推理系统",
      subtitle: "Lecture 10：prefill、decode、KV cache、量化、推测解码与动态 batching",
      duration: "4–5 小时",
      summary: "推理不是把训练循环去掉 backward。长 prompt 的 prefill 和单 token decode 处在不同 roofline 区域，KV cache 又把序列状态变成容量与调度问题。",
      objectives: ["分别为 prefill/decode 做资源计数", "推导 KV cache 容量", "解释 continuous batching 与 PagedAttention"],
      prerequisites: ["第 2、3、5 章", "自回归生成"],
      concepts: [
        { name: "Prefill", explanation: "一次并行处理完整 prompt，生成各层 KV cache 和首个输出分布。", why: "prompt 长时有较大矩阵，通常更容易获得计算复用。", example: "长度 2048 的 prompt 一次送入模型，所有位置 attention 并行计算。", boundary: "prefill 仍会因长上下文 attention 与 cache 写入受限，不能简单叫 compute-bound。" },
        { name: "Decode", explanation: "每轮只输入新 token，读取全部历史 KV，产生一个下一个-token 分布。", why: "它决定交互式 generation throughput 与 inter-token latency。", example: "batch 1 时每层矩阵形状很瘦，还需读取整层权重，常受带宽限制。", boundary: "增大 batch 能提高权重复用，却增加队列等待和 KV cache 容量。" },
        { name: "KV cache", explanation: "保存每层历史 key/value，避免每轮从头重算过去 token。", why: "用内存换计算，把重复前缀的 attention projection 移出 decode 热路径。", example: "每层存 2×S×K×H 个元素；GQA 减少 K/V heads 可显著降 cache。", boundary: "cache 不保存所有中间激活；其大小随 batch、长度和层数线性增长。" },
        { name: "Continuous batching", explanation: "请求完成后立即把空出的 slot 给新请求，而不是等整批所有序列结束。", why: "生成长度不同，静态 batch 会让短请求等待长请求。", example: "A 在第 20 token 结束，系统下一步即可插入 D，不必等 B/C 到第 100 token。", boundary: "吞吐提升可能增加单请求排队延迟，需要明确服务目标。" },
      ],
      sections: [
        { title: "1. 同一个模型，两种完全不同的 workload", intuition: "prefill 像批量矩阵计算，decode 像不断搬权重和历史。", paragraphs: ["Lecture 10 对 MLP 和 attention 分别计算 arithmetic intensity：prefill 让序列维参与大矩阵，decode 每步只有一个新 token。batch=1 时每 token 几乎都要读一遍权重，算术强度很低；更大 batch 可让一次权重读取服务更多 token。", "服务指标必须拆开：time to first token 包含排队和 prefill；inter-token latency 主要反映 decode；tokens/s 是系统吞吐。只报一个平均延迟会隐藏长 prompt 或长 response 的尾部。"], checks: ["TTFT 与 ITL 是否分别测？", "prompt/response 长度分布是否代表真实流量？"] },
        { title: "2. KV cache 是容量规划的核心", intuition: "不重算历史的代价，是为每层每个历史 token 保留 K/V。", paragraphs: ["设 batch B、序列 S、KV heads K、head dim H、层数 L、元素字节 b，cache 近似 2BSKHLb。MHA 中 K 等于 query heads；GQA 让多个 query heads 共用较少 K/V heads，降低 cache。", "cache 与模型权重争夺显存。若为每个请求预留 max length，会产生内部碎片；PagedAttention 把 cache 分成页，按需映射逻辑 token 到物理块，理念类似虚拟内存。"], formula: { latex: "M_{KV}=2BSKHLb", explanation: "因子 2 来自 key 与 value；这是主项估计，未含 allocator metadata 和临时 buffer。", symbols: [{ symbol: "B", meaning: "并发序列数" }, { symbol: "S", meaning: "已缓存长度" }, { symbol: "K,H,L", meaning: "KV 头数、头维、层数" }, { symbol: "b", meaning: "每元素字节" }] }, checks: ["使用的是 query heads 还是 KV heads？", "是否计入 prefix sharing？"] },
        { title: "3. 近似和无损捷径要分开", intuition: "推理优化有些改变数值，有些在理想条件下保留分布。", paragraphs: ["量化把权重/激活映射到低比特表示，需报告 calibration、group size、scale 和 quality loss；GQA/local attention 通常是架构选择。推测解码则用便宜 draft 提议 token，由 target 模型验证，在正确接受规则下保持 target 分布。", "动态 batching、prefix cache、PagedAttention 主要改变调度与存储；kernel fusion 改执行；每项都应分别测 quality、吞吐、TTFT、ITL 和显存。所谓 lossless 常指采样分布，而不保证逐请求延迟一定改善。", "Dan Fu 的嘉宾课沿一枚 token 在 inference engine 中的生命周期重走这条链：调度请求、分配 KV 页、区分 prefill/decode，再讨论把多个 decode 操作合成 megakernel 以减少启动和中间搬运。后半把系统限制反推到循环式模型架构，强调 kernel、engine 与 architecture 要联合设计；这是 Lecture 10 的全栈延伸，不是新的通用加速定律。"], example: { title: "吞吐与延迟冲突", steps: ["batch 1 decode 权重读取无法复用，ITL 低但 tokens/s 差。", "等待凑 batch 32，提高权重复用和总吞吐。", "低流量请求却多等了 batching window，TTFT 变坏。"], result: "调度参数必须由 SLO 和到达过程决定，不能只最大化 GPU 利用率。" }, checks: ["优化是否改变输出分布？", "是否报告 p95/p99 而非只均值？"] },
      ],
      lab: { title: "实验：KV cache 与请求级 continuous batching", goal: "计算不同 KV-head 配置的容量，再用 arrival、completion 和 slot reuse 离散模拟对比静态 batch。", file: "/labs/cs336/inference_capacity.py", steps: ["计算 MHA cache", "把 KV heads 减为 1/4", "给五个不同到达/生成长度请求排程", "比较完成时间与 slot utilization"], expected: ["GQA cache 按 KV head 比例下降", "两种调度完成相同 useful token 工作", "continuous batching 在该 workload 中更早完成且利用率更高", "输出 PASS"], sourceNote: "对应 Lecture 10；本站实现请求级离散事件机制，不复刻 vLLM/PagedAttention。" },
      recordings: [
        { title: "Lecture 10 · Inference", youtubeId: "EfM546A79aM", note: "课堂从 MLP/attention 强度计算进入 GQA/MLA/CLA、量化、speculative decoding 和动态 workload。" },
        { title: "Guest Lecture · Dan Fu", youtubeId: "9EEm4iMAF5s", note: "延伸 Lecture 10：从 token 生命周期讲 continuous batching、KV cache 管理、prefill/decode 分工、megakernel 与循环架构。" },
      ],
      pitfalls: ["用总吞吐代替用户延迟", "KV cache 误乘 query heads", "把量化与推测解码都统称无损"],
      exercises: [
        { question: "GQA 为什么减少 KV cache？", answer: "多个 query heads 共享更少的 key/value heads，缓存按 KV heads 而非 query heads 计数。" },
        { question: "continuous batching 解决什么浪费？", answer: "不同序列完成时间不同造成的空闲 slot；它允许在解码迭代间加入/移除请求。" },
      ],
      sources: [script("10", "Inference"), video("EfM546A79aM", "Lecture 10 · Inference"), video("9EEm4iMAF5s", "Guest Lecture · Dan Fu")],
    },
    {
      slug: "evaluation",
      index: 10,
      title: "Evaluation：从预测到可信结论",
      subtitle: "Lecture 12：能力、偏好、agent、安全与污染审计",
      duration: "4 小时",
      summary: "评测不是下载 benchmark 跑一个总分。先明确被测构念，再固定 prompt、sampling、scorer 和统计单元；随后检查训练测试重叠、题目质量和 judge 偏差。",
      objectives: ["把目标构念映射到可观测指标", "计算准确率与不确定性", "识别 contamination、judge bias 与聚合陷阱"],
      prerequisites: ["概率统计基础", "语言模型输出"],
      concepts: [
        { name: "Construct validity", explanation: "指标是否真的测到了声称的能力，而非格式遵循、记忆或提示敏感性。", why: "一个高分只有在测量解释成立时才有意义。", example: "数学题 exact match 可能把等价表达判错，或把格式错误混入推理能力。", boundary: "不存在单一 benchmark 覆盖通用智能；结论范围应与任务集合一致。" },
        { name: "Evaluation protocol", explanation: "prompt template、few-shot examples、sampling、解码上限、答案提取和 scorer 的完整契约。", why: "任一细节变化都可能显著改变分数。", example: "同一多选题用生成字母与计算选项 logprob 得分可能不同。", boundary: "复现 protocol 不等于复现模型训练数据或服务端隐藏设置。" },
        { name: "Contamination", explanation: "评测题或近重复内容出现在训练数据中，使分数混入记忆。", why: "公开 benchmark 容易被网页和数据集镜像收进 pretraining corpus。", example: "不仅查题干精确哈希，还要查选项重排、翻译和近重复。", boundary: "未检测到重叠不证明没有污染；检测方法有召回边界。" },
        { name: "Judge model", explanation: "用另一个模型比较开放式回答，能扩展人工评测但会引入位置、长度、风格和自偏好。", why: "许多对话/agent 任务无法用简单 exact match。", example: "交换 A/B 回答顺序后裁决翻转，说明 position bias。", boundary: "judge 分数不是客观真值；需校准、盲评和人工抽查。" },
      ],
      sections: [
        { title: "1. 先问“测什么”，再问“用哪个榜单”", intuition: "指标是任务目标的代理。", paragraphs: ["Lecture 12 从 language modeling loss 走到 knowledge/reasoning benchmark、human/LM preference、agent task、安全和领域评测。每一类都需要不同 unit of analysis：题、对话、任务轨迹或危害类别。", "课程展示 MMLU/MMLU-Pro/GPQA、Arena、AlpacaEval、WildBench、TerminalBench、ARC-AGI、HarmBench 与领域 HELM，不是让人把分数相加，而是看见覆盖、scoring 和真实性的差异。"], checks: ["主张的能力是否超出评测覆盖？", "失败是内容、格式还是工具执行？"] },
        { title: "2. 样本统计与聚合", intuition: "100 道题的 75% 不是一个没有误差的常数。", paragraphs: ["对二元正确率，样本是 Bernoulli；可用 bootstrap 或合适区间表达不确定性。比较两个模型最好按同一题配对，观察每题差异，而非把两个独立误差条相减。子类平均与总体 micro-average 可能得出不同排序。", "开放式评测还要重复 sampling；temperature>0 时单次输出不是模型唯一表现。报告样本数、随机种子、失败/超时如何计分，以及是否选择 best-of-k。"], formula: { latex: "\\hat p=\\frac{1}{n}\\sum_i y_i,\\qquad SE(\\hat p)\\approx\\sqrt{\\hat p(1-\\hat p)/n}", explanation: "正态近似只作直觉；小样本或接近 0/1 时应使用更稳健区间。", symbols: [{ symbol: "y_i", meaning: "第 i 题是否正确" }, { symbol: "n", meaning: "题目数" }, { symbol: "SE", meaning: "估计标准误" }] }, checks: ["是否配对比较？", "随机生成重复了几次？"] },
        { title: "3. 评测也需要数据工程", intuition: "benchmark 本身会老化、污染并产生错误标签。", paragraphs: ["建立版本化 manifest，保存样本 id、原始来源、license、prompt、scorer 版本和模型输出。对异常高分做 overlap audit；对低一致性题做人审；对 LM judge 做位置互换、长度控制和人类校准。", "Lecture 12 最后的问题是 evaluation 的用途：开发诊断、模型选择、对外报告和风险门槛需要不同严谨度。把测试集反复用于调参会使它成为训练信号，应保留最终锁定集。"], example: { title: "一个泄漏的开发闭环", steps: ["每天看 test leaderboard 并按弱项调数据。", "虽然没有对 test 反向传播，但决策持续使用 test 反馈。", "最终 test 已变成开发集，分数对新样本乐观。"], result: "需要独立 dev、公开 test 和尽量少触碰的最终审计集。" }, checks: ["谁能访问锁定集？", "scorer 版本是否冻结？"] },
      ],
      pitfalls: ["只报总分不报 protocol", "对 LM judge 不做顺序互换", "把未检测到污染写成无污染"],
      exercises: [
        { question: "为什么同一题配对比较更好？", answer: "题目难度对两个模型共同作用；看逐题差异能减少不相关方差并定位胜负样本。" },
        { question: "反复看 test 但不训练梯度，为什么仍会过拟合？", answer: "研究者的数据、prompt 和模型选择由 test 反馈驱动，信息已进入开发过程。" },
      ],
      recordings: [{ title: "Lecture 12 · Evaluation", youtubeId: "JpAxdTWQJxM", note: "课堂把 capability、preference、agent、安全和垂直领域评测放到同一测量框架，并专门讨论 overlap 与质量。" }],
      sources: [script("12", "Evaluation"), video("JpAxdTWQJxM", "Lecture 12 · Evaluation"), assignment(4, "Data", "data")],
    },
    {
      slug: "data-sources-rights",
      index: 11,
      title: "预训练数据：来源、谱系与权利",
      subtitle: "Lecture 13：Common Crawl、Wikipedia、GitHub、arXiv 与公开数据集配方",
      duration: "4 小时",
      summary: "网页可访问不等于可任意训练。课程先追溯 raw source 和抓取机制，再比较 C4、The Pile、RefinedWeb、Dolma、DCLM 等配方，最后把许可、隐私和法律不确定性放进数据决策。",
      objectives: ["画出数据来源到训练 shard 的 provenance", "区分网页访问、copyright、license 与隐私", "比较不同公开数据集的来源/过滤逻辑"],
      prerequisites: ["网页与文件格式基础", "第 10 章评测"],
      concepts: [
        { name: "Data provenance", explanation: "记录内容来自哪里、何时获取、经历哪些转换以及许可/删除状态。", why: "没有谱系就无法复现、去重、响应删除或解释模型行为。", example: "raw WARC → WET 文本 → language filter → dedup cluster → token shard，每步保存版本。", boundary: "记录 URL 不代表已经获得训练许可，也不保证作者身份可验证。" },
        { name: "Common Crawl", explanation: "公开提供周期性网页抓取，WARC 含原始响应，WET 主要含提取文本。", why: "它规模大、覆盖广，是许多开放预训练集的原料。", example: "同一网页可在多个 crawl 和镜像出现，必须跨 snapshot 去重。", boundary: "Common Crawl 公开可下载不等于其中每页内容是公共领域。" },
        { name: "Dataset mixture", explanation: "训练数据通常组合 web、百科、书、代码、论文和问答，并给各源采样权重。", why: "不同来源在规模、质量、语言和能力贡献上不同。", example: "代码只占原始 bytes 的小部分，却可被上采样以提升代码能力。", boundary: "source label 是粗代理；同一来源内部质量差异可能更大。" },
        { name: "License 与 fair use", explanation: "license 是权利人授权条款；fair use 是依司法辖区与具体用途判断的抗辩/例外，不是数据集标签。", why: "数据团队必须把技术可获取性与法律可使用性分开。", example: "arXiv 元数据可能有 CC0 条款，论文正文的具体 license 却逐篇不同。", boundary: "本站不提供法律意见；有争议数据需要机构法律审查。" },
      ],
      sections: [
        { title: "1. 数据不是一个 tar 文件，而是一条可审计链", intuition: "模型问题往往要追溯到某个来源、抓取或过滤版本。", paragraphs: ["为每条文档保留 source URI、snapshot、获取时间、content hash、license signal、语言、过滤分数与 lineage。不可变 raw 层与可重建 processed 层分开；删除请求应能定位所有派生 shard，而不是只删数据库一行。", "Lecture 13 从“数据从哪里来”进入 copyright、license、lawsuits，再逐个看 Common Crawl、Wikipedia、GitHub、arXiv 和 StackExchange。课堂没有把法律争议说成已解决事实；本站也保持这一边界。"], checks: ["能否从 token shard 追到 raw source？", "删除是否覆盖缓存和派生版本？"] },
        { title: "2. 比较数据集要比较配方，不只比较 token 数", intuition: "一万亿 token 可以来自完全不同的质量与混合。", paragraphs: ["C4 以规则过滤 web；CCNet 以 Wikipedia 风格质量模型过滤；The Pile 混合多源；RefinedWeb 强调大规模网页过滤；Dolma 提供较完整处理记录；DCLM 用质量 classifier 的数据实验驱动选择。课程沿时间线展示配方变化。", "比较时记录 raw/kept 比、语言、时间范围、domain mix、dedup 层级、污染过滤、PII 策略与 license policy。模型结果还受 tokenizer、训练 compute 和架构影响，不能把差异全归因于数据集名字。"], example: { title: "同样 100B token 的两份数据", steps: ["A 含大量重复模板，unique n-gram 少。", "B 去重后来源较多，但高质量代码比例低。", "二者总 token 相同，训练动态和下游能力仍可完全不同。"], result: "规模是必要描述，不是质量充分统计。" }, checks: ["token 数在去重前还是后？", "是否报告各语言/域分布？"] },
        { title: "3. 权利与风险进入数据 schema", intuition: "法律/伦理不能等模型训完再补一张表。", paragraphs: ["访问控制、robots、站点条款、copyright、具体 license、个人信息与敏感内容是不同字段。某个字段通过不代表其他字段通过。对代码还需考虑 license inheritance、vendored dependency 和 secret；对论坛需考虑用户名与上下文隐私。", "课程列举诉讼与 fair-use 因素是为了建立问题清单，而非给统一判决。实践中保留 legal basis、地域、用途、审查人和变更日期，遇到不确定性升级给法务。"], checks: ["是否把“网上公开”当作 license？", "数据用途变化后是否重新审查？"] },
      ],
      pitfalls: ["把 Common Crawl 当成版权清洁数据", "只记最终 shard 不记 provenance", "用单一 quality score 代替语言/域/权利审计"],
      exercises: [
        { question: "WARC 与 WET 的学习上最重要区别？", answer: "WARC 保存更完整网页响应和元数据；WET 主要是抽取文本，更易处理但失去部分结构与证据。" },
        { question: "公开下载为何不等于可任意使用？", answer: "技术访问性与 copyright、license、条款、隐私和具体用途是不同问题。" },
      ],
      recordings: [{ title: "Lecture 13 · Data (Sources, Datasets)", youtubeId: "-qm0ln33G24", note: "课堂从来源、知识产权与许可进入历代公开预训练数据配方。" }],
      sources: [script("13", "Data I"), video("-qm0ln33G24", "Lecture 13 · Data (Sources, Datasets)"), assignment(4, "Data", "data")],
    },
    {
      slug: "data-pipeline",
      index: 12,
      title: "数据流水线：抽取、过滤、去重与混合",
      subtitle: "Lecture 14：把 Common Crawl 原料变成可训练、可评估的 token stream",
      duration: "5 小时",
      summary: "这讲按流水线顺序处理文本抽取、语言/质量/毒性/PII 过滤、精确与近似去重、数据混合和合成数据。每一步都可能提高某指标，也可能删掉某类人或污染评测。",
      objectives: ["设计可复现 pipeline manifest", "推导 Jaccard、MinHash 与 LSH", "用消融选择 mixture 而非凭感觉"],
      prerequisites: ["第 11 章", "集合与概率"],
      concepts: [
        { name: "Content extraction", explanation: "从 HTML/WET 中提取主要文本、标题、列表和代码，并去除导航、广告与 boilerplate。", why: "原始网页大量 token 不是正文，会浪费预算和教会模板噪声。", example: "同一页顶部菜单在全站重复；抽取失败会造成大规模近重复。", boundary: "激进抽取可能删掉表格、公式、alt text 和代码结构。" },
        { name: "Quality/filter classifier", explanation: "规则或模型为文档打语言、质量、毒性等分数，再按阈值保留或加权。", why: "在固定 compute 下提高有效训练信号。", example: "以参考高质量语料训练 classifier 区分候选网页。", boundary: "classifier 会复制参考集的风格和偏差，分数不是客观质量。" },
        { name: "MinHash", explanation: "在真正随机排列（或满足相应近似条件的哈希族）下，两个集合的最小哈希相等概率等于 Jaccard 相似度。工程实现通常用不同 seed 的快速哈希近似这些随机排列。", why: "无需对所有文档对计算完整集合交并。", example: "100 个近似独立签名中 82 个相等，可把 Jaccard 粗估为 0.82，并给出采样误差而非把它当精确值。", boundary: "等概率结论依赖随机排列/哈希假设；普通 seeded hash 不自动具有严格 min-wise independence。它估计的也只是所选 shingle 定义下的 Jaccard。" },
        { name: "LSH bands", explanation: "把 MinHash 签名分成 b 个 band、每 band r 行，任一 band 全相同则成为候选对。", why: "把全对比较降为只验证高概率近重复候选。", example: "相似度 s 的候选碰撞概率 1−(1−s^r)^b。", boundary: "LSH 只召回候选，最终还需精确相似度验证；漏检和误报都存在。" },
      ],
      sections: [
        { title: "1. Pipeline 顺序会改变结果", intuition: "先抽取、先过滤还是先去重，不是可交换操作。", paragraphs: ["一般流程包括 download → extract → normalize → language/quality/safety/PII filter → exact/near dedup → decontaminate → mix → tokenize/shard。若在抽取 boilerplate 前做 near-dedup，网站菜单可能让不同正文被误判相似；若先过滤再 dedup，已删除文档不参与 cluster representative 选择。", "每阶段保存输入数、保留数、原因码和样本审计。阈值需要按语言/域分层查看，否则总体保留率会掩盖小语种被大量删除。A4 的 tests 覆盖 extract、language id、PII、toxicity、quality 与 dedup；本站不实现其 TODO。"], checks: ["阶段顺序是否版本化？", "删除原因能否回溯到单文档？"] },
        { title: "2. 从 exact hash 到 MinHash-LSH", intuition: "精确副本容易找，改几个词的模板副本需要近似集合方法。", paragraphs: ["先把规范化文档切成 n-gram shingles 集合 A。Jaccard=|A∩B|/|A∪B|。在随机排列模型下，MinHash 签名位置的匹配率无偏估计 Jaccard；工程中用 seeded hash 近似时，应把这一点写成假设并用实测校准误差。LSH 再把签名分 band，避免比较所有 pair。", "参数 b、r 决定 S 曲线阈值。b 增大提高召回也增加候选；r 增大要求每 band 更严格。候选对仍应算真实 Jaccard，再用 union-find 聚 cluster，按来源/质量策略选 representative。"], formula: { latex: "J(A,B)=\\frac{|A\\cap B|}{|A\\cup B|},\\qquad P(candidate)=1-(1-J(A,B)^r)^b", explanation: "在 band 内各签名行近似独立的模型下，b 个 band 中只要一个 band 的 r 行都相同就产生候选。", symbols: [{ symbol: "A,B", meaning: "两文档的 shingle 集合" }, { symbol: "b", meaning: "band 数" }, { symbol: "r", meaning: "每 band 行数" }] }, checks: ["哈希族是否足以近似随机排列？", "shingle 与 normalization 是否固定？", "候选是否做精确复核？"] },
        { title: "3. Mixture 是训练超参数", intuition: "采样权重决定模型在哪些分布上花 token 预算。", paragraphs: ["设数据源 k 的采样概率 p_k。原始占比不是唯一选择：高质量小源可上采样，但重复 epoch 可能过拟合；大 web 源可下采样，却仍贡献覆盖。需要在小规模 controlled run 上做 mixture 消融，并同时看多类 validation/eval。", "Lecture 14 还讨论 synthetic/post-training data。模型生成的数据可扩展稀缺任务，但会继承生成器偏差、重复模式和错误；必须保留 generator、prompt、过滤器和 verifier 版本。"], formula: { latex: "p_k\\ge0,\\quad\\sum_kp_k=1,\\qquad D_k=p_kD", explanation: "预期给来源 k 的 token 预算是总预算 D 的 p_k 部分。", symbols: [{ symbol: "p_k", meaning: "来源 k 的采样概率" }, { symbol: "D_k", meaning: "来源 k 的预期 token 数" }, { symbol: "D", meaning: "总训练 token 预算" }] }, checks: ["小数据源重复了多少 epoch？", "mixture 改善是否跨多个 eval？"] },
      ],
      lab: { title: "实验：MinHash-LSH 近重复审计", goal: "构造改写文档，观察 exact hash、Jaccard、MinHash 与 LSH 的差异。", file: "/labs/cs336/minhash_dedup.py", steps: ["运行固定文档集", "调节 b/r", "添加短文本和模板前缀"], expected: ["精确副本一定聚类", "近重复在合理参数下成为候选", "输出 PASS"], sourceNote: "对应 Lecture 14 和 A4 dedup 单元；本站为标准库教学实现，不复制作业答案。" },
      recordings: [{ title: "Lecture 14 · Data", youtubeId: "5sxHosTLPF8", note: "课堂按 extraction/filter/dedup/mixing 走完整管线，并用 Jaccard、MinHash、LSH 现场数值例解释近重复。" }],
      pitfalls: ["把 classifier score 当真实质量", "LSH candidate 未复核就删除", "只看总体保留率不看语言/域切片"],
      exercises: [
        { question: "为什么近重复应在 boilerplate 处理后做？", answer: "共享菜单/页脚会人为提高不同正文的集合相似度，导致误删。" },
        { question: "MinHash 82/100 相等说明什么？", answer: "在独立 hash 假设下，它给出 Jaccard 约 0.82 的估计；仍有采样误差。" },
      ],
      sources: [script("14", "Data II"), video("5sxHosTLPF8", "Lecture 14 · Data"), assignment(4, "Data", "data")],
    },
    {
      slug: "sft-rlhf",
      index: 13,
      title: "Mid/Post-training：SFT、偏好与 RLHF",
      subtitle: "Lecture 15：把 next-token predictor 变成可控的对话与工具使用模型",
      duration: "5 小时",
      summary: "预训练数据规模大但行为目标松散；SFT 用目标回答示范定义行为，偏好数据再表达“哪个回答更好”。本章按课堂顺序讨论数据内容、SFT loss、reward model、PPO/RLHF 与 DPO，并保留现代配方公开信息有限这一事实。",
      objectives: ["区分 pretraining、SFT 和 preference data", "推导 pairwise preference loss", "解释 RLHF 与 DPO 的数据和优化差异"],
      prerequisites: ["第 3 章 NLL", "基本策略梯度直觉"],
      concepts: [
        { name: "Supervised fine-tuning", explanation: "在 instruction/context 后对理想 assistant response 做 teacher-forced NLL，通常只让 response token 计 loss。", why: "它把模型从续写互联网文本转向遵守指令、对话格式和工具协议。", example: "user token 作为条件，assistant 的每个 token 是标签；system/user 可被 loss mask 掉。", boundary: "SFT 只能模仿数据里展示的行为；少量高质数据也无法覆盖所有越狱和分布外任务。" },
        { name: "Preference pair", explanation: "对同一 prompt 给 chosen y⁺ 与 rejected y⁻，监督信号是相对排序而非唯一标准答案。", why: "开放式问题有多种正确回答，标注者往往更容易比较。", example: "两答都正确，但一个引用清楚、一个冗长含糊，标注 chosen/rejected。", boundary: "偏好受标注规范、人口和展示顺序影响；不是普遍人类价值。" },
        { name: "Reward model", explanation: "学习标量 rφ(x,y)，使 chosen 的分数高于 rejected，常用 Bradley–Terry logistic loss。", why: "把人类比较转成可对新采样回答打分的训练信号。", example: "若分差 r⁺−r⁻=0，模型给 chosen 胜率 0.5。", boundary: "reward 是代理；policy 过度优化会利用模型漏洞并偏离人类判断。" },
        { name: "KL regularization", explanation: "惩罚新 policy 偏离 reference/SFT policy，限制 reward optimization 的更新幅度。", why: "降低语言崩坏和 reward hacking 风险，保留基础能力。", example: "目标约为 E[r−β log(π/π_ref)]。", boundary: "KL 系数只控制分布距离，不保证事实、安全或公平。" },
      ],
      sections: [
        { title: "1. SFT 数据到底包含什么", intuition: "instruction tuning 的能力边界首先由示范覆盖决定。", paragraphs: ["Lecture 15 从 FLAN、Self-Instruct、Alpaca、ShareGPT/Vicuna、OpenAssistant 到更现代的 tool-use/code 数据，逐步展示 instruction、input/context、assistant response 与多轮 roles。高性能数据不只要求答案正确，还要覆盖格式、长度、拒答、工具调用和领域。", "训练时将会话渲染成 chat template，并明确哪些 token 计 loss。若 system/user 也计 loss，模型在浪费容量预测提示；若 assistant header 或 EOS 处理错，部署生成边界会不一致。"], formula: { latex: "\\mathcal L_{SFT}=-\\sum_t m_t\\log\\pi_\\theta(y_t\\mid x,y_{<t})", explanation: "m_t=1 表示该 response token 参与监督，prompt/padding 常为 0。", symbols: [{ symbol: "x", meaning: "instruction 与上下文" }, { symbol: "y", meaning: "目标回答" }, { symbol: "m_t", meaning: "loss mask" }] }, checks: ["chat template 与部署一致吗？", "只对 assistant response 计 loss 吗？"] },
        { title: "2. 从 pairwise label 到 reward", intuition: "偏好模型学习的是比较概率。", paragraphs: ["Bradley–Terry 假设 P(y⁺≻y⁻|x)=σ(r⁺−r⁻)，最小化 −log σ(Δr)。若 position、length 或 style 与标签相关，reward model 会利用这些捷径，因此数据收集应随机顺序、提供明确 rubric，并测跨域一致性。", "RLHF 再从当前 policy 采样，用 reward model 打分，并以 KL 约束更新。课堂明确提醒：现代闭源 post-training 配方公开信息稀少，不能把公开论文的简单图示当作当前系统全貌。"], formula: { latex: "\\mathcal L_{RM}=-\\log\\sigma(r_\\phi(x,y^+)-r_\\phi(x,y^-))", explanation: "只有分差受监督，reward 的绝对零点不可识别。", symbols: [{ symbol: "y⁺,y⁻", meaning: "chosen 与 rejected 回答" }, { symbol: "r_φ", meaning: "reward model 标量分数" }, { symbol: "σ", meaning: "logistic 函数" }] }, checks: ["chosen 是否总是更长？", "标注者一致性是否量化？"] },
        { title: "3. DPO 与 RLHF 不是同一种数据流", intuition: "DPO 直接在固定偏好对上调整 log-ratio；在线 RLHF 会持续采样当前 policy。", paragraphs: ["DPO 用 chosen/rejected 在 policy 与 reference 下的 log probability 差构造 logistic loss，避免显式 reward model 和 rollout loop。它实现简单、稳定，但通常是 offline：更新后看到的仍是旧 policy 产生的 pair。", "PPO/RLHF 能从当前 policy 生成新回答并探索，却需要 rollout、reward/value/reference 等组件。A5 optional safety handout 包含 DPO 方向；仓库无 LICENSE，本站只讲机制并链接，不提供解答。"], formula: { latex: "\\mathcal L_{DPO}=-\\log\\sigma\\!\\left(\\beta[(\\log\\pi_\\theta(y^+|x)-\\log\\pi_{ref}(y^+|x))-(\\log\\pi_\\theta(y^-|x)-\\log\\pi_{ref}(y^-|x))]\\right)", explanation: "DPO 提高 chosen 相对 reference 的优势，同时降低 rejected 的相对优势。", symbols: [{ symbol: "π_ref", meaning: "冻结参考 policy" }, { symbol: "β", meaning: "偏离参考的尺度/温度" }, { symbol: "π_θ", meaning: "待优化 policy" }] }, checks: ["序列 logprob 是 sum 还是长度归一化？", "偏好 pair 来自哪个 policy？"] },
      ],
      pitfalls: ["把 chosen 当唯一正确答案", "reward 上升就宣称人类满意度必升", "忽略 chat template 与 response loss mask"],
      exercises: [
        { question: "Reward model 的绝对分数为什么不可识别？", answer: "Bradley–Terry 只依赖两回答分差；给所有分数加同一常数不改变比较概率。" },
        { question: "DPO 相比在线 RLHF 的主要数据局限？", answer: "通常只优化固定离线偏好对，不能自动看到更新后 policy 新产生的失败模式。" },
      ],
      recordings: [{ title: "Lecture 15 · Mid/Post-Training", youtubeId: "2oH6PWPrYFo", note: "课堂从公开 SFT 数据实例走到 preference、RLHF 与直接偏好优化，同时强调现代配方披露有限。" }],
      sources: [slides("15", "After pretraining: SFT/RLHF"), video("2oH6PWPrYFo", "Lecture 15 · Mid/Post-Training"), assignment(5, "Alignment and Reasoning RL", "alignment"), { title: "Assignment 5 optional safety/DPO handout", url: "https://github.com/stanford-cs336/assignment5-alignment/blob/main/cs336_spring2026_assignment5_supplement_safety_rlhf.pdf", kind: "assignment", note: "官方补充作业；仓库未发现开放许可证，仅链接。" }],
    },
    {
      slug: "rlvr-grpo",
      index: 14,
      title: "RLVR：Policy Gradient、PPO 与 GRPO",
      subtitle: "Lecture 16：用可验证奖励训练数学与代码推理",
      duration: "7–8 小时",
      summary: "当答案能由数学 checker、unit tests 等程序验证时，reward 不必完全由偏好模型代理。本章按视频从 PPO 走到 GRPO，再细看归一化偏差和 DeepSeek-R1、Kimi K1.5、Qwen3；最后把 A5 的 RFT、MaxRL、off-policy GRPO 与 GSPO 放到同一张目标函数地图里。",
      objectives: ["推导 REINFORCE、PPO clipping 与 group-mean baseline", "区分 population/sample std 和 sequence/constant normalization", "复述 DeepSeek-R1、Kimi K1.5、Qwen3 的训练数据流", "区分 RFT、MaxRL、off-policy GRPO 与 GSPO"],
      prerequisites: ["第 13 章", "期望、梯度与 log probability"],
      concepts: [
        { name: "Verifiable reward", explanation: "答案可由确定或高可信程序检查，例如数值等价、编译与 unit tests。", why: "比主观 reward model 更直接地对齐目标，并可大规模自动评分。", example: "同一数学题采样 8 个解答，抽取最终答案后 checker 返回 0/1。", boundary: "checker 只验证它编码的条件；模型可能猜答案、利用漏洞或写不可读过程。" },
        { name: "Policy gradient", explanation: "用采样回报乘 log-policy 梯度，得到期望奖励梯度的 Monte Carlo 估计。", why: "离散 token 无法直接对采样动作求普通路径导数。", example: "高于 baseline 的回答增加其 token logprob，低于 baseline 的回答降低。", boundary: "估计方差高，长序列 credit assignment 仍困难。" },
        { name: "PPO surrogate", explanation: "rollout 由旧 policy 产生，更新时用 ratio=πθ/πold 重权；clipping 对正负 advantage 分别限制过大的有利更新。", why: "它允许复用一批 rollout 做若干更新，同时抑制 policy 一步走太远。", example: "A>0、ratio=1.5、ε=0.2 时上界用 1.2A；A<0、ratio=0.5 时更悲观的 0.8A 生效。", boundary: "clip 是逐样本启发式，不保证全局 KL 小；若 rollout 后立即只做一次更新，ratio 起初就是 1。" },
        { name: "Group-relative advantage", explanation: "对同一 prompt 的 G 个样本，把 reward 减组均值并可除组标准差，无需单独 value model。组均值含当前样本本身，所以期望梯度相对普通 policy gradient 会缩放为 (G−1)/G；方向不变，但并非严格等于原估计。", why: "同题样本形成局部比较，减少题目难度尺度差异。", example: "奖励 [1,1,0,0] 的均值 0.5；population std=0.5 得到 ±1，而 sample std≈0.577 得到 ±0.866。", boundary: "全同奖励时没有组内信号；必须声明 std 的 population/sample 口径。除 std 还会改变不同难度 prompt 的权重。" },
        { name: "Dr.GRPO", explanation: "移除 group-std normalization，并用统一常数而非各 response 自身长度归一化 token loss。", why: "这两项修正减少按题目方差和回答长度产生的隐式重权，使目标更接近原始期望奖励梯度。", example: "一条 20-token 和一条 200-token 回答若都除各自长度，每条序列总权重相近；统一除 BG·L 后，token 得到相同尺度。", boundary: "常数归一化不会自动解决 reward hacking、探索不足或 verifier 漏洞。" },
        { name: "RFT、MaxRL 与 GSPO", explanation: "RFT 只对通过 verifier 的 rollout 做 SFT；MaxRL 用组均值而非组标准差归一化；GSPO 使用 response 级联合概率比，而标准 off-policy GRPO 常在 token 级做 ratio/clipping。", why: "A5 把这些方法并列，是为了分离 baseline、难度重权、长度归一化和 off-policy 修正，而不是把所有变体叫 GRPO。", example: "同一 response 的 token ratios 为 [1.2,0.8]：token-level clipping 分别处理；GSPO 先把 response log-ratio 聚合后得到一个序列比率。", boundary: "这些名字在论文和代码库中可能有不同 normalizer/KL 细节，必须写出实际公式。" },
        { name: "Importance ratio 与 clipping", explanation: "用 πθ/πold 修正从旧 policy 采样的数据，并 clip 防单次更新过大。", why: "rollout 与多轮优化间 policy 已变化，需要限制 off-policy 偏差。", example: "ratio=1.5、ε=0.2 时 surrogate 使用不超过 1.2 的方向性上界。", boundary: "clip 是启发式 trust region，不保证所有状态 KL 都受限。" },
      ],
      sections: [
        { title: "1. PPO：把序列奖励接回 token logprob", intuition: "verifier 只在回答结束时给分，梯度却要穿过每个已采样 token。", paragraphs: ["把 response y 看成动作序列，πθ(y|x)=∏tπθ(y_t|x,y_<t)，所以 log joint probability 是 token logprob 之和。REINFORCE 用完整回答的回报或 advantage 加权这串和。若 baseline 只依赖 prompt/state 而不依赖当前动作，减去它不改期望，只减方差。", "PPO 再引入旧 policy。ratio r_t=πθ/πold 衡量更新后该 token 相对 rollout 时变了多少；clipped surrogate 对 A>0 与 A<0 采取方向相关的 min。课堂展示的语言模型 PPO 还含 value/GAE、每 token reference-KL 惩罚和最后 token 的任务 reward。LM 近似终局奖励 bandit 时 γ=λ=1 很常见，但这不是所有 agent trajectory 的普遍设置。"], formula: { latex: "L^{clip}=\\mathbb E_t\\!\\left[\\min(r_tA_t,\\operatorname{clip}(r_t,1-\\epsilon,1+\\epsilon)A_t)\\right],\\qquad r_t=\\frac{\\pi_\\theta(y_t|h_t)}{\\pi_{old}(y_t|h_t)}", explanation: "正负 advantage 下 min 的有效分支不同；实现应分别测试 ratio 过大和过小。", symbols: [{ symbol: "A_t", meaning: "token/trajectory advantage" }, { symbol: "π_old", meaning: "采样 rollout 的 policy" }, { symbol: "ε", meaning: "clip range" }] }, checks: ["rollout 是 on-policy 还是复用了旧 batch？", "KL、terminal reward 与 advantage 分别在哪个 token 上？"] },
        { title: "2. GRPO 的组均值不是普通外部 baseline", intuition: "同组平均数包含当前样本，所以会轻微缩放期望梯度。", paragraphs: ["对同一 prompt 采 G 个独立回答，令 μ=(1/G)ΣR_j。用 R_j−μ 加权每条 logprob 可以消除题目绝对难度，但 μ 包含 R_j 自身。把期望逐项展开，会得到普通 policy-gradient 期望的 (G−1)/G 倍。这个常数不改变无限小更新方向，却说明‘完全无偏’说法不准确。", "再除组标准差会进一步改变目标：二元 reward 的 std 与通过率相关，中等难度题和极易/极难题得到不同重权。理论公式常写 population std，官方 A5 实现提示使用默认 torch.std 的 sample std；G=4、奖励 [1,1,0,0] 时二者分别给 ±1 与 ±0.866，代码和文字必须选同一口径。"], formula: { latex: "A_j=\\frac{R_j-\\mu}{s+\\epsilon},\\quad \\mu=\\frac1G\\sum_jR_j,\\quad \\mathbb E[\\hat g_{mean}]=\\frac{G-1}{G}\\nabla_\\theta J", explanation: "最后一个等式针对同 prompt 的 iid rollout 和仅减组均值的估计；再除随机 std 后不再只是常数缩放。", symbols: [{ symbol: "G", meaning: "同 prompt rollout 数" }, { symbol: "μ", meaning: "组均值" }, { symbol: "s", meaning: "必须声明 population/sample 的组标准差" }] }, checks: ["std 使用 G 还是 G−1 作分母？", "全 0/全 1 group 是否返回零而不是除零？"] },
        { title: "3. 长度归一化、Dr.GRPO 与 A5 变体", intuition: "loss 最后怎么平均，会决定长回答和难题的相对权重。", paragraphs: ["标准 GRPO 常先对每条 response 的 token loss 求平均，再对序列求平均。这让一条 20-token 与 200-token response 的总权重相近，因此长序列里的单 token 权重更小。Dr.GRPO 移除 group-std normalization，并把全 batch token loss 除以固定常数 Z（常见为 BG·max_generation_length），避免 normalizer 随采样内容改变。", "A5 还拆出三条轴：RFT 不减 baseline，只保留 verifier 通过的样本做 maximum likelihood；MaxRL 用组均值作 advantage normalizer，偏向当前成功率低的题；off-policy GRPO 用 token ratio/clipping，GSPO 则先聚合 response log-ratio再做 sequence-level 修正。它们不是一条由旧到新的单排名，而是不同偏差、方差和系统成本的取舍。"], formula: { latex: "L_{seq}=\\frac1{BG}\\sum_i\\frac{1}{|y_i|}\\sum_t\\ell_{it},\\qquad L_{const}=\\frac1Z\\sum_{i,t}\\ell_{it}", explanation: "sequence normalization 让每条回答总权重接近一致；constant normalization 让单 token 尺度一致。", symbols: [{ symbol: "|y_i|", meaning: "第 i 条 response 的有效 token 数" }, { symbol: "Z", meaning: "与本批采样长度无关的预先确定常数" }] }, example: { title: "没有学习信号的 group", steps: ["一道题采样 8 个答案且全部错误，reward 全 0。", "减组均值后所有 advantage 为 0，标准 GRPO 与 Dr.GRPO 本轮都不更新该题。", "增加相同失败样本的训练步数不会创造正样本，需要调整初始模型、采样温度、题目课程或奖励设计。"], result: "有效 group 比例是训练健康度指标，不应只看平均 reward。" }, checks: ["normalizer 会随 response 长度变化吗？", "RFT/MaxRL/GRPO 的 baseline 和 normalizer 是否分别记录？"] },
        { title: "4. DeepSeek-R1：可验证奖励之后仍是多阶段配方", intuition: "R1 的案例不是‘只靠一个 GRPO loss’，而是 base、RL、SFT 与广义对齐的组合。", paragraphs: ["视频先回到 DeepSeekMath 的 GRPO，再看 R1/R1-Zero。公开配方以 DeepSeek-V3 base 为起点，verifiable 阶段使用答案准确性和格式奖励；后续加入 reasoning SFT、语言一致性等信号，再把可验证与不可验证任务带回更广的 SFT/RLHF。课程特别提醒，公开报告对部分数据与工程细节描述有限，不能从一张流程图反推出全部实现。", "格式奖励可帮助模型产生可解析的 thinking/final 区段，却也给 reward hacking 留接口；只验最终答案不保证推理过程正确。R1 的 distillation 说明强模型生成的长推理可通过 SFT 迁移到较小模型，这与在线 RL 的探索和 credit assignment 是不同数据流。"], figures: [{ title: "DeepSeek-R1 的公开结果图", src: "https://raw.githubusercontent.com/stanford-cs336/lectures/main/images/deepseek-r1-benchmarks.png", href: "https://github.com/stanford-cs336/lectures/blob/main/images/deepseek-r1-benchmarks.png", caption: "结果图只能说明公开配方的最终表现；不能单独归因于 GRPO、格式奖励或某一个训练阶段。", credit: "Stanford CS336 Lecture 16，远程引用，未在本站复制", kind: "image" }], checks: ["奖励验证的是答案、格式还是过程？", "哪些阶段是公开事实，哪些工程细节没有披露？"] },
        { title: "5. Kimi K1.5：长度控制、数据生成与 rollout 系统", intuition: "当 CoT 变长，长度本身会成为优化变量，也会放大在线推理成本。", paragraphs: ["课程中的 Kimi K1.5 从 long-CoT SFT 进入在线 RL。数学题可用答案等价 checker，代码题由已有解答扩展测试；数据先经过难度和可验证性筛选。Kimi 使用显式长度奖励，让错误回答在组内相对过长时受罚，并对正确回答的长度控制采用不同逻辑，避免把‘越长越好’写入单一奖励。", "on-policy rollout 往往比反向训练慢，并需要在 inference engine 与 training framework 之间切换权重。因而算法报告必须同时看 reward、长度分布、有效 group、rollout tokens/s 与模型更新时间；只画 reward 曲线会隐藏系统吞吐和 stale-policy 程度。"], example: { title: "长度奖励为何要看正确性", steps: ["若答案错误且远长于同组中心，额外惩罚可减少无效长输出。", "若答案正确，简单惩罚所有长答案可能打掉必要推理。", "分别记录正确/错误样本长度，才能判断模型是在学会简洁还是学会提前结束。"], result: "长度控制是任务 reward、normalization 和生成预算共同作用的结果。" }, checks: ["长度 reward 是否与正确性条件化？", "rollout 与训练 policy 相差了多少步？"] },
        { title: "6. Qwen3：thinking mode、test-time scaling 与 agentic RL", intuition: "推理后训练开始同时控制是否思考、思考多久，以及能否在环境中完成轨迹。", paragraphs: ["Lecture 16 最后用 Qwen3 收束公开配方：reasoning SFT 后在筛选过的可验证任务上做 GRPO，再接更广的 RLHF/融合；课件给出的公开案例在一个阶段使用 3,995 个样本，数字本身不应脱离筛选、生成和 verifier 配方解释。thinking-mode fusion 让同一模型在显式思考与快速回答间切换，test-time scaling 则在推理时增加采样或搜索预算。", "Qwen3 Coder/agent 部分把 action 从纯 token 扩展为工具调用和环境轨迹。reward 可能来自编译、测试和任务完成，但环境构造、超时、工具错误和轨迹长度都会进入训练分布。此时‘bandit-like final reward’仍可用作近似，却不能忽略多步状态与执行失败。"], checks: ["训练样本数是否连同过滤/生成方法解释？", "agent reward 区分模型错误、工具错误和环境超时吗？"] },
      ],
      lab: { title: "实验：从 PPO clipping 到 GRPO/GSPO 口径", goal: "用纯数值例拆开组均值、population/sample std、正负 clipping、长度归一化和 token/sequence importance ratio。", file: "/labs/cs336/grpo_mechanics.py", steps: ["比较同一奖励组的两种 std", "验证全对/全错组", "分别测试正负 advantage clipping", "比较 sequence/constant loss 与 token/response ratio"], expected: ["组均值 baseline 的期望缩放为 (G−1)/G", "sample-std advantage 幅度小于 population-std", "正负 clipping 分支均正确", "两种长度/ratio 口径产生可解释差异", "输出 PASS"], sourceNote: "对应 Lecture 16 与 A5 的公开数学定义；独立标量实验不实现官方 trainer、adapter 或作业 TODO。" },
      recordings: [{ title: "Lecture 16 · Post-Training — RLVR", youtubeId: "dIFAi87Ws4E", note: "课堂沿 PPO→GRPO→variants 展开，并用实现片段和训练曲线讨论 reward shaping、KL 与归一化。" }],
      pitfalls: ["把 verifier 通过等同于过程正确", "全同 reward group 仍强行除零方差", "只监控训练 reward 不做独立 eval"],
      exercises: [
        { question: "减 baseline 为什么不改变期望梯度？", answer: "对给定 x，E_{y~π}[b(x)∇logπ(y|x)]=b(x)∇Σ_yπ(y|x)=0。" },
        { question: "GRPO 为什么省显存？", answer: "它用同 prompt 的组内奖励构造 advantage，可不训练/保存单独 value model；rollout 与 reference 仍有成本。" },
      ],
      sources: [slides("16", "Reinforcement learning from verifiable rewards"), video("dIFAi87Ws4E", "Lecture 16 · Post-Training — RLVR"), assignment(5, "Alignment and Reasoning RL", "alignment")],
    },
    {
      slug: "multimodality-frontiers",
      index: 15,
      title: "多模态语言模型与课程收束",
      subtitle: "Lecture 17 + guest boundary：图像编码、projector、AnyRes、生成与全栈研究",
      duration: "6–7 小时",
      summary: "Lecture 17 从 CLIP/SigLIP 的图文对齐开始，沿 LLaVA、OneVision 与 Qwen-VL 系列追踪视觉特征如何进入语言模型，再用 Chameleon 讨论统一理解与生成。本章保留原课的模型演进、数据阶段和数值例，并把视觉 token 重新放回推理资源账本。",
      objectives: ["推导 CLIP/SigLIP 的配对目标", "追踪 CLIP/LLaVA/OneVision/Qwen-VL 的 shape 与训练阶段", "计算 AnyRes/dynamic-resolution 的 token 与 attention 成本", "区分连续视觉 encoder、离散图像 token 与 diffusion decoder"],
      prerequisites: ["第 3、9、13 章", "卷积/ViT 基础有帮助"],
      concepts: [
        { name: "CLIP 与 SigLIP", explanation: "CLIP 在一个 batch 内把正确图文对作为多类匹配目标，图到文、文到图双向归一化；SigLIP 则把每个图文组合视作二元正负配对，用 sigmoid logistic loss。", why: "海量网页图文对没有精细类别标签，对比目标能把监督放在配对关系上。", example: "batch 有 B 对图文，CLIP 每张图要从 B 段文本中选对应项；SigLIP 对 B² 个组合分别判正负，通信模式也随之变化。", boundary: "学到的是 caption 提供的语义和偏差；全局对齐不保证 OCR、计数或像素级定位。" },
        { name: "Vision encoder", explanation: "把图像切成 patches，经 ViT/CLIP encoder 产生一串视觉特征。", why: "语言模型接收 d_model 向量序列，原始像素必须先压成语义表示。", example: "336×336 图像以 14×14 patch 切分，会产生 24×24=576 个 patch features（忽略特殊 token）。", boundary: "encoder 特征保留什么由其训练目标决定；冻结 encoder 也会限制细粒度适应。resize/crop 还可能先删掉边缘和小字。" },
        { name: "Projector", explanation: "线性层或小 MLP 把 vision feature dimension 映射到 LLM embedding dimension。", why: "两模块通道维不同，且需要学习让视觉表示落入语言模型可用空间。", example: "d_v=1024 映射到 d_lm=4096，再像 token embeddings 一样插入序列。", boundary: "维度对齐不等于语义对齐，仍需图文和指令数据训练。" },
        { name: "AnyRes / dynamic resolution", explanation: "把高分辨率或不同长宽比图像分块编码，并保留全局视图或布局信息。", why: "固定正方形 resize 会扭曲文字、裁掉细节，单图 patch 数又受上下文预算限制。", example: "长截图拆成多个 336×336 tiles，再加缩略全图，视觉 token 数随 tiles 增长。", boundary: "更多 tiles 提高细节也让 attention、prefill 与 KV 成本上升。" },
        { name: "mRoPE 与时空位置", explanation: "Qwen2-VL 一类模型把旋转位置的轴扩展到时间、高度和宽度，使图像/视频 token 保留二维或三维坐标。", why: "把所有视觉 token 当一条无结构文本序列，会弱化上下左右、帧顺序和不同分辨率之间的关系。", example: "视频 token 可同时带 temporal、height、width 三个位置索引，再与文字位置共同进入 attention。", boundary: "位置编码能表达坐标，不会自动解决对象跟踪、OCR 或长视频压缩。" },
        { name: "离散与连续视觉 token", explanation: "理解模型常把连续 encoder features 投影给 LLM；统一生成模型也可能用 VQ tokenizer 把图像编码成离散 ids，或让 Transformer 产生条件后交给 diffusion decoder。", why: "理解更关注语义压缩，生成还需保留颜色、纹理和局部细节，两者需要的信息密度不同。", example: "Chameleon 把图像与文本都表示成离散 token；另一条 omni 路径让 LLM 输出连续条件，再由 diffusion 生成像素。", boundary: "能接收图像不等于能生成图像；VQ token、连续 embedding 和 diffusion latent 不能互换名称。" },
        { name: "Omni / multimodal generation", explanation: "模型不仅理解图像，还可能统一处理音频、视频并生成非文本模态。", why: "共享序列接口可让跨模态上下文互相条件化。", example: "视觉 encoder 输入 + 文本 decoder 输出与离散图像 tokenizer 输出是不同设计点。", boundary: "能输入多模态不代表能生成多模态；离散 tokenizer、diffusion decoder 和连续表征不能混为一谈。" },
      ],
      sections: [
        { title: "1. CLIP 与 SigLIP：先学会哪段文字属于哪张图", intuition: "对比学习先建立跨模态坐标系，还没有训练一个会对话的视觉助手。", paragraphs: ["CLIP 从一个 batch 的 B 对图文出发，分别经 image encoder 与 text encoder 得到归一化向量，点积除温度形成 B×B 相似度矩阵。对每张图，正确文本是分类标签；反向再让每段文本选择正确图像。官方讲义沿用 CLIP 的关键事实：训练数据约 4 亿图文对，最佳公开配置之一是 ViT-L/14@336；336/14=24，所以忽略特殊 token 时有 576 个 patches。", "SigLIP 不对整行做 multiclass softmax，而对每个图文组合做 sigmoid 正负分类。它让 loss 不必依赖全局 batch softmax，课程用它说明目标函数会改变跨设备通信和 batch-size 行为。两者都以网页配对为监督，caption 没提到的小字、数量和空间关系不一定进入全局 embedding。"], formula: { latex: "L_{CLIP}=\\tfrac12[CE(S,I_B)+CE(S^\\top,I_B)],\\quad S_{ij}=\\frac{u_i^\\top v_j}{\\tau};\\qquad L_{SigLIP}=\\sum_{ij}\\log(1+e^{-z_{ij}(u_i^\\top v_j/\\tau+b)})", explanation: "CLIP 做双向 B 类分类；SigLIP 对每个 pair 使用 z=+1/−1 的 logistic loss。", symbols: [{ symbol: "u_i,v_j", meaning: "归一化图像/文本 embedding" }, { symbol: "τ", meaning: "温度" }, { symbol: "z_ij", meaning: "图文是否匹配的 ±1 标签" }] }, figures: [{ title: "CLIP 的 batch 内图文匹配", src: "https://raw.githubusercontent.com/stanford-cs336/lectures/main/images/clip.png", href: "https://github.com/stanford-cs336/lectures/blob/main/images/clip.png", caption: "每个 batch 同时构造 B 个正对和大量错配负对；两个方向的归一化不要漏掉。", credit: "Stanford CS336 Lecture 17，远程引用，未在本站复制", kind: "image" }], checks: ["embedding 是否先归一化？", "正样本是对角线，还是数据排列已经改变？", "结论是语义对齐还是细粒度定位？"] },
        { title: "2. LLaVA：projector 接口与两阶段训练", intuition: "最小 VLM 是 vision encoder + projector + causal LM，而不是把 PNG 当文字。", paragraphs: ["LLaVA 使用 CLIP ViT-L/14 提取 patch features，线性 projector W 把 d_v 映射到语言模型 d_lm，再把视觉向量放进文本 embedding 序列。Lecture 17 沿原论文介绍约 158K 条由 COCO caption/检测信息经 GPT-4 生成的视觉指令数据；这个数字描述首版数据配方，不能当现代 VLM 的通用规模。", "训练分两步：第一阶段冻结 vision encoder 与 LLM，只训练 W，让视觉特征进入语言空间；第二阶段继续冻结 vision encoder，训练 projector 与 LLM，学习问答和对话行为。chat template、image placeholder、视觉 token 位置和 causal mask 必须一致。维度对齐只是接口成立，语义与行为仍来自训练数据。"], formula: { latex: "v_{1:m}=W E_{vision}(I),\\qquad p(y|I,x)=\\prod_t p(y_t|v_{1:m},x,y_{<t})", explanation: "projector 输出 m 个 d_lm 向量；回答 token 的 NLL 才训练对话行为。", symbols: [{ symbol: "I", meaning: "输入图像" }, { symbol: "E_vision", meaning: "冻结或可训练的视觉编码器" }, { symbol: "W", meaning: "线性/MLP projector" }, { symbol: "m", meaning: "视觉 token 数" }] }, figures: [{ title: "LLaVA 的视觉接口", src: "https://raw.githubusercontent.com/stanford-cs336/lectures/main/images/llava-architecture.png", href: "https://github.com/stanford-cs336/lectures/blob/main/images/llava-architecture.png", caption: "CLIP features 经 projector 后作为 token-like embeddings 进入 LLM；图中连接不代表只训练一个阶段。", credit: "Stanford CS336 Lecture 17，远程引用，未在本站复制", kind: "image" }], checks: ["每一阶段冻结哪些参数？", "assistant loss mask 是否排除图像和 user prompt？"] },
        { title: "3. OneVision 与 AnyRes：细节最终都要付 token 预算", intuition: "保留高分辨率不是免费开关，而是把更多 tiles 送进同一个上下文。", paragraphs: ["固定 336×336 center crop 会切掉边缘，并把收据、网页和图表的小字压缩。AnyRes 选择与原图长宽比接近的 tile grid：每块按 encoder 原生分辨率编码，通常再保留一张全局缩略图和布局信息。LLaVA-OneVision 使用 SigLIP encoder、两层 MLP projector 与 Qwen2 语言模型，并区分单图、多图和视频的 token 配额：单图可用高分辨率，多图降低每图预算，视频进一步压缩每帧。", "若 patch size 固定，图像高宽各加倍，patch 数约变 4 倍。把 N_v 个视觉 token 与 N_t 个文本 token 送入 dense attention，score 主项按 (N_t+N_v)² 增长；prefill 和激活会先变贵，生成阶段是否缓存视觉 token 还取决于实现。只说分辨率提升而不报告 tile/token 数，无法比较模型。"], formula: { latex: "N_{patch}=\\left\\lfloor\\frac{H}{P}\\right\\rfloor\\left\\lfloor\\frac{W}{P}\\right\\rfloor,\\qquad F_{attn}\\propto(N_t+N_v)^2d", explanation: "未计 class token、2×2 merge、padding 与各模型的视觉压缩，因此部署应使用实际输出 shape。", symbols: [{ symbol: "H,W", meaning: "送入 encoder 的高宽" }, { symbol: "P", meaning: "patch size" }, { symbol: "N_v,N_t", meaning: "视觉与文本 token 数" }] }, figures: [{ title: "AnyRes 的 tile 与全局视图", src: "https://raw.githubusercontent.com/stanford-cs336/lectures/main/images/llava-onevision-anyres.png", href: "https://github.com/stanford-cs336/lectures/blob/main/images/llava-onevision-anyres.png", caption: "切块保留局部细节，同时要保存 grid 顺序或全局视图；简单拼接会丢空间关系。", credit: "Stanford CS336 Lecture 17，远程引用，未在本站复制", kind: "image" }], example: { title: "一张收据为什么仍会读错", steps: ["固定 crop 先把边缘字段切掉或缩到不可辨。", "caption 对齐只监督‘这是一张收据’，没有逐字段 OCR。", "LLM 根据常见格式补出金额，看起来流畅却没有视觉证据。"], result: "需要分辨率策略、OCR/grounding 数据和不可回答评测，而不是只换更大 LLM。" }, checks: ["每种输入最终产生多少视觉 token？", "tile layout 如何编码？"] },
        { title: "4. Qwen-VL 系列：从固定 adaptor 到动态时空 token", intuition: "模型代际变化集中在视觉压缩、位置表示和训练数据阶段，不只是换一个更大的 ViT。", paragraphs: ["原课先看 Qwen-VL：OpenCLIP ViT-bigC、带二维位置的 cross-attention adaptor，将图像压成固定 256 个表示，并用 <img>/<box>/<ref> 支持图像区间与 grounding；训练从大规模弱图文对齐、到高质量任务数据、再到 instruction tuning。Qwen2-VL 改用 dynamic resolution，不再把所有图压成同一 token 数，并以 2×2 merge 压缩视觉网格。", "Qwen2-VL 的 mRoPE 把 temporal/height/width 分量带进位置旋转，适配图像与视频；Qwen3-VL 继续扩展 encoder、预训练任务和 agent/grounding 数据。阅读这些发布时要把 architecture、data、resolution 和 evaluation 分开：结果提升不能仅归因于某个 positional encoding。"], figures: [{ title: "Qwen2-VL 动态分辨率架构", src: "https://raw.githubusercontent.com/stanford-cs336/lectures/main/images/qwen2-vl-architecture.png", href: "https://github.com/stanford-cs336/lectures/blob/main/images/qwen2-vl-architecture.png", caption: "动态视觉 token、merge 与语言模型接口共同决定实际序列长度；不能继续假设每图固定 576 token。", credit: "Stanford CS336 Lecture 17，远程引用，未在本站复制", kind: "image" }], checks: ["视觉 token 是固定长度还是随分辨率变化？", "位置编码表示了时间与二维坐标吗？", "训练阶段和冻结策略是否混写？"] },
        { title: "5. 从 Chameleon 到 omni：理解和生成需要不同细节", intuition: "把所有模态叫 token 只是接口统一，token 背后的编码目标仍可能完全不同。", paragraphs: ["Chameleon 用离散 image tokenizer 把图像与文字 token 放进同一自回归序列，使模型可以交错理解和生成。离散图像 token 要保留足够像素细节，序列会比只做语义理解的 CLIP features 更长，训练还要处理模态不平衡和图像 token 的局部统计。", "另一条路径保留连续 vision/audio encoder，让 Transformer 负责跨模态理解和规划，再用 diffusion decoder 生成图像或音频。Lecture 17 的总结明确区分 comprehension 与 generation：前者偏语义压缩，后者需要细粒度重建。‘omni’描述输入输出能力目标，不等价于某个固定 tokenizer 或 loss。", "官方 schedule 另列 Lecture 18 Daniel Selsam，但没有公开材料，因此本站不补写主题。Dan Fu 的公开视频讨论 inference engine、KV cache、megakernel 与循环架构，已放在第 9 章；它不是多模态课的内容。"], figures: [{ title: "Chameleon 的统一离散 token 路径", src: "https://raw.githubusercontent.com/stanford-cs336/lectures/main/images/chameleon.png", href: "https://github.com/stanford-cs336/lectures/blob/main/images/chameleon.png", caption: "图像与文本都成为离散序列后可交错建模，但图像 token 的信息密度和评价方式仍不同。", credit: "Stanford CS336 Lecture 17，远程引用，未在本站复制", kind: "image" }], checks: ["模型只是理解多模态，还是也能生成？", "非文本输出由自回归 token 还是 diffusion decoder 产生？"] },
      ],
      lab: { title: "实验：视觉 patch、对比损失与 projector 接口", goal: "不用下载模型也能核对视觉 token 数、CLIP/SigLIP 损失方向、线性 projector shape 和图文序列 mask。", file: "/labs/cs336/multimodal_smoke.py", steps: ["计算 336/14 patch 数并改变分辨率", "比较对齐与打乱配对的双向 CLIP loss", "计算 SigLIP 正负 pair loss", "把 toy vision features 投影并拼接文本 token"], expected: ["336×336、patch14 得 576", "对齐 pair 的 CLIP loss 低于打乱配对", "projector 输出维度等于 d_lm", "回答位置能读取全部视觉 token", "输出 PASS"], sourceNote: "对应 Lecture 17 的 shape 与目标函数；代码为独立标量/列表实验，不复制无许可证的 lecture_17.py。" },
      recordings: [
        { title: "Lecture 17 · Alignment — Multimodality", youtubeId: "26FtD08ZpOU", note: "课堂从图像预处理/encoding、向 LLM 注入视觉特征、AnyRes 走向 Omni models。" },
      ],
      pitfalls: ["把 projector 的维度匹配说成已经语义对齐", "把 CLIP 与 SigLIP 写成同一个 softmax loss", "图像分辨率增加却不计算视觉 token", "把能理解图像写成能生成图像", "为填课程目录而虚构未公开 guest lecture 内容"],
      exercises: [
        { question: "图像宽高各翻倍，patch size 不变，patch 数怎样变？", answer: "两个轴的 patch 数各翻倍，总 patch 数约变 4 倍。" },
        { question: "CLIP 对比训练与多模态 SFT 的目标差异？", answer: "前者对齐成对图文全局表征；后者在图像/文本条件下监督 assistant response 的 token 概率与行为。" },
      ],
      sources: [
        script("17", "Multimodal models"),
        video("26FtD08ZpOU", "Lecture 17 · Alignment — Multimodality"),
        { title: "Spring 2026 schedule：Lecture 18 Daniel Selsam", url: `${course}#schedule`, kind: "course", note: "官方仅列讲者；核对时没有公开课件或录像，本站不补写内容。" },
        { title: "CS336 2026 官方 YouTube playlist", url: playlist, kind: "video", note: "截至核对时包含 Lectures 1–17 与 Dan Fu guest recording。" },
      ],
    },
  ],
} satisfies OpenCourse;
